// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://purl.org/ontology/bibo/');

/**
 * [bibo](http://purl.org/ontology/bibo/})
 */
const bibo = {
  /**
    * **[edition](http://purl.org/ontology/bibo/edition)** (property)
    * 
    * The name defining a special edition of a document. Normally its a literal value composed of a version number and words.
    */
    edition: prefixer('edition'),

    /**
    * **[page end](http://purl.org/ontology/bibo/pageEnd)** (property)
    * 
    * Ending page number within a continuous page range.
    */
    pageEnd: prefixer('pageEnd'),

    /**
    * **[issue](http://purl.org/ontology/bibo/issue)** (property)
    * 
    * An issue number
    */
    issue: prefixer('issue'),

    /**
    * **[locator](http://purl.org/ontology/bibo/locator)** (property)
    * 
    * A description (often numeric) that locates an item within a containing document or collection.
    */
    locator: prefixer('locator'),

    /**
    * **[page start](http://purl.org/ontology/bibo/pageStart)** (property)
    * 
    * Starting page number within a continuous page range.
    */
    pageStart: prefixer('pageStart'),

    /**
    * **[volume](http://purl.org/ontology/bibo/volume)** (property)
    * 
    * A volume number
    */
    volume: prefixer('volume'),

    /**
    * **[abstract](http://purl.org/ontology/bibo/abstract)** (property)
    * 
    * A summary of the resource.
    */
    abstract: prefixer('abstract'),

    /**
    * **[date argued](http://purl.org/ontology/bibo/argued)** (property)
    * 
    * The date on which a legal case is argued before a court. Date is of format xsd:date
    */
    argued: prefixer('argued'),

    /**
    * **[chapter](http://purl.org/ontology/bibo/chapter)** (property)
    * 
    * An chapter number
    */
    chapter: prefixer('chapter'),

    /**
    * **[Academic Article](http://purl.org/ontology/bibo/AcademicArticle)** (class)
    * 
    * A scholarly academic article, typically published in a journal.
    */
    AcademicArticle: prefixer('AcademicArticle'),

    /**
    * **[content](http://purl.org/ontology/bibo/content)** (property)
    * 
    * This property is for a plain-text rendering of the content of a Document. While the plain-text content of an entire document could be described by this property.
    */
    content: prefixer('content'),

    /**
    * **[Article](http://purl.org/ontology/bibo/Article)** (class)
    * 
    * A written composition in prose, usually nonfiction, on a specific topic, forming an independent part of a book or other publication, as a newspaper or magazine.
    */
    Article: prefixer('Article'),

    /**
    * **[Document](http://purl.org/ontology/bibo/Document)** (class)
    * 
    * A document (noun) is a bounded physical representation of body of information designed with the capacity (and usually intent) to communicate. A document may manifest symbolic, diagrammatic or sensory-representational information.
    */
    Document: prefixer('Document'),

    /**
    * **[audio document](http://purl.org/ontology/bibo/AudioDocument)** (class)
    * 
    * An audio document; aka record.
    */
    AudioDocument: prefixer('AudioDocument'),

    /**
    * **[audio-visual document](http://purl.org/ontology/bibo/AudioVisualDocument)** (class)
    * 
    * An audio-visual document; film, video, and so forth.
    */
    AudioVisualDocument: prefixer('AudioVisualDocument'),

    /**
    * **[Bill](http://purl.org/ontology/bibo/Bill)** (class)
    * 
    * Draft legislation presented for discussion to a legal body.
    */
    Bill: prefixer('Bill'),

    /**
    * **[Legislation](http://purl.org/ontology/bibo/Legislation)** (class)
    * 
    * A legal document proposing or enacting a law or a group of laws.
    */
    Legislation: prefixer('Legislation'),

    /**
    * **[Book](http://purl.org/ontology/bibo/Book)** (class)
    * 
    * A written or printed work of fiction or nonfiction, usually on sheets of paper fastened or bound together within covers.
    */
    Book: prefixer('Book'),

    /**
    * **[number of pages](http://purl.org/ontology/bibo/numPages)** (property)
    * 
    * The number of pages contained in a document
    */
    numPages: prefixer('numPages'),

    /**
    * **[Book Section](http://purl.org/ontology/bibo/BookSection)** (class)
    * 
    * A section of a book.
    */
    BookSection: prefixer('BookSection'),

    /**
    * **[number of volumes](http://purl.org/ontology/bibo/numVolumes)** (property)
    * 
    * The number of volumes contained in a collection of documents (usually a series, periodical, etc.).
    */
    numVolumes: prefixer('numVolumes'),

    /**
    * **[document part](http://purl.org/ontology/bibo/DocumentPart)** (class)
    * 
    * a distinct part of a larger document or collected document.
    */
    DocumentPart: prefixer('DocumentPart'),

    /**
    * **[number](http://purl.org/ontology/bibo/number)** (property)
    * 
    * A generic item or document number. Not to be confused with issue number.
    */
    number: prefixer('number'),

    /**
    * **[Brief](http://purl.org/ontology/bibo/Brief)** (class)
    * 
    * A written argument submitted to a court.
    */
    Brief: prefixer('Brief'),

    /**
    * **[Legal Case Document](http://purl.org/ontology/bibo/LegalCaseDocument)** (class)
    * 
    * A document accompanying a legal case.
    */
    LegalCaseDocument: prefixer('LegalCaseDocument'),

    /**
    * **[pages](http://purl.org/ontology/bibo/pages)** (property)
    * 
    * A string of non-contiguous page spans that locate a Document within a Collection. Example: 23-25, 34, 54-56. For continuous page ranges, use the pageStart and pageEnd properties.
    */
    pages: prefixer('pages'),

    /**
    * **[Chapter](http://purl.org/ontology/bibo/Chapter)** (class)
    * 
    * A chapter of a book.
    */
    Chapter: prefixer('Chapter'),

    /**
    * **[Code](http://purl.org/ontology/bibo/Code)** (class)
    * 
    * A collection of statutes.
    */
    Code: prefixer('Code'),

    /**
    * **[prefix name](http://purl.org/ontology/bibo/prefixName)** (property)
    * 
    * The prefix of a name
    */
    prefixName: prefixer('prefixName'),

    /**
    * **[Periodical](http://purl.org/ontology/bibo/Periodical)** (class)
    * 
    * A group of related documents issued at regular intervals.
    */
    Periodical: prefixer('Periodical'),

    /**
    * **[section](http://purl.org/ontology/bibo/section)** (property)
    * 
    * A section number
    */
    section: prefixer('section'),

    /**
    * **[Collected Document](http://purl.org/ontology/bibo/CollectedDocument)** (class)
    * 
    * A document that simultaneously contains other documents.
    */
    CollectedDocument: prefixer('CollectedDocument'),

    /**
    * **[Collection](http://purl.org/ontology/bibo/Collection)** (class)
    * 
    * A collection of Documents or Collections
    */
    Collection: prefixer('Collection'),

    /**
    * **[short title](http://purl.org/ontology/bibo/shortTitle)** (property)
    * 
    * The abbreviation of a title.
    */
    shortTitle: prefixer('shortTitle'),

    /**
    * **[Conference](http://purl.org/ontology/bibo/Conference)** (class)
    * 
    * A meeting for consultation or discussion.
    */
    Conference: prefixer('Conference'),

    /**
    * **[Court Reporter](http://purl.org/ontology/bibo/CourtReporter)** (class)
    * 
    * A collection of legal cases.
    */
    CourtReporter: prefixer('CourtReporter'),

    /**
    * **[suffix name](http://purl.org/ontology/bibo/suffixName)** (property)
    * 
    * The suffix of a name
    */
    suffixName: prefixer('suffixName'),

    /**
    * **[Document Status](http://purl.org/ontology/bibo/DocumentStatus)** (class)
    * 
    * The status of the publication of a document.
    */
    DocumentStatus: prefixer('DocumentStatus'),

    /**
    * **[uri](http://purl.org/ontology/bibo/uri)** (property)
    * 
    * Universal Resource Identifier of a document
    */
    uri: prefixer('uri'),

    /**
    * **[Edited Book](http://purl.org/ontology/bibo/EditedBook)** (class)
    * 
    * An edited book.
    */
    EditedBook: prefixer('EditedBook'),

    /**
    * **[EMail](http://purl.org/ontology/bibo/Email)** (class)
    * 
    * A written communication addressed to a person or organization and transmitted electronically.
    */
    Email: prefixer('Email'),

    /**
    * **[Personal Communication Document](http://purl.org/ontology/bibo/PersonalCommunicationDocument)** (class)
    * 
    * A personal communication manifested in some document.
    */
    PersonalCommunicationDocument: prefixer('PersonalCommunicationDocument'),

    /**
    * **[Excerpt](http://purl.org/ontology/bibo/Excerpt)** (class)
    * 
    * A passage selected from a larger work.
    */
    Excerpt: prefixer('Excerpt'),

    /**
    * **[Film](http://purl.org/ontology/bibo/Film)** (class)
    * 
    * aka movie.
    */
    Film: prefixer('Film'),

    /**
    * **[Hearing](http://purl.org/ontology/bibo/Hearing)** (class)
    * 
    * An instance or a session in which testimony and arguments are presented, esp. before an official, as a judge in a lawsuit.
    */
    Hearing: prefixer('Hearing'),

    /**
    * **[Image](http://purl.org/ontology/bibo/Image)** (class)
    * 
    * A document that presents visual or diagrammatic information.
    */
    Image: prefixer('Image'),

    /**
    * **[Interview](http://purl.org/ontology/bibo/Interview)** (class)
    * 
    * A formalized discussion between two or more people.
    */
    Interview: prefixer('Interview'),

    /**
    * **[Issue](http://purl.org/ontology/bibo/Issue)** (class)
    * 
    * something that is printed or published and distributed, esp. a given number of a periodical
    */
    Issue: prefixer('Issue'),

    /**
    * **[Journal](http://purl.org/ontology/bibo/Journal)** (class)
    * 
    * A periodical of scholarly journal Articles.
    */
    Journal: prefixer('Journal'),

    /**
    * **[Legal Document](http://purl.org/ontology/bibo/LegalDocument)** (class)
    * 
    * A legal document; for example, a court decision, a brief, and so forth.
    */
    LegalDocument: prefixer('LegalDocument'),

    /**
    * **[Decision](http://purl.org/ontology/bibo/LegalDecision)** (class)
    * 
    * A document containing an authoritative determination (as a decree or judgment) made after consideration of facts or law.
    */
    LegalDecision: prefixer('LegalDecision'),

    /**
    * **[Letter](http://purl.org/ontology/bibo/Letter)** (class)
    * 
    * A written or printed communication addressed to a person or organization and usually transmitted by mail.
    */
    Letter: prefixer('Letter'),

    /**
    * **[Magazine](http://purl.org/ontology/bibo/Magazine)** (class)
    * 
    * A periodical of magazine Articles. A magazine is a publication that is issued periodically, usually bound in a paper cover, and typically contains essays, stories, poems, etc., by many writers, and often photographs and drawings, frequently specializing in a particular subject or area, as hobbies, news, or sports.
    */
    Magazine: prefixer('Magazine'),

    /**
    * **[Manual](http://purl.org/ontology/bibo/Manual)** (class)
    * 
    * A small reference book, especially one giving instructions.
    */
    Manual: prefixer('Manual'),

    /**
    * **[Manuscript](http://purl.org/ontology/bibo/Manuscript)** (class)
    * 
    * An unpublished Document, which may also be submitted to a publisher for publication.
    */
    Manuscript: prefixer('Manuscript'),

    /**
    * **[Map](http://purl.org/ontology/bibo/Map)** (class)
    * 
    * A graphical depiction of geographic features.
    */
    Map: prefixer('Map'),

    /**
    * **[Multivolume Book](http://purl.org/ontology/bibo/MultiVolumeBook)** (class)
    * 
    * A loose, thematic, collection of Documents, often Books.
    */
    MultiVolumeBook: prefixer('MultiVolumeBook'),

    /**
    * **[Newspaper](http://purl.org/ontology/bibo/Newspaper)** (class)
    * 
    * A periodical of documents, usually issued daily or weekly, containing current news, editorials, feature articles, and usually advertising.
    */
    Newspaper: prefixer('Newspaper'),

    /**
    * **[Note](http://purl.org/ontology/bibo/Note)** (class)
    * 
    * Notes or annotations about a resource.
    */
    Note: prefixer('Note'),

    /**
    * **[Patent](http://purl.org/ontology/bibo/Patent)** (class)
    * 
    * A document describing the exclusive right granted by a government to an inventor to manufacture, use, or sell an invention for a certain number of years.
    */
    Patent: prefixer('Patent'),

    /**
    * **[Performance](http://purl.org/ontology/bibo/Performance)** (class)
    * 
    * A public performance.
    */
    Performance: prefixer('Performance'),

    /**
    * **[Personal Communication](http://purl.org/ontology/bibo/PersonalCommunication)** (class)
    * 
    * A communication between an agent and one or more specific recipients.
    */
    PersonalCommunication: prefixer('PersonalCommunication'),

    /**
    * **[Proceedings](http://purl.org/ontology/bibo/Proceedings)** (class)
    * 
    * A compilation of documents published from an event, such as a conference.
    */
    Proceedings: prefixer('Proceedings'),

    /**
    * **[Quote](http://purl.org/ontology/bibo/Quote)** (class)
    * 
    * An excerpted collection of words.
    */
    Quote: prefixer('Quote'),

    /**
    * **[Reference Source](http://purl.org/ontology/bibo/ReferenceSource)** (class)
    * 
    * A document that presents authoritative reference information, such as a dictionary or encylopedia .
    */
    ReferenceSource: prefixer('ReferenceSource'),

    /**
    * **[Report](http://purl.org/ontology/bibo/Report)** (class)
    * 
    * A document describing an account or statement describing in detail an event, situation, or the like, usually as the result of observation, inquiry, etc..
    */
    Report: prefixer('Report'),

    /**
    * **[Series](http://purl.org/ontology/bibo/Series)** (class)
    * 
    * A loose, thematic, collection of Documents, often Books.
    */
    Series: prefixer('Series'),

    /**
    * **[Slide](http://purl.org/ontology/bibo/Slide)** (class)
    * 
    * A slide in a slideshow
    */
    Slide: prefixer('Slide'),

    /**
    * **[Slideshow](http://purl.org/ontology/bibo/Slideshow)** (class)
    * 
    * A presentation of a series of slides, usually presented in front of an audience with written text and images.
    */
    Slideshow: prefixer('Slideshow'),

    /**
    * **[Specification](http://purl.org/ontology/bibo/Specification)** (class)
    * 
    * A document describing a specification.
    */
    Specification: prefixer('Specification'),

    /**
    * **[Standard](http://purl.org/ontology/bibo/Standard)** (class)
    * 
    * A document describing a standard: a specification organized through a standards body.
    */
    Standard: prefixer('Standard'),

    /**
    * **[Statute](http://purl.org/ontology/bibo/Statute)** (class)
    * 
    * A bill enacted into law.
    */
    Statute: prefixer('Statute'),

    /**
    * **[Thesis](http://purl.org/ontology/bibo/Thesis)** (class)
    * 
    * A document created to summarize research findings associated with the completion of an academic degree.
    */
    Thesis: prefixer('Thesis'),

    /**
    * **[Thesis degree](http://purl.org/ontology/bibo/ThesisDegree)** (class)
    * 
    * The academic degree of a Thesis
    */
    ThesisDegree: prefixer('ThesisDegree'),

    /**
    * **[annotates](http://purl.org/ontology/bibo/annotates)** (property)
    * 
    * Critical or explanatory note for a Document.
    */
    annotates: prefixer('annotates'),

    /**
    * **[Webpage](http://purl.org/ontology/bibo/Webpage)** (class)
    * 
    * A web page is an online document available (at least initially) on the world wide web. A web page is written first and foremost to appear on the web, as distinct from other online resources such as books, manuscripts or audio documents which use the web primarily as a distribution mechanism alongside other more traditional methods such as print.
    */
    Webpage: prefixer('Webpage'),

    /**
    * **[list of authors](http://purl.org/ontology/bibo/authorList)** (property)
    * 
    * An ordered list of authors. Normally, this list is seen as a priority list that order authors by importance.
    */
    authorList: prefixer('authorList'),

    /**
    * **[Website](http://purl.org/ontology/bibo/Website)** (class)
    * 
    * A group of Webpages accessible on the Web.
    */
    Website: prefixer('Website'),

    /**
    * **[list of contributors](http://purl.org/ontology/bibo/contributorList)** (property)
    * 
    * An ordered list of contributors. Normally, this list is seen as a priority list that order contributors by importance.
    */
    contributorList: prefixer('contributorList'),

    /**
    * **[Workshop](http://purl.org/ontology/bibo/Workshop)** (class)
    * 
    * A seminar, discussion group, or the like, that emphasizes zxchange of ideas and the demonstration and application of techniques, skills, etc.
    */
    Workshop: prefixer('Workshop'),

    /**
    * **[cited by](http://purl.org/ontology/bibo/citedBy)** (property)
    * 
    * Relates a document to another document that cites the
    * first document.
    */
    citedBy: prefixer('citedBy'),

    /**
    * **[cites](http://purl.org/ontology/bibo/cites)** (property)
    * 
    * Relates a document to another document that is cited
    * by the first document as reference, comment, review, quotation or for
    * another purpose.
    */
    cites: prefixer('cites'),

    /**
    * **[court](http://purl.org/ontology/bibo/court)** (property)
    * 
    * A court associated with a legal document; for example, that which issues a decision.
    */
    court: prefixer('court'),

    /**
    * **[degree](http://purl.org/ontology/bibo/degree)** (property)
    * 
    * The thesis degree.
    */
    degree: prefixer('degree'),

    /**
    * **[director](http://purl.org/ontology/bibo/director)** (property)
    * 
    * A Film director.
    */
    director: prefixer('director'),

    /**
    * **[distributor](http://purl.org/ontology/bibo/distributor)** (property)
    * 
    * Distributor of a document or a collection of documents.
    */
    distributor: prefixer('distributor'),

    /**
    * **[editor](http://purl.org/ontology/bibo/editor)** (property)
    * 
    * A person having managerial and sometimes policy-making responsibility for the editorial part of a publishing firm or of a newspaper, magazine, or other publication.
    */
    editor: prefixer('editor'),

    /**
    * **[list of editors](http://purl.org/ontology/bibo/editorList)** (property)
    * 
    * An ordered list of editors. Normally, this list is seen as a priority list that order editors by importance.
    */
    editorList: prefixer('editorList'),

    /**
    * **[interviewee](http://purl.org/ontology/bibo/interviewee)** (property)
    * 
    * An agent that is interviewed by another agent.
    */
    interviewee: prefixer('interviewee'),

    /**
    * **[interviewer](http://purl.org/ontology/bibo/interviewer)** (property)
    * 
    * An agent that interview another agent.
    */
    interviewer: prefixer('interviewer'),

    /**
    * **[issuer](http://purl.org/ontology/bibo/issuer)** (property)
    * 
    * An entity responsible for issuing often informally published documents such as press releases, reports, etc.
    */
    issuer: prefixer('issuer'),

    /**
    * **[organizer](http://purl.org/ontology/bibo/organizer)** (property)
    * 
    * The organizer of an event; includes conference organizers, but also government agencies or other bodies that are responsible for conducting hearings.
    */
    organizer: prefixer('organizer'),

    /**
    * **[owner](http://purl.org/ontology/bibo/owner)** (property)
    * 
    * Owner of a document or a collection of documents.
    */
    owner: prefixer('owner'),

    /**
    * **[presented at](http://purl.org/ontology/bibo/presentedAt)** (property)
    * 
    * Relates a document to an event; for example, a paper to a conference.
    */
    presentedAt: prefixer('presentedAt'),

    /**
    * **[presents](http://purl.org/ontology/bibo/presents)** (property)
    * 
    * Relates an event to associated documents; for example, conference to a paper.
    */
    presents: prefixer('presents'),

    /**
    * **[producer](http://purl.org/ontology/bibo/producer)** (property)
    * 
    * Producer of a document or a collection of documents.
    */
    producer: prefixer('producer'),

    /**
    * **[recipient](http://purl.org/ontology/bibo/recipient)** (property)
    * 
    * An agent that receives a communication document.
    */
    recipient: prefixer('recipient'),

    /**
    * **[review of](http://purl.org/ontology/bibo/reviewOf)** (property)
    * 
    * Relates a review document to a reviewed thing (resource, item, etc.).
    */
    reviewOf: prefixer('reviewOf'),

    /**
    * **[status](http://purl.org/ontology/bibo/status)** (property)
    * 
    * The publication status of (typically academic) content.
    */
    status: prefixer('status'),

    /**
    * **[transcript of](http://purl.org/ontology/bibo/transcriptOf)** (property)
    * 
    * Relates a document to some transcribed original.
    */
    transcriptOf: prefixer('transcriptOf'),

    /**
    * **[translation of](http://purl.org/ontology/bibo/translationOf)** (property)
    * 
    * Relates a translated document to the original document.
    */
    translationOf: prefixer('translationOf'),

    /**
    * **[translator](http://purl.org/ontology/bibo/translator)** (property)
    * 
    * A person who translates written document from one language to another.
    */
    translator: prefixer('translator'),

  
  };

export default bibo

