// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://creativecommons.org/ns#');

/**
 * [cc](http://creativecommons.org/ns#})
 */
const cc = {
  /**
    * **[Requirement](http://creativecommons.org/ns#Requirement)** (class)
    * 
    * an action that may or
    * may not be requested of you
    */
    Requirement: prefixer('Requirement'),

    /**
    * **[Prohibition](http://creativecommons.org/ns#Prohibition)** (class)
    * 
    * something you may be
    * asked not to do
    */
    Prohibition: prefixer('Prohibition'),

    /**
    * **[Permission](http://creativecommons.org/ns#Permission)** (class)
    * 
    * an action that may or
    * may not be allowed or desired
    */
    Permission: prefixer('Permission'),

    /**
    * **[Jurisdiction](http://creativecommons.org/ns#Jurisdiction)** (class)
    * 
    * the legal jurisdiction
    * of a license
    */
    Jurisdiction: prefixer('Jurisdiction'),

    /**
    * **[License](http://creativecommons.org/ns#License)** (class)
    * 
    * a set of
    * requests/permissions to users of a Work, e.g. a
    * copyright license, the public domain, information
    * for distributors
    */
    License: prefixer('License'),

    /**
    * **[Work](http://creativecommons.org/ns#Work)** (class)
    * 
    * a potentially
    * copyrightable work
    */
    Work: prefixer('Work'),

  
  };

export default cc

