// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://commontag.org/ns#');

/**
 * [ctag](http://commontag.org/ns#})
 */
const ctag = {
  /**
    * **[Author Tag](http://commontag.org/ns#AuthorTag)** (class)
    * 
    * A Tag asserted by the author of a content resource.
    */
    AuthorTag: prefixer('AuthorTag'),

    /**
    * **[Tag](http://commontag.org/ns#Tag)** (class)
    * 
    * A Common Tag associating a URI and a keyword to annotate a resource.
    */
    Tag: prefixer('Tag'),

    /**
    * **[Auto Tag](http://commontag.org/ns#AutoTag)** (class)
    * 
    * A Tag asserted by an automated tool on a content resource.
    */
    AutoTag: prefixer('AutoTag'),

    /**
    * **[Reader Tag](http://commontag.org/ns#ReaderTag)** (class)
    * 
    * A Tag asserted by the reader (consumer) of a content resource.
    */
    ReaderTag: prefixer('ReaderTag'),

    /**
    * **[Tagged Content](http://commontag.org/ns#TaggedContent)** (class)
    * 
    * Content which has one or more Common Tag.
    */
    TaggedContent: prefixer('TaggedContent'),

    /**
    * **[is about](http://commontag.org/ns#isAbout)** (property)
    * 
    * A resource (URI) representing the concepts described by the content.
    */
    isAbout: prefixer('isAbout'),

    /**
    * **[tag label](http://commontag.org/ns#label)** (property)
    * 
    * A local, human-readable name for a Tag.
    */
    label: prefixer('label'),

    /**
    * **[means](http://commontag.org/ns#means)** (property)
    * 
    * A a resource (URI) representing the conceptual meaning of a Tag.
    */
    means: prefixer('means'),

    /**
    * **[tagged](http://commontag.org/ns#tagged)** (property)
    * 
    * Links a resource to a Common Tag.
    */
    tagged: prefixer('tagged'),

    /**
    * **[tagging date](http://commontag.org/ns#taggingDate)** (property)
    * 
    * The date the Tag was assigned.
    */
    taggingDate: prefixer('taggingDate'),

  
  };

export default ctag

