// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://datashapes.org/dash#');

/**
 * [dash](http://datashapes.org/dash#})
 */
const dash = {
  /**
    * **[API Status](http://datashapes.org/dash#APIStatus)** (class)
    * 
    * The class of possible values for dash:apiStatus.
    */
    APIStatus: prefixer('APIStatus'),

    /**
    * **[Property role](http://datashapes.org/dash#PropertyRole)** (class)
    * 
    * The class of roles that a property (shape) may take for its focus nodes.
    */
    PropertyRole: prefixer('PropertyRole'),

    /**
    * **[Failure result](http://datashapes.org/dash#FailureResult)** (class)
    * 
    * A result representing a validation failure such as an unsupported recursion.
    */
    FailureResult: prefixer('FailureResult'),

    /**
    * **[Failure test case result](http://datashapes.org/dash#FailureTestCaseResult)** (class)
    * 
    * Represents a failure of a test case.
    */
    FailureTestCaseResult: prefixer('FailureTestCaseResult'),

    /**
    * **[Test case result](http://datashapes.org/dash#TestCaseResult)** (class)
    * 
    * Base class for results produced by running test cases.
    */
    TestCaseResult: prefixer('TestCaseResult'),

    /**
    * **[Graph update](http://datashapes.org/dash#GraphUpdate)** (class)
    * 
    * A suggestion consisting of added and/or deleted triples, represented as rdf:Statements via dash:addedTriple and dash:deletedTriple.
    */
    GraphUpdate: prefixer('GraphUpdate'),

    /**
    * **[Suggestion](http://datashapes.org/dash#Suggestion)** (class)
    * 
    * Base class of suggestions that modify a graph to "fix" the source of a validation result.
    */
    Suggestion: prefixer('Suggestion'),

    /**
    * **[Multi-function](http://datashapes.org/dash#MultiFunction)** (class)
    * 
    * A multi-function is a function that can return zero or more result objects consisting of one or more result variables. While normal (SPARQL/SHACL) functions can only return a single result node, multi-functions may not only return multiple nodes but even multiple individual variables per solution.
    * 
    * A common way of defining multi-functions is by wrapping a SPARQL SELECT query, using dash:SPARQLMultiFunction. However, some MultiFunctions (in TopBraid) may also be implemented natively.
    */
    MultiFunction: prefixer('MultiFunction'),

    /**
    * **[SPARQL CONSTRUCT template](http://datashapes.org/dash#SPARQLConstructTemplate)** (class)
    * 
    * Encapsulates one or more SPARQL CONSTRUCT queries that can be parameterized. Parameters will become pre-bound variables in the queries.
    */
    SPARQLConstructTemplate: prefixer('SPARQLConstructTemplate'),

    /**
    * **[SPARQL multi-function](http://datashapes.org/dash#SPARQLMultiFunction)** (class)
    * 
    * A multi-function based on a SPARQL SELECT query. The query gets executed with the arguments pre-bound to the variables declared as parameters. The results of the multi-function are all result bindings from the SPARQL result set.
    */
    SPARQLMultiFunction: prefixer('SPARQLMultiFunction'),

    /**
    * **[SPARQL SELECT template](http://datashapes.org/dash#SPARQLSelectTemplate)** (class)
    * 
    * Encapsulates a SPARQL SELECT query that can be parameterized. Parameters will become pre-bound variables in the query.
    */
    SPARQLSelectTemplate: prefixer('SPARQLSelectTemplate'),

    /**
    * **[SPARQL UPDATE suggestion generator](http://datashapes.org/dash#SPARQLUpdateSuggestionGenerator)** (class)
    * 
    * A SuggestionGenerator based on a SPARQL UPDATE query (sh:update), producing an instance of dash:GraphUpdate. The INSERTs become dash:addedTriple and the DELETEs become dash:deletedTriple. The WHERE clause operates on the data graph with the pre-bound variables $focusNode, $predicate and $value, as well as the other pre-bound variables for the parameters of the constraint.
    * 
    * In many cases, there may be multiple possible suggestions to fix a problem. For example, with sh:maxLength there are many ways to slice a string. In those cases, the system will first iterate through the result variables from a SELECT query (sh:select) and apply these results as pre-bound variables into the UPDATE query.
    */
    SPARQLUpdateSuggestionGenerator: prefixer('SPARQLUpdateSuggestionGenerator'),

    /**
    * **[Suggestion generator](http://datashapes.org/dash#SuggestionGenerator)** (class)
    * 
    * Base class of objects that can generate suggestions (added or deleted triples) for a validation result of a given constraint component.
    */
    SuggestionGenerator: prefixer('SuggestionGenerator'),

    /**
    * **[Script function](http://datashapes.org/dash#ScriptFunction)** (class)
    * 
    * Script functions can be used from SPARQL queries and will be injected into the generated prefix object (in JavaScript, for ADS scripts). The dash:js will be inserted into a generated JavaScript function and therefore needs to use the return keyword to produce results. These JS snippets can access the parameter values based on the local name of the sh:Parameter's path. For example ex:value can be accessed using value.
    * 
    * SPARQL use note: Since these functions may be used from any data graph and any shapes graph, they must not rely on any API apart from what's available in the shapes graph that holds the rdf:type triple of the function itself. In other words, at execution time from SPARQL, the ADS shapes graph will be the home graph of the function's declaration.
    */
    ScriptFunction: prefixer('ScriptFunction'),

    /**
    * **[Shape script](http://datashapes.org/dash#ShapeScript)** (class)
    * 
    * A shape script contains extra code that gets injected into the API for the associated node shape. In particular you can use this to define additional functions that operate on the current focus node (the this variable in JavaScript).
    */
    ShapeScript: prefixer('ShapeScript'),

    /**
    * **[Success result](http://datashapes.org/dash#SuccessResult)** (class)
    * 
    * A result representing a successfully validated constraint.
    */
    SuccessResult: prefixer('SuccessResult'),

    /**
    * **[Success test case result](http://datashapes.org/dash#SuccessTestCaseResult)** (class)
    * 
    * Represents a successful run of a test case.
    */
    SuccessTestCaseResult: prefixer('SuccessTestCaseResult'),

    /**
    * **[Suggestion result](http://datashapes.org/dash#SuggestionResult)** (class)
    * 
    * Class of results that have been produced as suggestions, not through SHACL validation. How the actual results are produced is up to implementers. Each instance of this class should have values for sh:focusNode, sh:resultMessage, sh:resultSeverity (suggested default: sh:Info), and dash:suggestion to point at one or more suggestions.
    */
    SuggestionResult: prefixer('SuggestionResult'),

    /**
    * **[Test environment](http://datashapes.org/dash#TestEnvironment)** (class)
    * 
    * Abstract base class for test environments, holding information on how to set up a test case.
    */
    TestEnvironment: prefixer('TestEnvironment'),

    /**
    * **[Action](http://datashapes.org/dash#Action)** (class)
    * 
    * An executable command triggered by an agent, backed by a Script implementation. Actions may get deactivated using sh:deactivated.
    */
    Action: prefixer('Action'),

    /**
    * **[abstract](http://datashapes.org/dash#abstract)** (property)
    * 
    * Indicates that a class is "abstract" and cannot be used in asserted rdf:type triples. Only non-abstract subclasses of abstract classes should be instantiated directly.
    */
    abstract: prefixer('abstract'),

    /**
    * **[Shape class](http://datashapes.org/dash#ShapeClass)** (class)
    * 
    * A class that is also a node shape. This class can be used as rdf:type instead of the combination of rdfs:Class and sh:NodeShape.
    */
    ShapeClass: prefixer('ShapeClass'),

    /**
    * **[reifiable by](http://datashapes.org/dash#reifiableBy)** (property)
    * 
    * Can be used to specify the node shape that may be applied to reified statements produced by a property shape. The property shape must have a URI resource as its sh:path. The values of this property must be node shapes. User interfaces can use this information to determine which properties to present to users when reified statements are explored or edited. Use dash:None to indicate that no reification should be permitted.
    */
    reifiableBy: prefixer('reifiableBy'),

    /**
    * **[Script](http://datashapes.org/dash#Script)** (class)
    * 
    * An executable unit implemented in one or more languages such as JavaScript.
    */
    Script: prefixer('Script'),

    /**
    * **[Action group](http://datashapes.org/dash#ActionGroup)** (class)
    * 
    * A group of ResourceActions, used to arrange items in menus etc. Similar to sh:PropertyGroups, they may have a sh:order and should have labels (in multiple languages if applicable).
    */
    ActionGroup: prefixer('ActionGroup'),

    /**
    * **[editor](http://datashapes.org/dash#editor)** (property)
    * 
    * Can be used to link a property shape with an editor, to state a preferred editing widget in user interfaces.
    */
    editor: prefixer('editor'),

    /**
    * **[Action test case](http://datashapes.org/dash#ActionTestCase)** (class)
    * 
    * A test case that evaluates a dash:Action using provided input parameters. Requires exactly one value for dash:action and will operate on the test case's graph (with imports) as both data and shapes graph.
    * 
    * Currently only supports read-only actions, allowing the comparison of actual results with the expected results.
    */
    ActionTestCase: prefixer('ActionTestCase'),

    /**
    * **[viewer](http://datashapes.org/dash#viewer)** (property)
    * 
    * Can be used to link a property shape with a viewer, to state a preferred viewing widget in user interfaces.
    */
    viewer: prefixer('viewer'),

    /**
    * **[Test case](http://datashapes.org/dash#TestCase)** (class)
    * 
    * A test case to verify that a (SHACL-based) feature works as expected.
    */
    TestCase: prefixer('TestCase'),

    /**
    * **[co-exists with](http://datashapes.org/dash#coExistsWith)** (property)
    * 
    * Specifies a property that must have a value whenever the property path has a value, and must have no value whenever the property path has no value.
    */
    coExistsWith: prefixer('coExistsWith'),

    /**
    * **[Single editor](http://datashapes.org/dash#SingleEditor)** (class)
    * 
    * An editor for individual value nodes.
    */
    SingleEditor: prefixer('SingleEditor'),

    /**
    * **[local constraint](http://datashapes.org/dash#localConstraint)** (property)
    * 
    * Can be set to true for those constraint components where the validation does not require to visit any other triples than the shape definitions and the direct property values of the focus node mentioned in the property constraints. Examples of this include sh:minCount and sh:hasValue.
    * 
    * Constraint components that are marked as such can be optimized by engines, e.g. they can be evaluated client-side at form submission time, without having to make a round-trip to a server, assuming the client has downloaded a complete snapshot of the resource.
    * 
    * Any component marked with dash:staticConstraint is also a dash:localConstraint.
    */
    localConstraint: prefixer('localConstraint'),

    /**
    * **[Single viewer](http://datashapes.org/dash#SingleViewer)** (class)
    * 
    * A viewer for a single value.
    */
    SingleViewer: prefixer('SingleViewer'),

    /**
    * **[Change script](http://datashapes.org/dash#ChangeScript)** (class)
    * 
    * Class of ADS scripts that are executed after edits to the data graph were made, but within the same edit.
    * 
    * These scripts may access the current changes from the graphs with names dataset.addedGraphURI and dataset.deletedGraphURI to learn about which resource values have been added or deleted. For example query them using graph.withDataGraph(dataset.addedGraphURI, ...) or via SPARQL's GRAPH keyword.
    * 
    * Change scripts may then perform further changes which would again become visible to other change scripts. They MUST NOT have other side effects though, because they may get executed in Preview mode, or the change may cause constraint violations and then be rejected. For side effects, after the change has been applied, use commit scripts (dash:CommitScript).
    * 
    * Change scripts are executed by their relative sh:order, with a default value of 0. Use lower values to execute before other scripts.
    */
    ChangeScript: prefixer('ChangeScript'),

    /**
    * **[has value in](http://datashapes.org/dash#hasValueIn)** (property)
    * 
    * Specifies a constraint that at least one of the value nodes must be a member of the given list.
    */
    hasValueIn: prefixer('hasValueIn'),

    /**
    * **[Commit script](http://datashapes.org/dash#CommitScript)** (class)
    * 
    * Class of ADS scripts that are executed after edits to the data graph were made and have been committed.
    * 
    * These scripts may access the changes that have just happened from the graphs with names dataset.addedGraphURI and dataset.deletedGraphURI to learn about which resource values have been added or deleted. For example query them using graph.withDataGraph(dataset.addedGraphURI, ...) or via SPARQL's GRAPH keyword.
    * 
    * Commit scripts may then perform side effects such as updating other graphs or sending out notifications to external systems. For edits that should be made within a finishing change, use change scripts (dash:ChangeScript).
    * 
    * Commit scripts are executed by their relative sh:order, with a default value of 0. Use lower values to execute before other scripts.
    */
    CommitScript: prefixer('CommitScript'),

    /**
    * **[has value with class](http://datashapes.org/dash#hasValueWithClass)** (property)
    * 
    * Specifies a constraint that at least one of the value nodes must be an instance of a given class.
    */
    hasValueWithClass: prefixer('hasValueWithClass'),

    /**
    * **[Constructor](http://datashapes.org/dash#Constructor)** (class)
    * 
    * A script that is executed when a new instance of the class associated via dash:constructor is created, e.g. from a New button. Such scripts typically declare one or more parameters that are collected from the user when the script starts. The values of these parameters can be used as named variables in the script for arbitrary purposes such as setting the URI or initializing some property values of the new instance.
    * 
    * The variable focusNode will hold the named node of the selected type, for example when a constructor is associated with a superclass but the user has pressed New for a subclass.
    * 
    * The last expression of the script will be used as result of the constructor, so that the surrounding tool knows which resource shall be navigated to next.
    */
    Constructor: prefixer('Constructor'),

    /**
    * **[Editor](http://datashapes.org/dash#Editor)** (class)
    * 
    * The class of widgets for editing value nodes.
    */
    Editor: prefixer('Editor'),

    /**
    * **[Widget](http://datashapes.org/dash#Widget)** (class)
    * 
    * Base class of user interface components that can be used to display or edit value nodes.
    */
    Widget: prefixer('Widget'),

    /**
    * **[hidden](http://datashapes.org/dash#hidden)** (property)
    * 
    * Properties marked as hidden do not appear in user interfaces, yet remain part of the shape for other purposes such as validation and scripting or GraphQL schema generation.
    */
    hidden: prefixer('hidden'),

    /**
    * **[Explore action](http://datashapes.org/dash#ExploreAction)** (class)
    * 
    * An action typically showing up in an Explore section of a selected resource. Cannot make changes to the data.
    */
    ExploreAction: prefixer('ExploreAction'),

    /**
    * **[stem](http://datashapes.org/dash#stem)** (property)
    * 
    * Specifies a string value that the IRI of the value nodes must start with.
    */
    stem: prefixer('stem'),

    /**
    * **[Resource action](http://datashapes.org/dash#ResourceAction)** (class)
    * 
    * An Action that can be executed for a selected resource. Such Actions show up in context menus once they have been assigned a sh:group.
    */
    ResourceAction: prefixer('ResourceAction'),

    /**
    * **[static constraint](http://datashapes.org/dash#staticConstraint)** (property)
    * 
    * Can be set to true for those constraint components where the validation does not require to visit any other triples than the parameters. Examples of this include sh:datatype or sh:nodeKind, where no further triples need to be queried to determine the result.
    * 
    * Constraint components that are marked as such can be optimized by engines, e.g. they can be evaluated client-side at form submission time, without having to make a round-trip to a server.
    */
    staticConstraint: prefixer('staticConstraint'),

    /**
    * **[Function test case](http://datashapes.org/dash#FunctionTestCase)** (class)
    * 
    * A test case that verifies that a given SPARQL expression produces a given, expected result.
    */
    FunctionTestCase: prefixer('FunctionTestCase'),

    /**
    * **[Graph service](http://datashapes.org/dash#GraphService)** (class)
    * 
    * A service that does not apply to a specific resource (as ResourceService does) but operates on the whole graph. The focusNode variable will be the URI of the current base graph (e.g. <urn:x-evn-master:geo> as a NamedNode.
    */
    GraphService: prefixer('GraphService'),

    /**
    * **[symmetric](http://datashapes.org/dash#symmetric)** (property)
    * 
    * True to declare that the associated property path is symmetric.
    */
    symmetric: prefixer('symmetric'),

    /**
    * **[Service](http://datashapes.org/dash#Service)** (class)
    * 
    * A script that gets exposed as a web service, e.g. /tbl/service/ex/MyService
    */
    Service: prefixer('Service'),

    /**
    * **[Graph store test case](http://datashapes.org/dash#GraphStoreTestCase)** (class)
    * 
    * A test case that can be used to verify that an RDF file could be loaded (from a file) and that the resulting RDF graph is equivalent to a given TTL file.
    */
    GraphStoreTestCase: prefixer('GraphStoreTestCase'),

    /**
    * **[action group](http://datashapes.org/dash#actionGroup)** (property)
    * 
    * Links an Action with the ActionGroup that it should be arranged in.
    */
    actionGroup: prefixer('actionGroup'),

    /**
    * **[Graph validation test case](http://datashapes.org/dash#GraphValidationTestCase)** (class)
    * 
    * A test case that performs SHACL constraint validation on the whole graph and compares the results with the expected validation results stored with the test case. By default this excludes meta-validation (i.e. the validation of the shape definitions themselves). If that's desired, set dash:validateShapes to true.
    */
    GraphValidationTestCase: prefixer('GraphValidationTestCase'),

    /**
    * **[action icon class](http://datashapes.org/dash#actionIconClass)** (property)
    * 
    * The (CSS) class of an Action for display purposes alongside the label.
    */
    actionIconClass: prefixer('actionIconClass'),

    /**
    * **[Validation test case](http://datashapes.org/dash#ValidationTestCase)** (class)
    * 
    * Abstract superclass for test cases concerning SHACL constraint validation. Future versions may add new kinds of validatin test cases, e.g. to validate a single resource only.
    */
    ValidationTestCase: prefixer('ValidationTestCase'),

    /**
    * **[added triple](http://datashapes.org/dash#addedTriple)** (property)
    * 
    * May link a dash:GraphUpdate with one or more triples (represented as instances of rdf:Statement) that should be added to fix the source of the result.
    */
    addedTriple: prefixer('addedTriple'),

    /**
    * **[Included script](http://datashapes.org/dash#IncludedScript)** (class)
    * 
    * The code associated with instances of this class will get injected into the generated APIs, as global code snippets. Typically used to declare libraries of utility functions or constants that are (compared to shape scripts) not necessarily associated with specific classes or shapes.
    * 
    * Note that the JavaScript code stored in dash:js cannot use the export keyword because the code must also work in external scripts (such as on Node.js). Instead, you need to enumerate the exported symbols via dash:exports.
    */
    IncludedScript: prefixer('IncludedScript'),

    /**
    * **[API status](http://datashapes.org/dash#apiStatus)** (property)
    * 
    * Defines how and whether the associated feature is part of an external API. APIs may be implemented as (REST) web services, via GraphQL or ADS Script APIs.
    */
    apiStatus: prefixer('apiStatus'),

    /**
    * **[Inferencing test case](http://datashapes.org/dash#InferencingTestCase)** (class)
    * 
    * A test case to verify whether an inferencing engine is producing identical results to those stored as expected results.
    */
    InferencingTestCase: prefixer('InferencingTestCase'),

    /**
    * **[applicable to class](http://datashapes.org/dash#applicableToClass)** (property)
    * 
    * Can be used to state that a shape is applicable to instances of a given class. This is a softer statement than "target class": a target means that all instances of the class must conform to the shape. Being applicable to simply means that the shape may apply to (some) instances of the class. This information can be used by algorithms or humans.
    */
    applicableToClass: prefixer('applicableToClass'),

    /**
    * **[Multi viewer](http://datashapes.org/dash#MultiViewer)** (class)
    * 
    * A viewer for multiple/all values at once.
    */
    MultiViewer: prefixer('MultiViewer'),

    /**
    * **[cachable](http://datashapes.org/dash#cachable)** (property)
    * 
    * If set to true then the results of the SHACL function can be cached in between invocations with the same arguments. In other words, they are stateless and do not depend on triples in any graph, or the current time stamp etc.
    */
    cachable: prefixer('cachable'),

    /**
    * **[Modify action](http://datashapes.org/dash#ModifyAction)** (class)
    * 
    * An action typically showing up in a Modify section of a selected resource. May make changes to the data.
    */
    ModifyAction: prefixer('ModifyAction'),

    /**
    * **[composite](http://datashapes.org/dash#composite)** (property)
    * 
    * Can be used to indicate that a property/path represented by a property constraint represents a composite relationship. In a composite relationship, the life cycle of a "child" object (value of the property/path) depends on the "parent" object (focus node). If the parent gets deleted, then the child objects should be deleted, too. Tools may use dash:composite (if set to true) to implement cascading delete operations.
    */
    composite: prefixer('composite'),

    /**
    * **[Multi editor](http://datashapes.org/dash#MultiEditor)** (class)
    * 
    * An editor for multiple/all value nodes at once.
    */
    MultiEditor: prefixer('MultiEditor'),

    /**
    * **[context-free](http://datashapes.org/dash#contextFree)** (property)
    * 
    * Used to mark certain parameterizables as context-free, meaning that the outcome of a process does not depend on the currently active query graph.
    */
    contextFree: prefixer('contextFree'),

    /**
    * **[Viewer](http://datashapes.org/dash#Viewer)** (class)
    * 
    * The class of widgets for viewing value nodes.
    */
    Viewer: prefixer('Viewer'),

    /**
    * **[default language](http://datashapes.org/dash#defaultLang)** (property)
    * 
    * Can be used to annotate a graph (usually the owl:Ontology) with the default language that tools should suggest for new literal values. For example, predominantly English graphs should have "en" as default language.
    */
    defaultLang: prefixer('defaultLang'),

    /**
    * **[Query test case](http://datashapes.org/dash#QueryTestCase)** (class)
    * 
    * A test case running a given SPARQL SELECT query and comparing its results with those stored as JSON Result Set in the expected result property.
    */
    QueryTestCase: prefixer('QueryTestCase'),

    /**
    * **[default view for role](http://datashapes.org/dash#defaultViewForRole)** (property)
    * 
    * Links a node shape with the roles for which it shall be used as default view. User interfaces can use these values to select how to present a given RDF resource. The values of this property are URIs representing a group of users or agents. There is a dedicated URI dash:all representing all users.
    */
    defaultViewForRole: prefixer('defaultViewForRole'),

    /**
    * **[Resource service](http://datashapes.org/dash#ResourceService)** (class)
    * 
    * A Service that can (and must) be applied to a given resource as focus node. Use dash:resourceService to link a class to the services that apply to its instances.
    */
    ResourceService: prefixer('ResourceService'),

    /**
    * **[deleted triple](http://datashapes.org/dash#deletedTriple)** (property)
    * 
    * May link a dash:GraphUpdate result with one or more triples (represented as instances of rdf:Statement) that should be deleted to fix the source of the result.
    */
    deletedTriple: prefixer('deletedTriple'),

    /**
    * **[Script constraint](http://datashapes.org/dash#ScriptConstraint)** (class)
    * 
    * The class of constraints that are based on Scripts. Depending on whether dash:onAllValues is set to true, these scripts can access the following pre-assigned variables:
    * 
    * - focusNode: the focus node of the constraint (a NamedNode)
    * - if dash:onAllValues is not true: value: the current value node (e.g. a JavaScript string for xsd:string literals, a number for numeric literals or true or false for xsd:boolean literals. All other literals become LiteralNodes, and non-literals become instances of NamedNode)
    * - if dash:onAllValues is true: values: an array of current value nodes, as above.
    * 
    * If the expression returns an array then each array member will be mapped to one validation result, following the mapping rules below.
    * 
    * For string results, a validation result will use the string as sh:resultMessage.
    * For boolean results, a validation result will be produced if the result is false (true means no violation).
    * 
    * For object results, a validation result will be produced using the value of the field "message" of the object as result message. If the field "value" has a value then this will become the sh:value in the violation.
    * 
    * Unless another sh:message has been directly returned, the sh:message of the dash:ScriptConstraint will be used, similar to sh:message at SPARQL Constraints. These sh:messages can access the values {$focusNode}, {$value} etc as template variables.
    */
    ScriptConstraint: prefixer('ScriptConstraint'),

    /**
    * **[dependency predicate](http://datashapes.org/dash#dependencyPredicate)** (property)
    * 
    * Can be used in dash:js node expressions to enumerate the predicates that the computation of the values may depend on. This can be used by clients to determine whether an edit requires re-computation of values on a form or elsewhere. For example, if the dash:js is something like "focusNode.firstName + focusNode.lastName" then the dependency predicates should be ex:firstName and ex:lastName.
    */
    dependencyPredicate: prefixer('dependencyPredicate'),

    /**
    * **[Script suggestion generator](http://datashapes.org/dash#ScriptSuggestionGenerator)** (class)
    * 
    * A Suggestion Generator that is backed by an Active Data Shapes script. The script needs to return a JSON object or an array of JSON objects if it shall generate multiple suggestions. It may also return null to indicate that nothing was suggested. Note that the whole script is evaluated as a (JavaScript) expression, and those will use the last value as result. So simply putting an object at the end of your script should do. Alternatively, define the bulk of the operation as a function and simply call that function in the script.
    * 
    * Each response object can have the following fields:
    * 
    * {
    * message: "The human readable message",  // Defaults to the rdfs:label(s) of the suggestion generator
    * add: [ // An array of triples to add, each triple as an array with three nodes
    * [ subject, predicate, object ],
    * [ ... ]
    * ],
    * delete: [
    * ... like add, for the triples to delete
    * ]
    * }
    * 
    * Suggestions with neither added nor deleted triples will be discarded.
    * 
    * At execution time, the script operates on the data graph as the active graph, with the following pre-bound variables:
    * - focusNode: the NamedNode that is the sh:focusNode of the validation result
    * - predicate: the NamedNode representing the predicate of the validation result, assuming sh:resultPath is a URI
    * - value: the value node from the validation result's sh:value, cast into the most suitable JS object
    * - the other pre-bound variables for the parameters of the constraint, e.g. in a sh:maxCount constraint it would be maxCount
    * 
    * The script will be executed in read-only mode, i.e. it cannot modify the graph.
    * 
    * Example with dash:js:
    * 
    * ({
    * message: `Copy labels into ${graph.localName(predicate)}`,
    * add: focusNode.values(rdfs.label).map(label =>
    * [ focusNode, predicate, label ]
    * )
    * })
    */
    ScriptSuggestionGenerator: prefixer('ScriptSuggestionGenerator'),

    /**
    * **[details endpoint](http://datashapes.org/dash#detailsEndpoint)** (property)
    * 
    * Can be used to link a SHACL property shape with the URL of a SPARQL endpoint that may contain further RDF triples for the value nodes delivered by the property. This can be used to inform a processor that it should switch to values from an external graph when the user wants to retrieve more information about a value.
    * 
    * This property should be regarded as an "annotation", i.e. it does not have any impact on validation or other built-in SHACL features. However, selected tools may want to use this information. One implementation strategy would be to periodically fetch the values specified by the sh:node or sh:class shape associated with the property, using the property shapes in that shape, and add the resulting triples into the main query graph.
    * 
    * An example value is "https://query.wikidata.org/sparql".
    */
    detailsEndpoint: prefixer('detailsEndpoint'),

    /**
    * **[Script test case](http://datashapes.org/dash#ScriptTestCase)** (class)
    * 
    * A test case that evaluates a script. Requires exactly one value for dash:js and will operate on the test case's graph (with imports) as both data and shapes graph.
    * 
    * Supports read-only scripts only at this stage.
    */
    ScriptTestCase: prefixer('ScriptTestCase'),

    /**
    * **[details graph](http://datashapes.org/dash#detailsGraph)** (property)
    * 
    * Can be used to link a SHACL property shape with a SHACL node expression that produces the URIs of one or more graphs that contain further RDF triples for the value nodes delivered by the property. This can be used to inform a processor that it should switch to another data graph when the user wants to retrieve more information about a value.
    * 
    * The node expressions are evaluated with the focus node as input. (It is unclear whether there are also cases where the result may be different for each specific value, in which case the node expression would need a second input argument).
    * 
    * This property should be regarded as an "annotation", i.e. it does not have any impact on validation or other built-in SHACL features. However, selected tools may want to use this information.
    */
    detailsGraph: prefixer('detailsGraph'),

    /**
    * **[Script validator](http://datashapes.org/dash#ScriptValidator)** (class)
    * 
    * A SHACL validator based on an Active Data Shapes script.
    * 
    * See the comment at dash:ScriptConstraint for the basic evaluation approach. Note that in addition to focusNode and value/values, the script can access pre-bound variables for each declared argument of the constraint component.
    */
    ScriptValidator: prefixer('ScriptValidator'),

    /**
    * **[expected result](http://datashapes.org/dash#expectedResult)** (property)
    * 
    * The expected result(s) of a test case. The value range of this property is different for each kind of test cases.
    */
    expectedResult: prefixer('expectedResult'),

    /**
    * **[expected result is JSON](http://datashapes.org/dash#expectedResultIsJSON)** (property)
    * 
    * A flag to indicate that the expected result represents a JSON string. If set to true, then tests would compare JSON structures (regardless of whitespaces) instead of actual syntax.
    */
    expectedResultIsJSON: prefixer('expectedResultIsJSON'),

    /**
    * **[expected result is Turtle](http://datashapes.org/dash#expectedResultIsTTL)** (property)
    * 
    * A flag to indicate that the expected result represents an RDF graph encoded as a Turtle file. If set to true, then tests would compare graphs instead of actual syntax.
    */
    expectedResultIsTTL: prefixer('expectedResultIsTTL'),

    /**
    * **[fixed](http://datashapes.org/dash#fixed)** (property)
    * 
    * Can be used to mark that certain validation results have already been fixed.
    */
    fixed: prefixer('fixed'),

    /**
    * **[height](http://datashapes.org/dash#height)** (property)
    * 
    * The height.
    */
    height: prefixer('height'),

    /**
    * **[JavaScript source code](http://datashapes.org/dash#js)** (property)
    * 
    * The JavaScript source code of a Script.
    */
    js: prefixer('js'),

    /**
    * **[mime types](http://datashapes.org/dash#mimeTypes)** (property)
    * 
    * For file-typed properties, this can be used to specify the expected/allowed mime types of its values. This can be used, for example, to limit file input boxes or file selectors. If multiple values are allowed then they need to be separated by commas.
    * 
    * Example values are listed at https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
    */
    mimeTypes: prefixer('mimeTypes'),

    /**
    * **[never materialize](http://datashapes.org/dash#neverMaterialize)** (property)
    * 
    * If set to true at a property shape then any sh:values and sh:defaultValue rules of this property will be ignored when 'all inferences' are computed. This is useful for property values that shall only be computed for individual focus nodes (e.g. when a user visits a resource) but not for large inference runs.
    */
    neverMaterialize: prefixer('neverMaterialize'),

    /**
    * **[on all values](http://datashapes.org/dash#onAllValues)** (property)
    * 
    * If set to true for a ScriptConstraint or ScriptValidator, then the associated script will receive all value nodes at once, as a value of the variable values. By default (or false), the script is called for each value node individually.
    */
    onAllValues: prefixer('onAllValues'),

    /**
    * **[property suggestion generator](http://datashapes.org/dash#propertySuggestionGenerator)** (property)
    * 
    * Links the constraint component with instances of dash:SuggestionGenerator that may be used to produce suggestions for a given validation result that was produced by a property constraint.
    */
    propertySuggestionGenerator: prefixer('propertySuggestionGenerator'),

    /**
    * **[read only](http://datashapes.org/dash#readOnly)** (property)
    * 
    * Used as a hint for user interfaces that values of the associated property should not be editable. The values of this may be the boolean literals true or false or, more generally, a SHACL node expression that must evaluate to true or false.
    */
    readOnly: prefixer('readOnly'),

    /**
    * **[resource action](http://datashapes.org/dash#resourceAction)** (property)
    * 
    * Links a class with the Resource Actions that can be applied to instances of that class.
    */
    resourceAction: prefixer('resourceAction'),

    /**
    * **[shape](http://datashapes.org/dash#shape)** (property)
    * 
    * States that a subject resource has a given shape. This property can, for example, be used to capture results of SHACL validation on static data.
    */
    shape: prefixer('shape'),

    /**
    * **[suggestion](http://datashapes.org/dash#suggestion)** (property)
    * 
    * Can be used to link a result with one or more suggestions on how to address or improve the underlying issue.
    */
    suggestion: prefixer('suggestion'),

    /**
    * **[suggestion confidence](http://datashapes.org/dash#suggestionConfidence)** (property)
    * 
    * An optional confidence between 0% and 100%. Suggestions with 100% confidence are strongly recommended. Can be used to sort recommended updates.
    */
    suggestionConfidence: prefixer('suggestionConfidence'),

    /**
    * **[suggestion generator](http://datashapes.org/dash#suggestionGenerator)** (property)
    * 
    * Links a sh:SPARQLConstraint or sh:JSConstraint with instances of dash:SuggestionGenerator that may be used to produce suggestions for a given validation result that was produced by the constraint.
    */
    suggestionGenerator: prefixer('suggestionGenerator'),

    /**
    * **[suggestion](http://datashapes.org/dash#suggestionGroup)** (property)
    * 
    * Can be used to link a suggestion with the group identifier to which it belongs. By default this is a link to the dash:SuggestionGenerator, but in principle this could be any value.
    */
    suggestionGroup: prefixer('suggestionGroup'),

    /**
    * **[validate shapes](http://datashapes.org/dash#validateShapes)** (property)
    * 
    * True to also validate the shapes itself (i.e. parameter declarations).
    */
    validateShapes: prefixer('validateShapes'),

    /**
    * **[width](http://datashapes.org/dash#width)** (property)
    * 
    * The width.
    */
    width: prefixer('width'),

    /**
    * **[x](http://datashapes.org/dash#x)** (property)
    * 
    * The x position.
    */
    'x': prefixer('x'),

    /**
    * **[y](http://datashapes.org/dash#y)** (property)
    * 
    * The y position.
    */
    'y': prefixer('y'),

  
  };

export default dash

