// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://purl.org/dc/terms/');

/**
 * [dcterms](http://purl.org/dc/terms/})
 */
const dcterms = {
  /**
    * **[Date Modified](http://purl.org/dc/terms/modified)** (property)
    * 
    * Date on which the resource was changed.
    */
    modified: prefixer('modified'),

    /**
    * **[Publisher](http://purl.org/dc/terms/publisher)** (property)
    * 
    * An entity responsible for making the resource available.
    */
    publisher: prefixer('publisher'),

    /**
    * **[Title](http://purl.org/dc/terms/title)** (property)
    * 
    * A name given to the resource.
    */
    title: prefixer('title'),

    /**
    * **[Date Issued](http://purl.org/dc/terms/issued)** (property)
    * 
    * Date of formal issuance of the resource.
    */
    issued: prefixer('issued'),

    /**
    * **[Description](http://purl.org/dc/terms/description)** (property)
    * 
    * An account of the resource.
    */
    description: prefixer('description'),

    /**
    * **[Abstract](http://purl.org/dc/terms/abstract)** (property)
    * 
    * A summary of the resource.
    */
    abstract: prefixer('abstract'),

    /**
    * **[Access Rights](http://purl.org/dc/terms/accessRights)** (property)
    * 
    * Information about who access the resource or an indication of its security status.
    */
    accessRights: prefixer('accessRights'),

    /**
    * **[Rights](http://purl.org/dc/terms/rights)** (property)
    * 
    * Information about rights held in and over the resource.
    */
    rights: prefixer('rights'),

    /**
    * **[Accrual Method](http://purl.org/dc/terms/accrualMethod)** (property)
    * 
    * The method by which items are added to a collection.
    */
    accrualMethod: prefixer('accrualMethod'),

    /**
    * **[Accrual Periodicity](http://purl.org/dc/terms/accrualPeriodicity)** (property)
    * 
    * The frequency with which items are added to a collection.
    */
    accrualPeriodicity: prefixer('accrualPeriodicity'),

    /**
    * **[Accrual Policy](http://purl.org/dc/terms/accrualPolicy)** (property)
    * 
    * The policy governing the addition of items to a collection.
    */
    accrualPolicy: prefixer('accrualPolicy'),

    /**
    * **[Alternative Title](http://purl.org/dc/terms/alternative)** (property)
    * 
    * An alternative name for the resource.
    */
    alternative: prefixer('alternative'),

    /**
    * **[Agent](http://purl.org/dc/terms/Agent)** (class)
    * 
    * A resource that acts or has the power to act.
    */
    Agent: prefixer('Agent'),

    /**
    * **[Audience](http://purl.org/dc/terms/audience)** (property)
    * 
    * A class of agents for whom the resource is intended or useful.
    */
    audience: prefixer('audience'),

    /**
    * **[Date Available](http://purl.org/dc/terms/available)** (property)
    * 
    * Date that the resource became or will become available.
    */
    available: prefixer('available'),

    /**
    * **[Agent Class](http://purl.org/dc/terms/AgentClass)** (class)
    * 
    * A group of agents.
    */
    AgentClass: prefixer('AgentClass'),

    /**
    * **[Date](http://purl.org/dc/terms/date)** (property)
    * 
    * A point or period of time associated with an event in the lifecycle of the resource.
    */
    date: prefixer('date'),

    /**
    * **[Bibliographic Resource](http://purl.org/dc/terms/BibliographicResource)** (class)
    * 
    * A book, article, or other documentary resource.
    */
    BibliographicResource: prefixer('BibliographicResource'),

    /**
    * **[Bibliographic Citation](http://purl.org/dc/terms/bibliographicCitation)** (property)
    * 
    * A bibliographic reference for the resource.
    */
    bibliographicCitation: prefixer('bibliographicCitation'),

    /**
    * **[File Format](http://purl.org/dc/terms/FileFormat)** (class)
    * 
    * A digital resource format.
    */
    FileFormat: prefixer('FileFormat'),

    /**
    * **[Identifier](http://purl.org/dc/terms/identifier)** (property)
    * 
    * An unambiguous reference to the resource within a given context.
    */
    identifier: prefixer('identifier'),

    /**
    * **[Media Type](http://purl.org/dc/terms/MediaType)** (class)
    * 
    * A file format or physical medium.
    */
    MediaType: prefixer('MediaType'),

    /**
    * **[Conforms To](http://purl.org/dc/terms/conformsTo)** (property)
    * 
    * An established standard to which the described resource conforms.
    */
    conformsTo: prefixer('conformsTo'),

    /**
    * **[Frequency](http://purl.org/dc/terms/Frequency)** (class)
    * 
    * A rate at which something recurs.
    */
    Frequency: prefixer('Frequency'),

    /**
    * **[Relation](http://purl.org/dc/terms/relation)** (property)
    * 
    * A related resource.
    */
    relation: prefixer('relation'),

    /**
    * **[Jurisdiction](http://purl.org/dc/terms/Jurisdiction)** (class)
    * 
    * The extent or range of judicial, law enforcement, or other authority.
    */
    Jurisdiction: prefixer('Jurisdiction'),

    /**
    * **[Contributor](http://purl.org/dc/terms/contributor)** (property)
    * 
    * An entity responsible for making contributions to the resource.
    */
    contributor: prefixer('contributor'),

    /**
    * **[Location, Period, or Jurisdiction](http://purl.org/dc/terms/LocationPeriodOrJurisdiction)** (class)
    * 
    * A location, period of time, or jurisdiction.
    */
    LocationPeriodOrJurisdiction: prefixer('LocationPeriodOrJurisdiction'),

    /**
    * **[Coverage](http://purl.org/dc/terms/coverage)** (property)
    * 
    * The spatial or temporal topic of the resource, spatial applicability of the resource, or jurisdiction under which the resource is relevant.
    */
    coverage: prefixer('coverage'),

    /**
    * **[License Document](http://purl.org/dc/terms/LicenseDocument)** (class)
    * 
    * A legal document giving official permission to do something with a resource.
    */
    LicenseDocument: prefixer('LicenseDocument'),

    /**
    * **[Date Created](http://purl.org/dc/terms/created)** (property)
    * 
    * Date of creation of the resource.
    */
    created: prefixer('created'),

    /**
    * **[Rights Statement](http://purl.org/dc/terms/RightsStatement)** (class)
    * 
    * A statement about the intellectual property rights (IPR) held in or over a resource, a legal document giving official permission to do something with a resource, or a statement about access rights.
    */
    RightsStatement: prefixer('RightsStatement'),

    /**
    * **[Creator](http://purl.org/dc/terms/creator)** (property)
    * 
    * An entity responsible for making the resource.
    */
    creator: prefixer('creator'),

    /**
    * **[Linguistic System](http://purl.org/dc/terms/LinguisticSystem)** (class)
    * 
    * A system of signs, symbols, sounds, gestures, or rules used in communication.
    */
    LinguisticSystem: prefixer('LinguisticSystem'),

    /**
    * **[Date Accepted](http://purl.org/dc/terms/dateAccepted)** (property)
    * 
    * Date of acceptance of the resource.
    */
    dateAccepted: prefixer('dateAccepted'),

    /**
    * **[Location](http://purl.org/dc/terms/Location)** (class)
    * 
    * A spatial region or named place.
    */
    Location: prefixer('Location'),

    /**
    * **[Date Copyrighted](http://purl.org/dc/terms/dateCopyrighted)** (property)
    * 
    * Date of copyright of the resource.
    */
    dateCopyrighted: prefixer('dateCopyrighted'),

    /**
    * **[Media Type or Extent](http://purl.org/dc/terms/MediaTypeOrExtent)** (class)
    * 
    * A media type or extent.
    */
    MediaTypeOrExtent: prefixer('MediaTypeOrExtent'),

    /**
    * **[Date Submitted](http://purl.org/dc/terms/dateSubmitted)** (property)
    * 
    * Date of submission of the resource.
    */
    dateSubmitted: prefixer('dateSubmitted'),

    /**
    * **[Method of Accrual](http://purl.org/dc/terms/MethodOfAccrual)** (class)
    * 
    * A method by which resources are added to a collection.
    */
    MethodOfAccrual: prefixer('MethodOfAccrual'),

    /**
    * **[Audience Education Level](http://purl.org/dc/terms/educationLevel)** (property)
    * 
    * A class of agents, defined in terms of progression through an educational or training context, for which the described resource is intended.
    */
    educationLevel: prefixer('educationLevel'),

    /**
    * **[Method of Instruction](http://purl.org/dc/terms/MethodOfInstruction)** (class)
    * 
    * A process that is used to engender knowledge, attitudes, and skills.
    */
    MethodOfInstruction: prefixer('MethodOfInstruction'),

    /**
    * **[Extent](http://purl.org/dc/terms/extent)** (property)
    * 
    * The size or duration of the resource.
    */
    extent: prefixer('extent'),

    /**
    * **[Period of Time](http://purl.org/dc/terms/PeriodOfTime)** (class)
    * 
    * An interval of time that is named or defined by its start and end dates.
    */
    PeriodOfTime: prefixer('PeriodOfTime'),

    /**
    * **[Format](http://purl.org/dc/terms/format)** (property)
    * 
    * The file format, physical medium, or dimensions of the resource.
    */
    format: prefixer('format'),

    /**
    * **[Physical Medium](http://purl.org/dc/terms/PhysicalMedium)** (class)
    * 
    * A physical material or carrier.
    */
    PhysicalMedium: prefixer('PhysicalMedium'),

    /**
    * **[Has Format](http://purl.org/dc/terms/hasFormat)** (property)
    * 
    * A related resource that is substantially the same as the pre-existing described resource, but in another format.
    */
    hasFormat: prefixer('hasFormat'),

    /**
    * **[Physical Resource](http://purl.org/dc/terms/PhysicalResource)** (class)
    * 
    * A material thing.
    */
    PhysicalResource: prefixer('PhysicalResource'),

    /**
    * **[Has Part](http://purl.org/dc/terms/hasPart)** (property)
    * 
    * A related resource that is included either physically or logically in the described resource.
    */
    hasPart: prefixer('hasPart'),

    /**
    * **[Policy](http://purl.org/dc/terms/Policy)** (class)
    * 
    * A plan or course of action by an authority, intended to influence and determine decisions, actions, and other matters.
    */
    Policy: prefixer('Policy'),

    /**
    * **[Has Version](http://purl.org/dc/terms/hasVersion)** (property)
    * 
    * A related resource that is a version, edition, or adaptation of the described resource.
    */
    hasVersion: prefixer('hasVersion'),

    /**
    * **[Provenance Statement](http://purl.org/dc/terms/ProvenanceStatement)** (class)
    * 
    * Any changes in ownership and custody of a resource since its creation that are significant for its authenticity, integrity, and interpretation.
    */
    ProvenanceStatement: prefixer('ProvenanceStatement'),

    /**
    * **[Instructional Method](http://purl.org/dc/terms/instructionalMethod)** (property)
    * 
    * A process, used to engender knowledge, attitudes and skills, that the described resource is designed to support.
    */
    instructionalMethod: prefixer('instructionalMethod'),

    /**
    * **[Size or Duration](http://purl.org/dc/terms/SizeOrDuration)** (class)
    * 
    * A dimension or extent, or a time taken to play or execute.
    */
    SizeOrDuration: prefixer('SizeOrDuration'),

    /**
    * **[Is Format Of](http://purl.org/dc/terms/isFormatOf)** (property)
    * 
    * A pre-existing related resource that is substantially the same as the described resource, but in another format.
    */
    isFormatOf: prefixer('isFormatOf'),

    /**
    * **[Standard](http://purl.org/dc/terms/Standard)** (class)
    * 
    * A reference point against which other things can be evaluated or compared.
    */
    Standard: prefixer('Standard'),

    /**
    * **[Is Part Of](http://purl.org/dc/terms/isPartOf)** (property)
    * 
    * A related resource in which the described resource is physically or logically included.
    */
    isPartOf: prefixer('isPartOf'),

    /**
    * **[Is Referenced By](http://purl.org/dc/terms/isReferencedBy)** (property)
    * 
    * A related resource that references, cites, or otherwise points to the described resource.
    */
    isReferencedBy: prefixer('isReferencedBy'),

    /**
    * **[Is Replaced By](http://purl.org/dc/terms/isReplacedBy)** (property)
    * 
    * A related resource that supplants, displaces, or supersedes the described resource.
    */
    isReplacedBy: prefixer('isReplacedBy'),

    /**
    * **[Is Required By](http://purl.org/dc/terms/isRequiredBy)** (property)
    * 
    * A related resource that requires the described resource to support its function, delivery, or coherence.
    */
    isRequiredBy: prefixer('isRequiredBy'),

    /**
    * **[Is Version Of](http://purl.org/dc/terms/isVersionOf)** (property)
    * 
    * A related resource of which the described resource is a version, edition, or adaptation.
    */
    isVersionOf: prefixer('isVersionOf'),

    /**
    * **[Language](http://purl.org/dc/terms/language)** (property)
    * 
    * A language of the resource.
    */
    language: prefixer('language'),

    /**
    * **[License](http://purl.org/dc/terms/license)** (property)
    * 
    * A legal document giving official permission to do something with the resource.
    */
    license: prefixer('license'),

    /**
    * **[Mediator](http://purl.org/dc/terms/mediator)** (property)
    * 
    * An entity that mediates access to the resource.
    */
    mediator: prefixer('mediator'),

    /**
    * **[Medium](http://purl.org/dc/terms/medium)** (property)
    * 
    * The material or physical carrier of the resource.
    */
    medium: prefixer('medium'),

    /**
    * **[Provenance](http://purl.org/dc/terms/provenance)** (property)
    * 
    * A statement of any changes in ownership and custody of the resource since its creation that are significant for its authenticity, integrity, and interpretation.
    */
    provenance: prefixer('provenance'),

    /**
    * **[References](http://purl.org/dc/terms/references)** (property)
    * 
    * A related resource that is referenced, cited, or otherwise pointed to by the described resource.
    */
    references: prefixer('references'),

    /**
    * **[Replaces](http://purl.org/dc/terms/replaces)** (property)
    * 
    * A related resource that is supplanted, displaced, or superseded by the described resource.
    */
    replaces: prefixer('replaces'),

    /**
    * **[Requires](http://purl.org/dc/terms/requires)** (property)
    * 
    * A related resource that is required by the described resource to support its function, delivery, or coherence.
    */
    requires: prefixer('requires'),

    /**
    * **[Rights Holder](http://purl.org/dc/terms/rightsHolder)** (property)
    * 
    * A person or organization owning or managing rights over the resource.
    */
    rightsHolder: prefixer('rightsHolder'),

    /**
    * **[Source](http://purl.org/dc/terms/source)** (property)
    * 
    * A related resource from which the described resource is derived.
    */
    source: prefixer('source'),

    /**
    * **[Spatial Coverage](http://purl.org/dc/terms/spatial)** (property)
    * 
    * Spatial characteristics of the resource.
    */
    spatial: prefixer('spatial'),

    /**
    * **[Subject](http://purl.org/dc/terms/subject)** (property)
    * 
    * A topic of the resource.
    */
    subject: prefixer('subject'),

    /**
    * **[Table Of Contents](http://purl.org/dc/terms/tableOfContents)** (property)
    * 
    * A list of subunits of the resource.
    */
    tableOfContents: prefixer('tableOfContents'),

    /**
    * **[Temporal Coverage](http://purl.org/dc/terms/temporal)** (property)
    * 
    * Temporal characteristics of the resource.
    */
    temporal: prefixer('temporal'),

    /**
    * **[Type](http://purl.org/dc/terms/type)** (property)
    * 
    * The nature or genre of the resource.
    */
    type: prefixer('type'),

    /**
    * **[Date Valid](http://purl.org/dc/terms/valid)** (property)
    * 
    * Date (often a range) of validity of a resource.
    */
    valid: prefixer('valid'),

  
  };

export default dcterms

