// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.w3.org/ns/dqv#');

/**
 * [dqv](http://www.w3.org/ns/dqv#})
 */
const dqv = {
  /**
    * **[Category](http://www.w3.org/ns/dqv#Category)** (class)
    * 
    * Represents a group of quality dimensions in which a common type of information is used as quality indicator.
    */
    Category: prefixer('Category'),

    /**
    * **[Dimension](http://www.w3.org/ns/dqv#Dimension)** (class)
    * 
    * Represents criteria relevant for assessing quality. Each quality dimension must have one or more metric to measure it. A dimension is linked with a category using the dqv:inCategory property.
    */
    Dimension: prefixer('Dimension'),

    /**
    * **[Metric](http://www.w3.org/ns/dqv#Metric)** (class)
    * 
    * Represents a standard to measure a quality dimension. An observation (instance of dqv:QualityMeasurement) assigns a value in a given unit to a Metric.
    */
    Metric: prefixer('Metric'),

    /**
    * **[Quality Annotation](http://www.w3.org/ns/dqv#QualityAnnotation)** (class)
    * 
    * Represents quality annotations, including ratings, quality certificates or feedback that can be associated to datasets or distributions. Quality annotations must have one oa:motivatedBy statement with an instance of oa:Motivation (and skos:Concept) that reflects a quality assessment purpose. We define this instance as dqv:qualityAssessment.
    */
    QualityAnnotation: prefixer('QualityAnnotation'),

    /**
    * **[Quality Certificate](http://www.w3.org/ns/dqv#QualityCertificate)** (class)
    * 
    * An annotation that associates a resource (especially, a dataset or a distribution) to another resource (for example, a document) that certifies the resource's quality according to a set of quality assessment rules.
    */
    QualityCertificate: prefixer('QualityCertificate'),

    /**
    * **[Quality Measurement](http://www.w3.org/ns/dqv#QualityMeasurement)** (class)
    * 
    * Represents the evaluation of a given dataset (or dataset distribution) against a specific quality metric.
    */
    QualityMeasurement: prefixer('QualityMeasurement'),

    /**
    * **[Quality Measurement Dataset](http://www.w3.org/ns/dqv#QualityMeasurementDataset)** (class)
    * 
    * Represents a dataset of quality measurements, evaluations of one or more datasets (or dataset distributions) against specific quality metrics.
    */
    QualityMeasurementDataset: prefixer('QualityMeasurementDataset'),

    /**
    * **[Quality Metadata](http://www.w3.org/ns/dqv#QualityMetadata)** (class)
    * 
    * Represents quality metadata, it is defined to group quality certificates, policies, measurements and annotations under a named graph.
    */
    QualityMetadata: prefixer('QualityMetadata'),

    /**
    * **[Quality Policy](http://www.w3.org/ns/dqv#QualityPolicy)** (class)
    * 
    * Represents a policy or agreement that is chiefly governed by data quality concerns.
    */
    QualityPolicy: prefixer('QualityPolicy'),

    /**
    * **[User Quality feedback](http://www.w3.org/ns/dqv#UserQualityFeedback)** (class)
    * 
    * Represents feedback that users have on the quality of datasets or distributions. Besides dqv:qualityAssessment, which is the motivation required by all quality annotations, one of the predefined instances of oa:Motivation should be indicated as motivation to distinguish among the different kinds of feedback, e.g., classifications, questions.
    */
    UserQualityFeedback: prefixer('UserQualityFeedback'),

    /**
    * **[computed on](http://www.w3.org/ns/dqv#computedOn)** (property)
    * 
    * Refers to the resource (e.g., a dataset, a linkset, a graph, a set of triples) on which the quality measurement is performed. In the DQV context, this property is generally expected to be used in statements in which objects are instances of dcat:Dataset or dcat:Distribution.
    */
    computedOn: prefixer('computedOn'),

    /**
    * **[has quality measurement](http://www.w3.org/ns/dqv#hasQualityMeasurement)** (property)
    * 
    * Refers to the performed quality measurements. Quality measurements can be performed to any kind of resource (e.g., a dataset, a linkset, a graph, a set of triples). However, in the DQV context, this property is generally expected to be used in statements in which subjects are instances of dcat:Dataset or dcat:Distribution.
    */
    hasQualityMeasurement: prefixer('hasQualityMeasurement'),

    /**
    * **[expected data type](http://www.w3.org/ns/dqv#expectedDataType)** (property)
    * 
    * Represents the expected data type for metric's observed value (e.g. xsd:boolean, xsd:double etc...)
    */
    expectedDataType: prefixer('expectedDataType'),

    /**
    * **[has quality annotation](http://www.w3.org/ns/dqv#hasQualityAnnotation)** (property)
    * 
    * Refers to a quality annotation. Quality annotation can be applied to any kind of resource, e.g., a dataset, a linkset, a graph, a set of triples. However, in the DQV context, this property is generally expected to be used in statements in which subjects are instances of dcat:Dataset or dcat:Distribution.
    */
    hasQualityAnnotation: prefixer('hasQualityAnnotation'),

    /**
    * **[has quality metadata](http://www.w3.org/ns/dqv#hasQualityMetadata)** (property)
    * 
    * Refers to a grouping of quality information such as certificates, policies, measurements and annotations as a named graph. Quality information represented in such a grouping can pertain to any kind of resource (e.g., a dataset, a linkset, a graph, a set of triples). However, in the DQV context, this property is generally expected to be used in statements in which subjects are instances of dcat:Dataset or dcat:Distribution.
    */
    hasQualityMetadata: prefixer('hasQualityMetadata'),

    /**
    * **[in category](http://www.w3.org/ns/dqv#inCategory)** (property)
    * 
    * Represents the category a dimension is grouped in.
    */
    inCategory: prefixer('inCategory'),

    /**
    * **[in dimension](http://www.w3.org/ns/dqv#inDimension)** (property)
    * 
    * Represents the dimensions a quality metric, certificate and annotation allow a measurement of.
    */
    inDimension: prefixer('inDimension'),

    /**
    * **[is measurement of](http://www.w3.org/ns/dqv#isMeasurementOf)** (property)
    * 
    * Indicates the metric being observed.
    */
    isMeasurementOf: prefixer('isMeasurementOf'),

    /**
    * **[value](http://www.w3.org/ns/dqv#value)** (property)
    * 
    * Refers to values computed by metric.
    */
    value: prefixer('value'),

  
  };

export default dqv

