// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.w3.org/ns/duv#');

/**
 * [duv](http://www.w3.org/ns/duv#})
 */
const duv = {
  /**
    * **[Rating Feedback](http://www.w3.org/ns/duv#RatingFeedback)** (class)
    * 
    * Predefined criteria used to express a user opinion about a dataset or distribution using a discrete range of values.
    */
    RatingFeedback: prefixer('RatingFeedback'),

    /**
    * **[User Feedback](http://www.w3.org/ns/duv#UserFeedback)** (class)
    * 
    * User feedback on the dataset. Expresses whether the dataset was useful or not, for example.
    */
    UserFeedback: prefixer('UserFeedback'),

    /**
    * **[Usage](http://www.w3.org/ns/duv#Usage)** (class)
    * 
    * A helpful description of actions that can be performed on a given dataset or distribution.
    */
    Usage: prefixer('Usage'),

    /**
    * **[UsageTool](http://www.w3.org/ns/duv#UsageTool)** (class)
    * 
    * A synopsis describing the way a tool can use a dataset or distribution.
    */
    UsageTool: prefixer('UsageTool'),

    /**
    * **[has distributor](http://www.w3.org/ns/duv#hasDistributor)** (property)
    * 
    * The distributor is the organization that makes the dataset available for downloading and use.
    */
    hasDistributor: prefixer('hasDistributor'),

    /**
    * **[has dataset feedback](http://www.w3.org/ns/duv#hasFeedback)** (property)
    * 
    * User feedback associated with Dataset or distribution
    */
    hasFeedback: prefixer('hasFeedback'),

    /**
    * **[has rating](http://www.w3.org/ns/duv#hasRating)** (property)
    * 
    * Rating Feedback has rating opinion
    */
    hasRating: prefixer('hasRating'),

    /**
    * **[has dataset/distribution usage](http://www.w3.org/ns/duv#hasUsage)** (property)
    * 
    * Dataset/distribution usage guidance or instructions.
    */
    hasUsage: prefixer('hasUsage'),

    /**
    * **[has usage tool](http://www.w3.org/ns/duv#hasUsageTool)** (property)
    * 
    * Describes the tool that provides the Usage
    */
    hasUsageTool: prefixer('hasUsageTool'),

    /**
    * **[refers to dataset](http://www.w3.org/ns/duv#refersTo)** (property)
    * 
    * Dataset associated with Usage.
    */
    refersTo: prefixer('refersTo'),

  
  };

export default duv

