// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.w3.org/2003/12/exif/ns#');

/**
 * [exif](http://www.w3.org/2003/12/exif/ns#})
 */
const exif = {
  /**
    * **[IFD](http://www.w3.org/2003/12/exif/ns#IFD)** (class)
    * 
    * An Image File Directory
    */
    IFD: prefixer('IFD'),

    /**
    * **[Unknown tag](http://www.w3.org/2003/12/exif/ns#_unknown)** (property)
    * 
    * An Exif tag whose meaning is not known
    */
    '_unknown': prefixer('_unknown'),

    /**
    * **[ApertureValue](http://www.w3.org/2003/12/exif/ns#apertureValue)** (property)
    * 
    * The lens aperture. The unit is the APEX value.
    */
    apertureValue: prefixer('apertureValue'),

    /**
    * **[PictTaking](http://www.w3.org/2003/12/exif/ns#pictTaking)** (property)
    * 
    * An attribute relating to Picture-Taking Conditions
    */
    pictTaking: prefixer('pictTaking'),

    /**
    * **[Artist](http://www.w3.org/2003/12/exif/ns#artist)** (property)
    * 
    * Person who created the image
    */
    artist: prefixer('artist'),

    /**
    * **[Exif Attribute](http://www.w3.org/2003/12/exif/ns#exifAttribute)** (property)
    * 
    * A property that connects an IFD to one of its entries. Super property which integrates all Exif tags.
    */
    exifAttribute: prefixer('exifAttribute'),

    /**
    * **[BitsPerSample](http://www.w3.org/2003/12/exif/ns#bitsPerSample)** (property)
    * 
    * The number of bits per image component. In this standard each component of the image is 8 bits, so the value for this tag is 8. See also SamplesPerPixel. In JPEG compressed data a JPEG marker is used instead of this tag.
    */
    bitsPerSample: prefixer('bitsPerSample'),

    /**
    * **[Image Data Structure](http://www.w3.org/2003/12/exif/ns#imageDataStruct)** (property)
    * 
    * An attribute relating to image data structure
    */
    imageDataStruct: prefixer('imageDataStruct'),

    /**
    * **[Resolution](http://www.w3.org/2003/12/exif/ns#resolution)** (property)
    * 
    * a rational number representing a resolution. Could be a subProperty of other general schema.
    */
    resolution: prefixer('resolution'),

    /**
    * **[BrightnessValue](http://www.w3.org/2003/12/exif/ns#brightnessValue)** (property)
    * 
    * The value of brightness. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99. Note that if the numerator of the recorded value is FFFFFFFF.H, Unknown shall be indicated.
    */
    brightnessValue: prefixer('brightnessValue'),

    /**
    * **[CFAPattern](http://www.w3.org/2003/12/exif/ns#cfaPattern)** (property)
    * 
    * The color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used. It does not apply to all sensing methods.
    */
    cfaPattern: prefixer('cfaPattern'),

    /**
    * **[ColorSpace](http://www.w3.org/2003/12/exif/ns#colorSpace)** (property)
    * 
    * The color space information tag (ColorSpace) is always recorded as the color space specifier. Normally sRGB (=1) is used to define the color space based on the PC monitor conditions and environment.
    */
    colorSpace: prefixer('colorSpace'),

    /**
    * **[Image Data Character](http://www.w3.org/2003/12/exif/ns#imageDataCharacter)** (property)
    * 
    * An attribute relating to image data characteristics
    */
    imageDataCharacter: prefixer('imageDataCharacter'),

    /**
    * **[ComponentsConfiguration](http://www.w3.org/2003/12/exif/ns#componentsConfiguration)** (property)
    * 
    * Information specific to compressed data. The channels of each component are arranged in order from the 1st component to the 4th. For uncompressed data the data arrangement is given in the PhotometricInterpretation tag. However, since PhotometricInterpretation can only express the order of Y,Cb and Cr, this tag is provided for cases when compressed data uses components other than Y, Cb, and Cr and to enable support of other sequences.
    */
    componentsConfiguration: prefixer('componentsConfiguration'),

    /**
    * **[Image Config](http://www.w3.org/2003/12/exif/ns#imageConfig)** (property)
    * 
    * An attribute relating to Image Configuration
    */
    imageConfig: prefixer('imageConfig'),

    /**
    * **[CompressedBitsPerPixel](http://www.w3.org/2003/12/exif/ns#compressedBitsPerPixel)** (property)
    * 
    * Information specific to compressed data. The compression mode used for a compressed image is indicated in unit bits per pixel.
    */
    compressedBitsPerPixel: prefixer('compressedBitsPerPixel'),

    /**
    * **[Compression](http://www.w3.org/2003/12/exif/ns#compression)** (property)
    * 
    * The compression scheme used for the image data. When a primary image is JPEG compressed, this designation is not necessary and is omitted. When thumbnails use JPEG compression, this tag value is set to 6.
    */
    compression: prefixer('compression'),

    /**
    * **[Contrast](http://www.w3.org/2003/12/exif/ns#contrast)** (property)
    * 
    * The direction of contrast processing applied by the camera when the image was shot.
    */
    contrast: prefixer('contrast'),

    /**
    * **[Copyright](http://www.w3.org/2003/12/exif/ns#copyright)** (property)
    * 
    * Copyright information. In this standard the tag is used to indicate both the photographer and editor copyrights. It is the copyright notice of the person or organization claiming rights to the image.
    */
    copyright: prefixer('copyright'),

    /**
    * **[CustomRendered](http://www.w3.org/2003/12/exif/ns#customRendered)** (property)
    * 
    * The use of special processing on image data, such as rendering geared to output. When special processing is performed, the reader is expected to disable or minimize any further processing.
    */
    customRendered: prefixer('customRendered'),

    /**
    * **[Data Type](http://www.w3.org/2003/12/exif/ns#datatype)** (property)
    * 
    * The Exif field data type, such as ascii, byte, short etc.
    */
    datatype: prefixer('datatype'),

    /**
    * **[Date](http://www.w3.org/2003/12/exif/ns#date)** (property)
    * 
    * a date information. Usually saved as YYYY:MM:DD (HH:MM:SS) format in Exif data, but represented here as W3C-DTF format
    */
    date: prefixer('date'),

    /**
    * **[Date and/or Time](http://www.w3.org/2003/12/exif/ns#dateAndOrTime)** (property)
    * 
    * An attribute relating to Date and/or Time
    */
    dateAndOrTime: prefixer('dateAndOrTime'),

    /**
    * **[DateTime](http://www.w3.org/2003/12/exif/ns#dateTime)** (property)
    * 
    * The date and time of image creation. In this standard it is the date and time the file was changed.
    */
    dateTime: prefixer('dateTime'),

    /**
    * **[DateTimeDigitized](http://www.w3.org/2003/12/exif/ns#dateTimeDigitized)** (property)
    * 
    * The date and time when the image was stored as digital data. If, for example, an image was captured by DSC and at the same time the file was recorded, then the DateTimeOriginal and DateTimeDigitized will have the same contents.
    */
    dateTimeDigitized: prefixer('dateTimeDigitized'),

    /**
    * **[DateTimeOriginal](http://www.w3.org/2003/12/exif/ns#dateTimeOriginal)** (property)
    * 
    * The date and time when the original image data was generated. For a DSC the date and time the picture was taken are recorded.
    */
    dateTimeOriginal: prefixer('dateTimeOriginal'),

    /**
    * **[DeviceSettingDescription](http://www.w3.org/2003/12/exif/ns#deviceSettingDescription)** (property)
    * 
    * Information on the picture-taking conditions of a particular camera model. The tag is used only to indicate the picture-taking conditions in the reader.
    */
    deviceSettingDescription: prefixer('deviceSettingDescription'),

    /**
    * **[DigitalZoomRatio](http://www.w3.org/2003/12/exif/ns#digitalZoomRatio)** (property)
    * 
    * The digital zoom ratio when the image was shot. If the numerator of the recorded value is 0, this indicates that digital zoom was not used.
    */
    digitalZoomRatio: prefixer('digitalZoomRatio'),

    /**
    * **[ExifVersion](http://www.w3.org/2003/12/exif/ns#exifVersion)** (property)
    * 
    * Exif Version
    */
    exifVersion: prefixer('exifVersion'),

    /**
    * **[Version Info](http://www.w3.org/2003/12/exif/ns#versionInfo)** (property)
    * 
    * An attribute relating to Version
    */
    versionInfo: prefixer('versionInfo'),

    /**
    * **[Exif IFD Pointer](http://www.w3.org/2003/12/exif/ns#exif_IFD_Pointer)** (property)
    * 
    * A pointer to the Exif IFD, which is a set of tags for recording Exif-specific attribute information.
    */
    exif_IFD_Pointer: prefixer('exif_IFD_Pointer'),

    /**
    * **[IFD Pointer](http://www.w3.org/2003/12/exif/ns#ifdPointer)** (property)
    * 
    * A tag that refers a child IFD
    */
    ifdPointer: prefixer('ifdPointer'),

    /**
    * **[Exif data](http://www.w3.org/2003/12/exif/ns#exifdata)** (property)
    * 
    * An Exif IFD data entry
    */
    exifdata: prefixer('exifdata'),

    /**
    * **[ExposureBiasValue](http://www.w3.org/2003/12/exif/ns#exposureBiasValue)** (property)
    * 
    * The exposure bias. The unit is the APEX value. Ordinarily it is given in the range of -99.99 to 99.99.
    */
    exposureBiasValue: prefixer('exposureBiasValue'),

    /**
    * **[ExposureIndex](http://www.w3.org/2003/12/exif/ns#exposureIndex)** (property)
    * 
    * The exposure index selected on the camera or input device at the time the image is captured.
    */
    exposureIndex: prefixer('exposureIndex'),

    /**
    * **[ExposureMode](http://www.w3.org/2003/12/exif/ns#exposureMode)** (property)
    * 
    * the exposure mode set when the image was shot. In auto-bracketing mode, the camera shoots a series of frames of the same scene at different exposure settings.
    */
    exposureMode: prefixer('exposureMode'),

    /**
    * **[ExposureProgram](http://www.w3.org/2003/12/exif/ns#exposureProgram)** (property)
    * 
    * The class of the program used by the camera to set exposure when the picture is taken.
    */
    exposureProgram: prefixer('exposureProgram'),

    /**
    * **[ExposureTime](http://www.w3.org/2003/12/exif/ns#exposureTime)** (property)
    * 
    * Exposure time, given in seconds (sec).
    */
    exposureTime: prefixer('exposureTime'),

    /**
    * **[Seconds](http://www.w3.org/2003/12/exif/ns#seconds)** (property)
    * 
    * a mesurement of time length with unit of second
    */
    seconds: prefixer('seconds'),

    /**
    * **[FNumber](http://www.w3.org/2003/12/exif/ns#fNumber)** (property)
    * 
    * F number
    */
    fNumber: prefixer('fNumber'),

    /**
    * **[FileSource](http://www.w3.org/2003/12/exif/ns#fileSource)** (property)
    * 
    * The image source. If a DSC recorded the image, this tag value of this tag always be set to 3, indicating that the image was recorded on a DSC.
    */
    fileSource: prefixer('fileSource'),

    /**
    * **[Flash](http://www.w3.org/2003/12/exif/ns#flash)** (property)
    * 
    * The status of flash when the image was shot.
    */
    flash: prefixer('flash'),

    /**
    * **[FlashEnergy](http://www.w3.org/2003/12/exif/ns#flashEnergy)** (property)
    * 
    * The strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds (BCPS).
    */
    flashEnergy: prefixer('flashEnergy'),

    /**
    * **[FlashpixVersion](http://www.w3.org/2003/12/exif/ns#flashpixVersion)** (property)
    * 
    * The Flashpix format version supported by a FPXR file. If the FPXR function supports Flashpix format Ver. 1.0, this is indicated similarly to ExifVersion by recording "0100" as 4-byte ASCII.
    */
    flashpixVersion: prefixer('flashpixVersion'),

    /**
    * **[FocalLength](http://www.w3.org/2003/12/exif/ns#focalLength)** (property)
    * 
    * The actual focal length of the lens, in mm. Conversion is not made to the focal length of a 35 mm film camera.
    */
    focalLength: prefixer('focalLength'),

    /**
    * **[Milimeter](http://www.w3.org/2003/12/exif/ns#mm)** (property)
    * 
    * A length with unit of mm
    */
    mm: prefixer('mm'),

    /**
    * **[FocalLengthIn35mmFilm](http://www.w3.org/2003/12/exif/ns#focalLengthIn35mmFilm)** (property)
    * 
    * The equivalent focal length assuming a 35mm film camera, in mm. A value of 0 means the focal length is unknown. Note that this tag differs from the FocalLength tag.
    */
    focalLengthIn35mmFilm: prefixer('focalLengthIn35mmFilm'),

    /**
    * **[Length](http://www.w3.org/2003/12/exif/ns#length)** (property)
    * 
    * Length of an object. Could be a subProperty of other general schema.
    */
    length: prefixer('length'),

    /**
    * **[FocalPlaneResolutionUnit](http://www.w3.org/2003/12/exif/ns#focalPlaneResolutionUnit)** (property)
    * 
    * The unit for measuring FocalPlaneXResolution and FocalPlaneYResolution. This value is the same as the ResolutionUnit.
    */
    focalPlaneResolutionUnit: prefixer('focalPlaneResolutionUnit'),

    /**
    * **[FocalPlaneXResolution](http://www.w3.org/2003/12/exif/ns#focalPlaneXResolution)** (property)
    * 
    * The number of pixels in the image width (X) direction per FocalPlaneResolutionUnit on the camera focal plane.
    */
    focalPlaneXResolution: prefixer('focalPlaneXResolution'),

    /**
    * **[FocalPlaneYResolution](http://www.w3.org/2003/12/exif/ns#focalPlaneYResolution)** (property)
    * 
    * The number of pixels in the image height (Y) direction per FocalPlaneResolutionUnit on the camera focal plane.
    */
    focalPlaneYResolution: prefixer('focalPlaneYResolution'),

    /**
    * **[GainControl](http://www.w3.org/2003/12/exif/ns#gainControl)** (property)
    * 
    * The degree of overall image gain adjustment.
    */
    gainControl: prefixer('gainControl'),

    /**
    * **[Geometric data](http://www.w3.org/2003/12/exif/ns#geo)** (property)
    * 
    * Geometric data such as latitude, longitude and altitude. Usually saved as rational number.
    */
    geo: prefixer('geo'),

    /**
    * **[GPSAltitude](http://www.w3.org/2003/12/exif/ns#gpsAltitude)** (property)
    * 
    * The altitude based on the reference in GPSAltitudeRef. Altitude is expressed as one RATIONAL value. The reference unit is meters.
    */
    gpsAltitude: prefixer('gpsAltitude'),

    /**
    * **[GPS Info](http://www.w3.org/2003/12/exif/ns#gpsInfo)** (property)
    * 
    * An attribute relating to GPS information
    */
    gpsInfo: prefixer('gpsInfo'),

    /**
    * **[GPSAltitudeRef](http://www.w3.org/2003/12/exif/ns#gpsAltitudeRef)** (property)
    * 
    * Indicates the altitude used as the reference altitude. If the reference is sea level and the altitude is above sea level, 0 is given. If the altitude is below sea level, a value of 1 is given and the altitude is indicated as an absolute value in the GPSAltitude tag. The reference unit is meters.
    */
    gpsAltitudeRef: prefixer('gpsAltitudeRef'),

    /**
    * **[GPSAreaInformation](http://www.w3.org/2003/12/exif/ns#gpsAreaInformation)** (property)
    * 
    * A character string recording the name of the GPS area. The first byte indicates the character code used, and this is followed by the name of the GPS area.
    */
    gpsAreaInformation: prefixer('gpsAreaInformation'),

    /**
    * **[GPSDOP](http://www.w3.org/2003/12/exif/ns#gpsDOP)** (property)
    * 
    * The GPS DOP (data degree of precision). An HDOP value is written during two-dimensional measurement, and PDOP during three-dimensional measurement.
    */
    gpsDOP: prefixer('gpsDOP'),

    /**
    * **[GPSDateStamp](http://www.w3.org/2003/12/exif/ns#gpsDateStamp)** (property)
    * 
    * date and time information relative to UTC (Coordinated Universal Time). The record format is "YYYY:MM:DD" while converted to W3C-DTF to use in RDF
    */
    gpsDateStamp: prefixer('gpsDateStamp'),

    /**
    * **[GPSDestBearing](http://www.w3.org/2003/12/exif/ns#gpsDestBearing)** (property)
    * 
    * The bearing to the destination point. The range of values is from 0.00 to 359.99.
    */
    gpsDestBearing: prefixer('gpsDestBearing'),

    /**
    * **[GPSDestBearingRef](http://www.w3.org/2003/12/exif/ns#gpsDestBearingRef)** (property)
    * 
    * Indicates the reference used for giving the bearing to the destination point. 'T' denotes true direction and 'M' is magnetic direction.
    */
    gpsDestBearingRef: prefixer('gpsDestBearingRef'),

    /**
    * **[GPSDestDistance](http://www.w3.org/2003/12/exif/ns#gpsDestDistance)** (property)
    * 
    * The distance to the destination point.
    */
    gpsDestDistance: prefixer('gpsDestDistance'),

    /**
    * **[GPSDestDistanceRef](http://www.w3.org/2003/12/exif/ns#gpsDestDistanceRef)** (property)
    * 
    * Indicates the unit used to express the distance to the destination point. 'K', 'M' and 'N' represent kilometers, miles and knots.
    */
    gpsDestDistanceRef: prefixer('gpsDestDistanceRef'),

    /**
    * **[GPSDestLatitude](http://www.w3.org/2003/12/exif/ns#gpsDestLatitude)** (property)
    * 
    * Latitude of destination, expressed as three values giving the degrees, minutes, and seconds, respectively.
    */
    gpsDestLatitude: prefixer('gpsDestLatitude'),

    /**
    * **[GPSDestLatitudeRef](http://www.w3.org/2003/12/exif/ns#gpsDestLatitudeRef)** (property)
    * 
    * Reference for latitude of destination
    */
    gpsDestLatitudeRef: prefixer('gpsDestLatitudeRef'),

    /**
    * **[GPSDestLongitude](http://www.w3.org/2003/12/exif/ns#gpsDestLongitude)** (property)
    * 
    * Longitude of destination, expressed as three values giving the degrees, minutes, and seconds, respectively.
    */
    gpsDestLongitude: prefixer('gpsDestLongitude'),

    /**
    * **[GPSDestLongitudeRef](http://www.w3.org/2003/12/exif/ns#gpsDestLongitudeRef)** (property)
    * 
    * Reference for longitude of destination
    */
    gpsDestLongitudeRef: prefixer('gpsDestLongitudeRef'),

    /**
    * **[GPSDifferential](http://www.w3.org/2003/12/exif/ns#gpsDifferential)** (property)
    * 
    * Indicates whether differential correction is applied to the GPS receiver.
    */
    gpsDifferential: prefixer('gpsDifferential'),

    /**
    * **[GPSImgDirection](http://www.w3.org/2003/12/exif/ns#gpsImgDirection)** (property)
    * 
    * The direction of the image when it was captured. The range of values is from 0.00 to 359.99.
    */
    gpsImgDirection: prefixer('gpsImgDirection'),

    /**
    * **[GPSImgDirectionRef](http://www.w3.org/2003/12/exif/ns#gpsImgDirectionRef)** (property)
    * 
    * The reference for giving the direction of the image when it is captured. 'T' denotes true direction and 'M' is magnetic direction.
    */
    gpsImgDirectionRef: prefixer('gpsImgDirectionRef'),

    /**
    * **[GPSInfo IFD Pointer](http://www.w3.org/2003/12/exif/ns#gpsInfo_IFD_Pointer)** (property)
    * 
    * A pointer to the GPS IFD, which is a set of tags for recording GPS information.
    */
    gpsInfo_IFD_Pointer: prefixer('gpsInfo_IFD_Pointer'),

    /**
    * **[GPSLatitude](http://www.w3.org/2003/12/exif/ns#gpsLatitude)** (property)
    * 
    * The latitude, expressed as three values giving the degrees, minutes, and seconds, respectively.
    */
    gpsLatitude: prefixer('gpsLatitude'),

    /**
    * **[GPSLatitudeRef](http://www.w3.org/2003/12/exif/ns#gpsLatitudeRef)** (property)
    * 
    * Indicates whether the latitude is north or south latitude. The ASCII value 'N' indicates north latitude, and 'S' is south latitude.
    */
    gpsLatitudeRef: prefixer('gpsLatitudeRef'),

    /**
    * **[GPSLongitude](http://www.w3.org/2003/12/exif/ns#gpsLongitude)** (property)
    * 
    * The longitude, expressed as three values giving the degrees, minutes, and seconds, respectively.
    */
    gpsLongitude: prefixer('gpsLongitude'),

    /**
    * **[GPSLongitudeRef](http://www.w3.org/2003/12/exif/ns#gpsLongitudeRef)** (property)
    * 
    * Indicates whether the longitude is east or west longitude. ASCII 'E' indicates east longitude, and 'W' is west longitude.
    */
    gpsLongitudeRef: prefixer('gpsLongitudeRef'),

    /**
    * **[GPSMapDatum](http://www.w3.org/2003/12/exif/ns#gpsMapDatum)** (property)
    * 
    * The geodetic survey data used by the GPS receiver. If the survey data is restricted to Japan, the value of this tag is 'TOKYO' or 'WGS-84'. If a GPS Info tag is recorded, it is strongly recommended that this tag be recorded.
    */
    gpsMapDatum: prefixer('gpsMapDatum'),

    /**
    * **[GPSMeasureMode](http://www.w3.org/2003/12/exif/ns#gpsMeasureMode)** (property)
    * 
    * The GPS measurement mode. '2' means two-dimensional measurement and '3' means three-dimensional measurement is in progress.
    */
    gpsMeasureMode: prefixer('gpsMeasureMode'),

    /**
    * **[GPSProcessingMethod](http://www.w3.org/2003/12/exif/ns#gpsProcessingMethod)** (property)
    * 
    * A character string recording the name of the method used for location finding. The first byte indicates the character code used, and this is followed by the name of the method.
    */
    gpsProcessingMethod: prefixer('gpsProcessingMethod'),

    /**
    * **[GPSSatellites](http://www.w3.org/2003/12/exif/ns#gpsSatellites)** (property)
    * 
    * The GPS satellites used for measurements. This tag can be used to describe the number of satellites, their ID number, angle of elevation, azimuth, SNR and other information in ASCII notation. The format is not specified. If the GPS receiver is incapable of taking measurements, value of the tag shall be set to NULL.
    */
    gpsSatellites: prefixer('gpsSatellites'),

    /**
    * **[GPSSpeed](http://www.w3.org/2003/12/exif/ns#gpsSpeed)** (property)
    * 
    * The speed of GPS receiver movement.
    */
    gpsSpeed: prefixer('gpsSpeed'),

    /**
    * **[GPSSpeedRef](http://www.w3.org/2003/12/exif/ns#gpsSpeedRef)** (property)
    * 
    * The unit used to express the GPS receiver speed of movement. 'K' 'M' and 'N' represents kilometers per hour, miles per hour, and knots.
    */
    gpsSpeedRef: prefixer('gpsSpeedRef'),

    /**
    * **[GPSStatus](http://www.w3.org/2003/12/exif/ns#gpsStatus)** (property)
    * 
    * The status of the GPS receiver when the image is recorded. 'A' means measurement is in progress, and 'V' means the measurement is Interoperability.
    */
    gpsStatus: prefixer('gpsStatus'),

    /**
    * **[GPSTimeStamp](http://www.w3.org/2003/12/exif/ns#gpsTimeStamp)** (property)
    * 
    * The time as UTC (Coordinated Universal Time). TimeStamp is expressed as three RATIONAL values giving the hour, minute, and second.
    */
    gpsTimeStamp: prefixer('gpsTimeStamp'),

    /**
    * **[GPSTrack](http://www.w3.org/2003/12/exif/ns#gpsTrack)** (property)
    * 
    * The direction of GPS receiver movement. The range of values is from 0.00 to 359.99.
    */
    gpsTrack: prefixer('gpsTrack'),

    /**
    * **[GPSTrackRef](http://www.w3.org/2003/12/exif/ns#gpsTrackRef)** (property)
    * 
    * The reference for giving the direction of GPS receiver movement. 'T' denotes true direction and 'M' is magnetic direction.
    */
    gpsTrackRef: prefixer('gpsTrackRef'),

    /**
    * **[GPSVersionID](http://www.w3.org/2003/12/exif/ns#gpsVersionID)** (property)
    * 
    * The version of GPSInfoIFD. The version is given as 2.2.0.0. This tag is mandatory when GPSInfo tag is present.
    */
    gpsVersionID: prefixer('gpsVersionID'),

    /**
    * **[Height](http://www.w3.org/2003/12/exif/ns#height)** (property)
    * 
    * Height of an object
    */
    height: prefixer('height'),

    /**
    * **[ImageDescription](http://www.w3.org/2003/12/exif/ns#imageDescription)** (property)
    * 
    * A character string giving the title of the image. It may be a comment such as "1988 company picnic" or the like. Two-byte character codes cannot be used. When a 2-byte code is necessary, the Exif Private tag UserComment is to be used.
    */
    imageDescription: prefixer('imageDescription'),

    /**
    * **[ImageLength](http://www.w3.org/2003/12/exif/ns#imageLength)** (property)
    * 
    * Image height. The number of rows of image data. In JPEG compressed data a JPEG marker is used.
    */
    imageLength: prefixer('imageLength'),

    /**
    * **[ImageUniqueID](http://www.w3.org/2003/12/exif/ns#imageUniqueID)** (property)
    * 
    * An identifier assigned uniquely to each image. It is recorded as an ASCII string equivalent to hexadecimal notation and 128-bit fixed length.
    */
    imageUniqueID: prefixer('imageUniqueID'),

    /**
    * **[ImageWidth](http://www.w3.org/2003/12/exif/ns#imageWidth)** (property)
    * 
    * Image width. The number of columns of image data, equal to the number of pixels per row. In JPEG compressed data a JPEG marker is used instead of this tag.
    */
    imageWidth: prefixer('imageWidth'),

    /**
    * **[Width](http://www.w3.org/2003/12/exif/ns#width)** (property)
    * 
    * Width of an object
    */
    width: prefixer('width'),

    /**
    * **[Interoperability Info](http://www.w3.org/2003/12/exif/ns#interopInfo)** (property)
    * 
    * An attribute relating to Interoperability. Tags stored in
    * Interoperability IFD may be defined dependently to each Interoperability rule.
    */
    interopInfo: prefixer('interopInfo'),

    /**
    * **[InteroperabilityIndex](http://www.w3.org/2003/12/exif/ns#interoperabilityIndex)** (property)
    * 
    * Indicates the identification of the Interoperability rule. 'R98' = conforming to R98 file specification of Recommended Exif Interoperability Rules (ExifR98) or to DCF basic file stipulated by Design Rule for Camera File System. 'THM' = conforming to DCF thumbnail file stipulated by Design rule for Camera File System.
    */
    interoperabilityIndex: prefixer('interoperabilityIndex'),

    /**
    * **[InteroperabilityVersion](http://www.w3.org/2003/12/exif/ns#interoperabilityVersion)** (property)
    * 
    * Interoperability Version
    */
    interoperabilityVersion: prefixer('interoperabilityVersion'),

    /**
    * **[Interoperability IFD Pointer](http://www.w3.org/2003/12/exif/ns#interoperability_IFD_Pointer)** (property)
    * 
    * A pointer to the Interoperability IFD, which is composed of tags storing the information to ensure the Interoperability
    */
    interoperability_IFD_Pointer: prefixer('interoperability_IFD_Pointer'),

    /**
    * **[ISOSpeedRatings](http://www.w3.org/2003/12/exif/ns#isoSpeedRatings)** (property)
    * 
    * Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.
    */
    isoSpeedRatings: prefixer('isoSpeedRatings'),

    /**
    * **[JPEGInterchangeFormat](http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormat)** (property)
    * 
    * The offset to the start byte (SOI) of JPEG compressed thumbnail data. This is not used for primary image JPEG data.
    */
    jpegInterchangeFormat: prefixer('jpegInterchangeFormat'),

    /**
    * **[Recording Offset](http://www.w3.org/2003/12/exif/ns#recOffset)** (property)
    * 
    * An attribute relating to recording offset
    */
    recOffset: prefixer('recOffset'),

    /**
    * **[JPEGInterchangeFormatLength](http://www.w3.org/2003/12/exif/ns#jpegInterchangeFormatLength)** (property)
    * 
    * The number of bytes of JPEG compressed thumbnail data. This is not used for primary image JPEG data.
    */
    jpegInterchangeFormatLength: prefixer('jpegInterchangeFormatLength'),

    /**
    * **[LightSource](http://www.w3.org/2003/12/exif/ns#lightSource)** (property)
    * 
    * Light source such as Daylight, Tungsten, Flash etc.
    */
    lightSource: prefixer('lightSource'),

    /**
    * **[Make](http://www.w3.org/2003/12/exif/ns#make)** (property)
    * 
    * Manufacturer of image input equipment
    */
    make: prefixer('make'),

    /**
    * **[MakerNote](http://www.w3.org/2003/12/exif/ns#makerNote)** (property)
    * 
    * Manufacturer notes
    */
    makerNote: prefixer('makerNote'),

    /**
    * **[User Info](http://www.w3.org/2003/12/exif/ns#userInfo)** (property)
    * 
    * An attribute relating to User Information
    */
    userInfo: prefixer('userInfo'),

    /**
    * **[MaxApertureValue](http://www.w3.org/2003/12/exif/ns#maxApertureValue)** (property)
    * 
    * The smallest F number of the lens. The unit is the APEX value. Ordinarily it is given in the range of 00.00 to 99.99, but it is not limited to this range.
    */
    maxApertureValue: prefixer('maxApertureValue'),

    /**
    * **[Meter](http://www.w3.org/2003/12/exif/ns#meter)** (property)
    * 
    * A length with unit of meter
    */
    meter: prefixer('meter'),

    /**
    * **[MeteringMode](http://www.w3.org/2003/12/exif/ns#meteringMode)** (property)
    * 
    * Metering mode, such as CenterWeightedAverage, Spot, MultiSpot,Pattern, Partial etc.
    */
    meteringMode: prefixer('meteringMode'),

    /**
    * **[Model](http://www.w3.org/2003/12/exif/ns#model)** (property)
    * 
    * Model of image input equipment
    */
    model: prefixer('model'),

    /**
    * **[OECF](http://www.w3.org/2003/12/exif/ns#oecf)** (property)
    * 
    * Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524. OECF is the relationship between the camera optical input and the image values.
    */
    oecf: prefixer('oecf'),

    /**
    * **[Orientation](http://www.w3.org/2003/12/exif/ns#orientation)** (property)
    * 
    * The image orientation viewed in terms of rows and columns.
    */
    orientation: prefixer('orientation'),

    /**
    * **[PhotometricInterpretation](http://www.w3.org/2003/12/exif/ns#photometricInterpretation)** (property)
    * 
    * Pixel composition. In JPEG compressed data a JPEG marker is used instead of this tag.
    */
    photometricInterpretation: prefixer('photometricInterpretation'),

    /**
    * **[PrintIM Brightness](http://www.w3.org/2003/12/exif/ns#pimBrightness)** (property)
    * 
    * Brightness info for print image matching
    */
    pimBrightness: prefixer('pimBrightness'),

    /**
    * **[PIM Info](http://www.w3.org/2003/12/exif/ns#pimInfo)** (property)
    * 
    * An attribute relating to print image matching
    */
    pimInfo: prefixer('pimInfo'),

    /**
    * **[PrintIM ColorBalance](http://www.w3.org/2003/12/exif/ns#pimColorBalance)** (property)
    * 
    * ColorBalance info for print image matching
    */
    pimColorBalance: prefixer('pimColorBalance'),

    /**
    * **[PrintIM Contrast](http://www.w3.org/2003/12/exif/ns#pimContrast)** (property)
    * 
    * Contrast info for print image matching
    */
    pimContrast: prefixer('pimContrast'),

    /**
    * **[PrintIM Saturation](http://www.w3.org/2003/12/exif/ns#pimSaturation)** (property)
    * 
    * Saturation info for print image matching
    */
    pimSaturation: prefixer('pimSaturation'),

    /**
    * **[PrintIM Sharpness](http://www.w3.org/2003/12/exif/ns#pimSharpness)** (property)
    * 
    * Sharpness info for print image matching
    */
    pimSharpness: prefixer('pimSharpness'),

    /**
    * **[PixelXDimension](http://www.w3.org/2003/12/exif/ns#pixelXDimension)** (property)
    * 
    * Information specific to compressed data. When a compressed file is recorded, the valid width of the meaningful image shall be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file.
    */
    pixelXDimension: prefixer('pixelXDimension'),

    /**
    * **[PixelYDimension](http://www.w3.org/2003/12/exif/ns#pixelYDimension)** (property)
    * 
    * Information specific to compressed data. When a compressed file is recorded, the valid height of the meaningful image shall be recorded in this tag, whether or not there is padding data or a restart marker. This tag should not exist in an uncompressed file. Since data padding is unnecessary in the vertical direction, the number of lines recorded in this valid image height tag will in fact be the same as that recorded in the SOF.
    */
    pixelYDimension: prefixer('pixelYDimension'),

    /**
    * **[PlanarConfiguration](http://www.w3.org/2003/12/exif/ns#planarConfiguration)** (property)
    * 
    * Indicates whether pixel components are recorded in chunky or planar format. In JPEG compressed files a JPEG marker is used instead of this tag. If this field does not exist, the TIFF default of 1 (chunky) is assumed.
    */
    planarConfiguration: prefixer('planarConfiguration'),

    /**
    * **[PrimaryChromaticities](http://www.w3.org/2003/12/exif/ns#primaryChromaticities)** (property)
    * 
    * The chromaticity of the three primary colors of the image. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).
    */
    primaryChromaticities: prefixer('primaryChromaticities'),

    /**
    * **[PrintImageMatching IFD Pointer](http://www.w3.org/2003/12/exif/ns#printImageMatching_IFD_Pointer)** (property)
    * 
    * A pointer to the print image matching IFD
    */
    printImageMatching_IFD_Pointer: prefixer('printImageMatching_IFD_Pointer'),

    /**
    * **[ReferenceBlackWhite](http://www.w3.org/2003/12/exif/ns#referenceBlackWhite)** (property)
    * 
    * The reference black point value and reference white point value. The color space is declared in a color space information tag, with the default being the value that gives the optimal image characteristics Interoperability these conditions.
    */
    referenceBlackWhite: prefixer('referenceBlackWhite'),

    /**
    * **[Related File](http://www.w3.org/2003/12/exif/ns#relatedFile)** (property)
    * 
    * Tag Relating to Related File Information
    */
    relatedFile: prefixer('relatedFile'),

    /**
    * **[RelatedImageFileFormat](http://www.w3.org/2003/12/exif/ns#relatedImageFileFormat)** (property)
    * 
    * Related image file format
    */
    relatedImageFileFormat: prefixer('relatedImageFileFormat'),

    /**
    * **[RelatedImageLength](http://www.w3.org/2003/12/exif/ns#relatedImageLength)** (property)
    * 
    * Related image length
    */
    relatedImageLength: prefixer('relatedImageLength'),

    /**
    * **[RelatedImageWidth](http://www.w3.org/2003/12/exif/ns#relatedImageWidth)** (property)
    * 
    * Related image width
    */
    relatedImageWidth: prefixer('relatedImageWidth'),

    /**
    * **[RelatedSoundFile](http://www.w3.org/2003/12/exif/ns#relatedSoundFile)** (property)
    * 
    * Related audio file
    */
    relatedSoundFile: prefixer('relatedSoundFile'),

    /**
    * **[ResolutionUnit](http://www.w3.org/2003/12/exif/ns#resolutionUnit)** (property)
    * 
    * The unit for measuring XResolution and YResolution. The same unit is used for both XResolution and YResolution. If the image resolution in unknown, 2 (inches) is designated.
    */
    resolutionUnit: prefixer('resolutionUnit'),

    /**
    * **[RowsPerStrip](http://www.w3.org/2003/12/exif/ns#rowsPerStrip)** (property)
    * 
    * The number of rows per strip. This is the number of rows in the image of one strip when an image is divided into strips. With JPEG compressed data this designation is not needed and is omitted.
    */
    rowsPerStrip: prefixer('rowsPerStrip'),

    /**
    * **[SamplesPerPixel](http://www.w3.org/2003/12/exif/ns#samplesPerPixel)** (property)
    * 
    * The number of components per pixel. Since this standard applies to RGB and YCbCr images, the value set for this tag is 3. In JPEG compressed data a JPEG marker is used instead of this tag.
    */
    samplesPerPixel: prefixer('samplesPerPixel'),

    /**
    * **[Saturation](http://www.w3.org/2003/12/exif/ns#saturation)** (property)
    * 
    * The direction of saturation processing applied by the camera when the image was shot.
    */
    saturation: prefixer('saturation'),

    /**
    * **[SceneCaptureType](http://www.w3.org/2003/12/exif/ns#sceneCaptureType)** (property)
    * 
    * The type of scene that was shot. It can also be used to record the mode in which the image was shot, such as Landscape, Portrait etc. Note that this differs from the scene type (SceneType) tag.
    */
    sceneCaptureType: prefixer('sceneCaptureType'),

    /**
    * **[SceneType](http://www.w3.org/2003/12/exif/ns#sceneType)** (property)
    * 
    * The type of scene. If a DSC recorded the image, this tag value shall always be set to 1, indicating that the image was directly photographed.
    */
    sceneType: prefixer('sceneType'),

    /**
    * **[SensingMethod](http://www.w3.org/2003/12/exif/ns#sensingMethod)** (property)
    * 
    * The image sensor type on the camera or input device, such as One-chip color area sensor etc.
    */
    sensingMethod: prefixer('sensingMethod'),

    /**
    * **[Sharpness](http://www.w3.org/2003/12/exif/ns#sharpness)** (property)
    * 
    * The direction of sharpness processing applied by the camera when the image was shot.
    */
    sharpness: prefixer('sharpness'),

    /**
    * **[ShutterSpeedValue](http://www.w3.org/2003/12/exif/ns#shutterSpeedValue)** (property)
    * 
    * Shutter speed. The unit is the APEX (Additive System of Photographic Exposure) setting
    */
    shutterSpeedValue: prefixer('shutterSpeedValue'),

    /**
    * **[Software](http://www.w3.org/2003/12/exif/ns#software)** (property)
    * 
    * The name and version of the software or firmware of the camera or image input device used to generate the image.
    */
    software: prefixer('software'),

    /**
    * **[SpatialFrequencyResponse](http://www.w3.org/2003/12/exif/ns#spatialFrequencyResponse)** (property)
    * 
    * This tag records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.
    */
    spatialFrequencyResponse: prefixer('spatialFrequencyResponse'),

    /**
    * **[SpectralSensitivity](http://www.w3.org/2003/12/exif/ns#spectralSensitivity)** (property)
    * 
    * Indicates the spectral sensitivity of each channel of the camera used. The tag value is an ASCII string compatible with the standard developed by the ASTM Technical committee.
    */
    spectralSensitivity: prefixer('spectralSensitivity'),

    /**
    * **[StripByteCounts](http://www.w3.org/2003/12/exif/ns#stripByteCounts)** (property)
    * 
    * The total number of bytes in each strip. With JPEG compressed data this designation is not needed and is omitted.
    */
    stripByteCounts: prefixer('stripByteCounts'),

    /**
    * **[StripOffsets](http://www.w3.org/2003/12/exif/ns#stripOffsets)** (property)
    * 
    * For each strip, the byte offset of that strip. With JPEG compressed data this designation is not needed and is omitted.
    */
    stripOffsets: prefixer('stripOffsets'),

    /**
    * **[SubSecTime](http://www.w3.org/2003/12/exif/ns#subSecTime)** (property)
    * 
    * DateTime subseconds
    */
    subSecTime: prefixer('subSecTime'),

    /**
    * **[SubSecTimeDigitized](http://www.w3.org/2003/12/exif/ns#subSecTimeDigitized)** (property)
    * 
    * DateTimeDigitized subseconds
    */
    subSecTimeDigitized: prefixer('subSecTimeDigitized'),

    /**
    * **[SubSecTimeOriginal](http://www.w3.org/2003/12/exif/ns#subSecTimeOriginal)** (property)
    * 
    * DateTimeOriginal subseconds
    */
    subSecTimeOriginal: prefixer('subSecTimeOriginal'),

    /**
    * **[SubjectArea](http://www.w3.org/2003/12/exif/ns#subjectArea)** (property)
    * 
    * The location and area of the main subject in the overall scene.
    */
    subjectArea: prefixer('subjectArea'),

    /**
    * **[SubjectDistance](http://www.w3.org/2003/12/exif/ns#subjectDistance)** (property)
    * 
    * The distance to the subject, given in meters. Note that if the numerator of the recorded value is FFFFFFFF.H, Infinity shall be indicated; and if the numerator is 0, Distance unknown shall be indicated.
    */
    subjectDistance: prefixer('subjectDistance'),

    /**
    * **[SubjectDistanceRange](http://www.w3.org/2003/12/exif/ns#subjectDistanceRange)** (property)
    * 
    * The distance to the subject, such as Macro, Close View or Distant View.
    */
    subjectDistanceRange: prefixer('subjectDistanceRange'),

    /**
    * **[SubjectLocation](http://www.w3.org/2003/12/exif/ns#subjectLocation)** (property)
    * 
    * The location of the main subject in the scene. The value of this tag represents the pixel at the center of the main subject relative to the left edge, prior to rotation processing as per the Rotation tag. The first value indicates the X column number and second indicates the Y row number.
    */
    subjectLocation: prefixer('subjectLocation'),

    /**
    * **[Subseconds](http://www.w3.org/2003/12/exif/ns#subseconds)** (property)
    * 
    * A tag used to record fractions of seconds for a date property
    */
    subseconds: prefixer('subseconds'),

    /**
    * **[Tag number](http://www.w3.org/2003/12/exif/ns#tag_number)** (property)
    * 
    * The Exif tag number
    */
    tag_number: prefixer('tag_number'),

    /**
    * **[Tag ID](http://www.w3.org/2003/12/exif/ns#tagid)** (property)
    * 
    * The Exif tag number with context prefix, such as IFD type or maker name
    */
    tagid: prefixer('tagid'),

    /**
    * **[TransferFunction](http://www.w3.org/2003/12/exif/ns#transferFunction)** (property)
    * 
    * A transfer function for the image, described in tabular style. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).
    */
    transferFunction: prefixer('transferFunction'),

    /**
    * **[UserComment](http://www.w3.org/2003/12/exif/ns#userComment)** (property)
    * 
    * A tag for Exif users to write keywords or comments on the image besides those in ImageDescription, and without the character code limitations of the ImageDescription tag. The character code used in the UserComment tag is identified based on an ID code in a fixed 8-byte area at the start of the tag data area.
    */
    userComment: prefixer('userComment'),

    /**
    * **[WhiteBalance](http://www.w3.org/2003/12/exif/ns#whiteBalance)** (property)
    * 
    * The white balance mode set when the image was shot.
    */
    whiteBalance: prefixer('whiteBalance'),

    /**
    * **[WhitePoint](http://www.w3.org/2003/12/exif/ns#whitePoint)** (property)
    * 
    * The chromaticity of the white point of the image. Normally this tag is not necessary, since color space is specified in the color space information tag (ColorSpace).
    */
    whitePoint: prefixer('whitePoint'),

    /**
    * **[XResolution](http://www.w3.org/2003/12/exif/ns#xResolution)** (property)
    * 
    * The number of pixels per ResolutionUnit in the ImageWidth direction. When the image resolution is unknown, 72 [dpi] is designated.
    */
    xResolution: prefixer('xResolution'),

    /**
    * **[YCbCrCoefficients](http://www.w3.org/2003/12/exif/ns#yCbCrCoefficients)** (property)
    * 
    * The matrix coefficients for transformation from RGB to YCbCr image data.
    */
    yCbCrCoefficients: prefixer('yCbCrCoefficients'),

    /**
    * **[YCbCrPositioning](http://www.w3.org/2003/12/exif/ns#yCbCrPositioning)** (property)
    * 
    * The position of chrominance components in relation to the luminance component. This field is designated only for JPEG compressed data or uncompressed YCbCr data.
    */
    yCbCrPositioning: prefixer('yCbCrPositioning'),

    /**
    * **[YCbCrSubSampling](http://www.w3.org/2003/12/exif/ns#yCbCrSubSampling)** (property)
    * 
    * The sampling ratio of chrominance components in relation to the luminance component. In JPEG compressed data a JPEG marker is used instead of this tag.
    */
    yCbCrSubSampling: prefixer('yCbCrSubSampling'),

    /**
    * **[YResolution](http://www.w3.org/2003/12/exif/ns#yResolution)** (property)
    * 
    * The number of pixels per ResolutionUnit in the ImageLength direction. The same value as XResolution is designated.
    */
    yResolution: prefixer('yResolution'),

  
  };

export default exif

