// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.opengis.net/ont/geosparql#');

/**
 * [geo](http://www.opengis.net/ont/geosparql#})
 */
const geo = {
  /**
    * **[Feature](http://www.opengis.net/ont/geosparql#Feature)** (class)
    * 
    * A discrete spatial phenomenon in a universe of discourse.
    */
    Feature: prefixer('Feature'),

    /**
    * **[Spatial Object](http://www.opengis.net/ont/geosparql#SpatialObject)** (class)
    * 
    * Anything spatial (being or having a shape, position or an extent).
    */
    SpatialObject: prefixer('SpatialObject'),

    /**
    * **[Geometry](http://www.opengis.net/ont/geosparql#Geometry)** (class)
    * 
    * A coherent set of direct positions in space. The positions are held within a Spatial Reference System (SRS).
    */
    Geometry: prefixer('Geometry'),

    /**
    * **[Feature Collection](http://www.opengis.net/ont/geosparql#FeatureCollection)** (class)
    * 
    * A collection of individual Features.
    */
    FeatureCollection: prefixer('FeatureCollection'),

    /**
    * **[Spatial Object Collection](http://www.opengis.net/ont/geosparql#SpatialObjectCollection)** (class)
    * 
    * A collection of individual Spatial Objects.
    */
    SpatialObjectCollection: prefixer('SpatialObjectCollection'),

    /**
    * **[Geometry Collection](http://www.opengis.net/ont/geosparql#GeometryCollection)** (class)
    * 
    * A collection of individual Geometries.
    */
    GeometryCollection: prefixer('GeometryCollection'),

    /**
    * **[as DGGS](http://www.opengis.net/ont/geosparql#asDGGS)** (property)
    * 
    * The Discrete Global Grid System (DGGS) serialization of a Geometry
    */
    asDGGS: prefixer('asDGGS'),

    /**
    * **[has serialization](http://www.opengis.net/ont/geosparql#hasSerialization)** (property)
    * 
    * Connects a Geometry object with its text-based serialization.
    */
    hasSerialization: prefixer('hasSerialization'),

    /**
    * **[as GML](http://www.opengis.net/ont/geosparql#asGML)** (property)
    * 
    * The GML serialization of a Geometry
    */
    asGML: prefixer('asGML'),

    /**
    * **[as GeoJSON](http://www.opengis.net/ont/geosparql#asGeoJSON)** (property)
    * 
    * The GeoJSON serialization of a Geometry
    */
    asGeoJSON: prefixer('asGeoJSON'),

    /**
    * **[as KML](http://www.opengis.net/ont/geosparql#asKML)** (property)
    * 
    * The KML serialization of a Geometry
    */
    asKML: prefixer('asKML'),

    /**
    * **[as WKT](http://www.opengis.net/ont/geosparql#asWKT)** (property)
    * 
    * The WKT serialization of a Geometry
    */
    asWKT: prefixer('asWKT'),

    /**
    * **[coordinate dimension](http://www.opengis.net/ont/geosparql#coordinateDimension)** (property)
    * 
    * The number of measurements or axes needed to describe the position of this Geometry in a coordinate system.
    */
    coordinateDimension: prefixer('coordinateDimension'),

    /**
    * **[default geometry](http://www.opengis.net/ont/geosparql#defaultGeometry)** (property)
    * 
    * The default Geometry to be used in spatial calculations. It is usually the most detailed Geometry.
    */
    defaultGeometry: prefixer('defaultGeometry'),

    /**
    * **[has geometry](http://www.opengis.net/ont/geosparql#hasGeometry)** (property)
    * 
    * A spatial representation for a given Feature.
    */
    hasGeometry: prefixer('hasGeometry'),

    /**
    * **[has default geometry](http://www.opengis.net/ont/geosparql#hasDefaultGeometry)** (property)
    * 
    * The default Geometry to be used in spatial calculations. It is usually the most detailed Geometry.
    */
    hasDefaultGeometry: prefixer('hasDefaultGeometry'),

    /**
    * **[dimension](http://www.opengis.net/ont/geosparql#dimension)** (property)
    * 
    * The topological dimension of this geometric object, which must be less than or equal to the coordinate dimension. In non-homogeneous collections, this will return the largest topological dimension of the contained objects.
    */
    dimension: prefixer('dimension'),

    /**
    * **[contains](http://www.opengis.net/ont/geosparql#ehContains)** (property)
    * 
    * States that the subject SpatialObject spatially contains the object SpatialObject. DE-9IM: T*TFF*FF*
    */
    ehContains: prefixer('ehContains'),

    /**
    * **[covered by](http://www.opengis.net/ont/geosparql#ehCoveredBy)** (property)
    * 
    * States that the subject SpatialObject is spatially covered by the object SpatialObject. DE-9IM: TFF*TFT**
    */
    ehCoveredBy: prefixer('ehCoveredBy'),

    /**
    * **[covers](http://www.opengis.net/ont/geosparql#ehCovers)** (property)
    * 
    * States that the subject SpatialObject spatially covers the object SpatialObject. DE-9IM: T*TFT*FF*
    */
    ehCovers: prefixer('ehCovers'),

    /**
    * **[disjoint](http://www.opengis.net/ont/geosparql#ehDisjoint)** (property)
    * 
    * States that the subject SpatialObject is spatially disjoint from the object SpatialObject. DE-9IM: FF*FF****
    */
    ehDisjoint: prefixer('ehDisjoint'),

    /**
    * **[disjoint](http://www.opengis.net/ont/geosparql#sfDisjoint)** (property)
    * 
    * States that the subject SpatialObject is spatially disjoint from the object SpatialObject. DE-9IM: FF*FF****
    */
    sfDisjoint: prefixer('sfDisjoint'),

    /**
    * **[equals](http://www.opengis.net/ont/geosparql#ehEquals)** (property)
    * 
    * States that the subject SpatialObject spatially equals the object SpatialObject. DE-9IM: TFFFTFFFT
    */
    ehEquals: prefixer('ehEquals'),

    /**
    * **[equals](http://www.opengis.net/ont/geosparql#sfEquals)** (property)
    * 
    * States that the subject SpatialObject spatially equals the object SpatialObject. DE-9IM: TFFFTFFFT
    */
    sfEquals: prefixer('sfEquals'),

    /**
    * **[inside](http://www.opengis.net/ont/geosparql#ehInside)** (property)
    * 
    * States that the subject SpatialObject is spatially inside the object SpatialObject. DE-9IM: TFF*FFT**
    */
    ehInside: prefixer('ehInside'),

    /**
    * **[meet](http://www.opengis.net/ont/geosparql#ehMeet)** (property)
    * 
    * States that the subject SpatialObject spatially meets the object SpatialObject. DE-9IM: FT******* ^ F**T***** ^ F***T****
    */
    ehMeet: prefixer('ehMeet'),

    /**
    * **[touches](http://www.opengis.net/ont/geosparql#sfTouches)** (property)
    * 
    * States that the subject SpatialObject spatially touches the object SpatialObject. DE-9IM: FT******* ^ F**T***** ^ F***T****
    */
    sfTouches: prefixer('sfTouches'),

    /**
    * **[overlap](http://www.opengis.net/ont/geosparql#ehOverlap)** (property)
    * 
    * States that the subject SpatialObject spatially overlaps the object SpatialObject. DE-9IM: T*T***T**
    */
    ehOverlap: prefixer('ehOverlap'),

    /**
    * **[has area](http://www.opengis.net/ont/geosparql#hasArea)** (property)
    * 
    * The area of a Spatial Object.
    */
    hasArea: prefixer('hasArea'),

    /**
    * **[has size](http://www.opengis.net/ont/geosparql#hasSize)** (property)
    * 
    * Subproperties of this property are used to indicate the size of a Spatial Object as a measurement or estimate of one or more dimensions of the Spatial Object's spatial presence.
    */
    hasSize: prefixer('hasSize'),

    /**
    * **[has bounding box](http://www.opengis.net/ont/geosparql#hasBoundingBox)** (property)
    * 
    * The minimum or smallest bounding or enclosing box of a given Feature.
    */
    hasBoundingBox: prefixer('hasBoundingBox'),

    /**
    * **[has centroid](http://www.opengis.net/ont/geosparql#hasCentroid)** (property)
    * 
    * The arithmetic mean position of all the Geometry points of a given Feature.
    */
    hasCentroid: prefixer('hasCentroid'),

    /**
    * **[has length](http://www.opengis.net/ont/geosparql#hasLength)** (property)
    * 
    * The length of a Spatial Object.
    */
    hasLength: prefixer('hasLength'),

    /**
    * **[has area in square meters](http://www.opengis.net/ont/geosparql#hasMetricArea)** (property)
    * 
    * The area of a Spatial Object in square meters.
    */
    hasMetricArea: prefixer('hasMetricArea'),

    /**
    * **[has metric size](http://www.opengis.net/ont/geosparql#hasMetricSize)** (property)
    * 
    * Subproperties of this property are used to indicate the size of a Spatial Object, as a measurement or estimate of one or more dimensions of the Spatial Object's spatial presence. Units are always metric (meter, square meter or cubic meter).
    */
    hasMetricSize: prefixer('hasMetricSize'),

    /**
    * **[has length in meters](http://www.opengis.net/ont/geosparql#hasMetricLength)** (property)
    * 
    * The length of a Spatial Object in meters.
    */
    hasMetricLength: prefixer('hasMetricLength'),

    /**
    * **[has perimeter length in meters](http://www.opengis.net/ont/geosparql#hasMetricPerimeterLength)** (property)
    * 
    * The length of the perimeter of a Spatial Object in meters.
    */
    hasMetricPerimeterLength: prefixer('hasMetricPerimeterLength'),

    /**
    * **[has spatial accuracy in meters](http://www.opengis.net/ont/geosparql#hasMetricSpatialAccuracy)** (property)
    * 
    * The positional accuracy of the coordinates of a Geometry in meters.
    */
    hasMetricSpatialAccuracy: prefixer('hasMetricSpatialAccuracy'),

    /**
    * **[has spatial resolution in meters](http://www.opengis.net/ont/geosparql#hasMetricSpatialResolution)** (property)
    * 
    * The spatial resolution of a Geometry in meters.
    */
    hasMetricSpatialResolution: prefixer('hasMetricSpatialResolution'),

    /**
    * **[has volume in cubic meters](http://www.opengis.net/ont/geosparql#hasMetricVolume)** (property)
    * 
    * The volume of a Spatial Object in cubic meters.
    */
    hasMetricVolume: prefixer('hasMetricVolume'),

    /**
    * **[has perimeter length](http://www.opengis.net/ont/geosparql#hasPerimeterLength)** (property)
    * 
    * The length of the perimeter of a Spatial Object.
    */
    hasPerimeterLength: prefixer('hasPerimeterLength'),

    /**
    * **[has spatial accuracy](http://www.opengis.net/ont/geosparql#hasSpatialAccuracy)** (property)
    * 
    * The positional accuracy of the coordinates of a Geometry.
    */
    hasSpatialAccuracy: prefixer('hasSpatialAccuracy'),

    /**
    * **[has spatial resolution](http://www.opengis.net/ont/geosparql#hasSpatialResolution)** (property)
    * 
    * The spatial resolution of a Geometry.
    */
    hasSpatialResolution: prefixer('hasSpatialResolution'),

    /**
    * **[has volume](http://www.opengis.net/ont/geosparql#hasVolume)** (property)
    * 
    * The volume of a three-dimensional Spatial Object.
    */
    hasVolume: prefixer('hasVolume'),

    /**
    * **[is empty](http://www.opengis.net/ont/geosparql#isEmpty)** (property)
    * 
    * (true) if this geometric object is the empty Geometry. If true, then this geometric object represents the empty point set for the coordinate space.
    */
    isEmpty: prefixer('isEmpty'),

    /**
    * **[is simple](http://www.opengis.net/ont/geosparql#isSimple)** (property)
    * 
    * (true) if this geometric object has no anomalous geometric points, such as self intersection or self tangency.
    */
    isSimple: prefixer('isSimple'),

    /**
    * **[disconnected](http://www.opengis.net/ont/geosparql#rcc8dc)** (property)
    * 
    * States that the subject SpatialObject is spatially disjoint from the object SpatialObject. DE-9IM: FFTFFTTTT
    */
    rcc8dc: prefixer('rcc8dc'),

    /**
    * **[externally connected](http://www.opengis.net/ont/geosparql#rcc8ec)** (property)
    * 
    * States that the subject SpatialObject spatially meets the object SpatialObject. DE-9IM: FFTFTTTTT
    */
    rcc8ec: prefixer('rcc8ec'),

    /**
    * **[equals](http://www.opengis.net/ont/geosparql#rcc8eq)** (property)
    * 
    * States that the subject SpatialObject spatially equals the object SpatialObject. DE-9IM: TFFFTFFFT
    */
    rcc8eq: prefixer('rcc8eq'),

    /**
    * **[non-tangential proper part](http://www.opengis.net/ont/geosparql#rcc8ntpp)** (property)
    * 
    * States that the subject SpatialObject is spatially inside the object SpatialObject. DE-9IM: TFFTFFTTT
    */
    rcc8ntpp: prefixer('rcc8ntpp'),

    /**
    * **[non-tangential proper part inverse](http://www.opengis.net/ont/geosparql#rcc8ntppi)** (property)
    * 
    * States that the subject SpatialObject spatially contains the object SpatialObject. DE-9IM: TTTFFTFFT
    */
    rcc8ntppi: prefixer('rcc8ntppi'),

    /**
    * **[partially overlapping](http://www.opengis.net/ont/geosparql#rcc8po)** (property)
    * 
    * States that the subject SpatialObject spatially overlaps the object SpatialObject. DE-9IM: TTTTTTTTT
    */
    rcc8po: prefixer('rcc8po'),

    /**
    * **[tangential proper part](http://www.opengis.net/ont/geosparql#rcc8tpp)** (property)
    * 
    * States that the subject SpatialObject is spatially covered by the object SpatialObject. DE-9IM: TFFTTFTTT
    */
    rcc8tpp: prefixer('rcc8tpp'),

    /**
    * **[tangential proper part inverse](http://www.opengis.net/ont/geosparql#rcc8tppi)** (property)
    * 
    * States that the subject SpatialObject spatially covers the object SpatialObject. DE-9IM: TTTFTTFFT
    */
    rcc8tppi: prefixer('rcc8tppi'),

    /**
    * **[contains](http://www.opengis.net/ont/geosparql#sfContains)** (property)
    * 
    * States that the subject SpatialObject spatially contains the object SpatialObject. DE-9IM: T*****FF*
    */
    sfContains: prefixer('sfContains'),

    /**
    * **[crosses](http://www.opengis.net/ont/geosparql#sfCrosses)** (property)
    * 
    * States that the subject SpatialObject spatially crosses the object SpatialObject. DE-9IM: T*T******
    */
    sfCrosses: prefixer('sfCrosses'),

    /**
    * **[intersects](http://www.opengis.net/ont/geosparql#sfIntersects)** (property)
    * 
    * States that the subject SpatialObject is not spatially disjoint from the object SpatialObject. DE-9IM: T******** ^ *T******* ^ ***T***** ^ ****T****
    */
    sfIntersects: prefixer('sfIntersects'),

    /**
    * **[overlaps](http://www.opengis.net/ont/geosparql#sfOverlaps)** (property)
    * 
    * States that the subject SpatialObject spatially overlaps the object SpatialObject. DE-9IM: T*T***T**
    */
    sfOverlaps: prefixer('sfOverlaps'),

    /**
    * **[within](http://www.opengis.net/ont/geosparql#sfWithin)** (property)
    * 
    * States that the subject SpatialObject is spatially within the object SpatialObject. DE-9IM: T*F**F***
    */
    sfWithin: prefixer('sfWithin'),

    /**
    * **[spatial dimension](http://www.opengis.net/ont/geosparql#spatialDimension)** (property)
    * 
    * The number of measurements or axes needed to describe the spatial position of this Geometry in a coordinate system.
    */
    spatialDimension: prefixer('spatialDimension'),

  
  };

export default geo

