// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.w3.org/ns/solid/oidc#');

/**
 * [oidc](http://www.w3.org/ns/solid/oidc#})
 */
const oidc = {
  /**
    * **[application type](http://www.w3.org/ns/solid/oidc#application_type)** (property)
    * 
    * TODO
    */
    application_type: prefixer('application_type'),

    /**
    * **[client name](http://www.w3.org/ns/solid/oidc#client_name)** (property)
    * 
    * A name for this client that can be presented to an End-User
    */
    client_name: prefixer('client_name'),

    /**
    * **[client URI](http://www.w3.org/ns/solid/oidc#client_uri)** (property)
    * 
    * A URI for this client's home page
    */
    client_uri: prefixer('client_uri'),

    /**
    * **[contacts](http://www.w3.org/ns/solid/oidc#contacts)** (property)
    * 
    * A collection of URIs where individuals or entities responsible for this client can be contacted.
    */
    contacts: prefixer('contacts'),

    /**
    * **[default max age](http://www.w3.org/ns/solid/oidc#default_max_age)** (property)
    * 
    * TODO
    */
    default_max_age: prefixer('default_max_age'),

    /**
    * **[grant types](http://www.w3.org/ns/solid/oidc#grant_types)** (property)
    * 
    * A collection of OAuth 2.0 Grant Types that the client will restrict itself to using.
    */
    grant_types: prefixer('grant_types'),

    /**
    * **[logo URI](http://www.w3.org/ns/solid/oidc#logo_uri)** (property)
    * 
    * A URI for this client's logo
    */
    logo_uri: prefixer('logo_uri'),

    /**
    * **[policy URI](http://www.w3.org/ns/solid/oidc#policy_uri)** (property)
    * 
    * A URI for this client's policy document
    */
    policy_uri: prefixer('policy_uri'),

    /**
    * **[redirect URIs](http://www.w3.org/ns/solid/oidc#redirect_uris)** (property)
    * 
    * A collection of registered URIs used by the client for redirection
    */
    redirect_uris: prefixer('redirect_uris'),

    /**
    * **[require auth time](http://www.w3.org/ns/solid/oidc#require_auth_time)** (property)
    * 
    * TODO
    */
    require_auth_time: prefixer('require_auth_time'),

    /**
    * **[response types](http://www.w3.org/ns/solid/oidc#response_types)** (property)
    * 
    * A collection of OAuth 2.0 Response Types that the client will restrict itself to using.
    */
    response_types: prefixer('response_types'),

    /**
    * **[scope](http://www.w3.org/ns/solid/oidc#scope)** (property)
    * 
    * An OAuth2 scope for the requested access token.
    */
    scope: prefixer('scope'),

    /**
    * **[token endpoint auth method](http://www.w3.org/ns/solid/oidc#token_endpoint_auth_method)** (property)
    * 
    * The requested client authentication method for the Token Endpoint
    */
    token_endpoint_auth_method: prefixer('token_endpoint_auth_method'),

    /**
    * **[ToS URI](http://www.w3.org/ns/solid/oidc#tos_uri)** (property)
    * 
    * A URI for this client's terms of service document
    */
    tos_uri: prefixer('tos_uri'),

  
  };

export default oidc

