// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.w3.org/ns/prov#');

/**
 * [prov](http://www.w3.org/ns/prov#})
 */
const prov = {
  /**
    * **[wasRevisionOf](http://www.w3.org/ns/prov#wasRevisionOf)** (property)
    * 
    * A revision is a derivation that revises an entity into a revised version.
    */
    wasRevisionOf: prefixer('wasRevisionOf'),

    /**
    * **[ActivityInfluence](http://www.w3.org/ns/prov#ActivityInfluence)** (class)
    * 
    * ActivityInfluence provides additional descriptions of an Activity's binary influence upon any other kind of resource. Instances of ActivityInfluence use the prov:activity property to cite the influencing Activity.
    */
    ActivityInfluence: prefixer('ActivityInfluence'),

    /**
    * **[Influence](http://www.w3.org/ns/prov#Influence)** (class)
    * 
    * An instance of prov:Influence provides additional descriptions about the binary prov:wasInfluencedBy relation from some influenced Activity, Entity, or Agent to the influencing Activity, Entity, or Agent. For example, :stomach_ache prov:wasInfluencedBy :spoon; prov:qualifiedInfluence [ a prov:Influence; prov:entity :spoon; :foo :bar ] . Because prov:Influence is a broad relation, the more specific relations (Communication, Delegation, End, etc.) should be used when applicable.
    */
    Influence: prefixer('Influence'),

    /**
    * **[EntityInfluence](http://www.w3.org/ns/prov#EntityInfluence)** (class)
    * 
    * EntityInfluence provides additional descriptions of an Entity's binary influence upon any other kind of resource. Instances of EntityInfluence use the prov:entity property to cite the influencing Entity.
    */
    EntityInfluence: prefixer('EntityInfluence'),

    /**
    * **[InstantaneousEvent](http://www.w3.org/ns/prov#InstantaneousEvent)** (class)
    * 
    * An instantaneous event, or event for short, happens in the world and marks a change in the world, in its activities and in its entities. The term 'event' is commonly used in process algebra with a similar meaning. Events represent communications or interactions; they are assumed to be atomic and instantaneous.
    */
    InstantaneousEvent: prefixer('InstantaneousEvent'),

    /**
    * **[AgentInfluence](http://www.w3.org/ns/prov#AgentInfluence)** (class)
    * 
    * AgentInfluence provides additional descriptions of an Agent's binary influence upon any other kind of resource. Instances of AgentInfluence use the prov:agent property to cite the influencing Agent.
    */
    AgentInfluence: prefixer('AgentInfluence'),

    /**
    * **[Association](http://www.w3.org/ns/prov#Association)** (class)
    * 
    * An instance of prov:Association provides additional descriptions about the binary prov:wasAssociatedWith relation from an prov:Activity to some prov:Agent that had some responsiblity for it. For example, :baking prov:wasAssociatedWith :baker; prov:qualifiedAssociation [ a prov:Association; prov:agent :baker; :foo :bar ].
    */
    Association: prefixer('Association'),

    /**
    * **[wasDerivedFrom](http://www.w3.org/ns/prov#wasDerivedFrom)** (property)
    * 
    * The more specific subproperties of prov:wasDerivedFrom (i.e., prov:wasQuotedFrom, prov:wasRevisionOf, prov:hadPrimarySource) should be used when applicable.
    */
    wasDerivedFrom: prefixer('wasDerivedFrom'),

    /**
    * **[Attribution](http://www.w3.org/ns/prov#Attribution)** (class)
    * 
    * An instance of prov:Attribution provides additional descriptions about the binary prov:wasAttributedTo relation from an prov:Entity to some prov:Agent that had some responsible for it. For example, :cake prov:wasAttributedTo :baker; prov:qualifiedAttribution [ a prov:Attribution; prov:entity :baker; :foo :bar ].
    */
    Attribution: prefixer('Attribution'),

    /**
    * **[Bundle](http://www.w3.org/ns/prov#Bundle)** (class)
    * 
    * Note that there are kinds of bundles (e.g. handwritten letters, audio recordings, etc.) that are not expressed in PROV-O, but can be still be described by PROV-O.
    */
    Bundle: prefixer('Bundle'),

    /**
    * **[Communication](http://www.w3.org/ns/prov#Communication)** (class)
    * 
    * An instance of prov:Communication provides additional descriptions about the binary prov:wasInformedBy relation from an informed prov:Activity to the prov:Activity that informed it. For example, :you_jumping_off_bridge prov:wasInformedBy :everyone_else_jumping_off_bridge; prov:qualifiedCommunication [ a prov:Communication; prov:activity :everyone_else_jumping_off_bridge; :foo :bar ].
    */
    Communication: prefixer('Communication'),

    /**
    * **[wasAssociatedWith](http://www.w3.org/ns/prov#wasAssociatedWith)** (property)
    * 
    * An prov:Agent that had some (unspecified) responsibility for the occurrence of this prov:Activity.
    */
    wasAssociatedWith: prefixer('wasAssociatedWith'),

    /**
    * **[wasAttributedTo](http://www.w3.org/ns/prov#wasAttributedTo)** (property)
    * 
    * Attribution is the ascribing of an entity to an agent.
    */
    wasAttributedTo: prefixer('wasAttributedTo'),

    /**
    * **[wasInformedBy](http://www.w3.org/ns/prov#wasInformedBy)** (property)
    * 
    * An activity a2 is dependent on or informed by another activity a1, by way of some unspecified entity that is generated by a1 and used by a2.
    */
    wasInformedBy: prefixer('wasInformedBy'),

    /**
    * **[actedOnBehalfOf](http://www.w3.org/ns/prov#actedOnBehalfOf)** (property)
    * 
    * An object property to express the accountability of an agent towards another agent. The subordinate agent acted on behalf of the responsible agent in an actual activity.
    */
    actedOnBehalfOf: prefixer('actedOnBehalfOf'),

    /**
    * **[wasEndedBy](http://www.w3.org/ns/prov#wasEndedBy)** (property)
    * 
    * End is when an activity is deemed to have ended. An end may refer to an entity, known as trigger, that terminated the activity.
    */
    wasEndedBy: prefixer('wasEndedBy'),

    /**
    * **[Delegation](http://www.w3.org/ns/prov#Delegation)** (class)
    * 
    * An instance of prov:Delegation provides additional descriptions about the binary prov:actedOnBehalfOf relation from a performing prov:Agent to some prov:Agent for whom it was performed. For example, :mixing prov:wasAssociatedWith :toddler . :toddler prov:actedOnBehalfOf :mother; prov:qualifiedDelegation [ a prov:Delegation; prov:entity :mother; :foo :bar ].
    */
    Delegation: prefixer('Delegation'),

    /**
    * **[wasInfluencedBy](http://www.w3.org/ns/prov#wasInfluencedBy)** (property)
    * 
    * This property has multiple RDFS domains to suit multiple OWL Profiles. See <a href="#owl-profile">PROV-O OWL Profile</a>.
    */
    wasInfluencedBy: prefixer('wasInfluencedBy'),

    /**
    * **[Derivation](http://www.w3.org/ns/prov#Derivation)** (class)
    * 
    * An instance of prov:Derivation provides additional descriptions about the binary prov:wasDerivedFrom relation from some derived prov:Entity to another prov:Entity from which it was derived. For example, :chewed_bubble_gum prov:wasDerivedFrom :unwrapped_bubble_gum; prov:qualifiedDerivation [ a prov:Derivation; prov:entity :unwrapped_bubble_gum; :foo :bar ].
    */
    Derivation: prefixer('Derivation'),

    /**
    * **[Dictionary](http://www.w3.org/ns/prov#Dictionary)** (class)
    * 
    * A given dictionary forms a given structure for its members. A different structure (obtained either by insertion or removal of members) constitutes a different dictionary.
    */
    Dictionary: prefixer('Dictionary'),

    /**
    * **[ProvenanceService](http://www.w3.org/ns/prov#DirectQueryService)** (class)
    * 
    * Type for a generic provenance query service. Mainly for use in RDF provenance query service descriptions, to facilitate discovery in linked data environments.
    */
    DirectQueryService: prefixer('DirectQueryService'),

    /**
    * **[atLocation](http://www.w3.org/ns/prov#atLocation)** (property)
    * 
    * The Location of any resource.
    */
    atLocation: prefixer('atLocation'),

    /**
    * **[wasQuotedFrom](http://www.w3.org/ns/prov#wasQuotedFrom)** (property)
    * 
    * An entity is derived from an original entity by copying, or 'quoting', some or all of it.
    */
    wasQuotedFrom: prefixer('wasQuotedFrom'),

    /**
    * **[End](http://www.w3.org/ns/prov#End)** (class)
    * 
    * An instance of prov:End provides additional descriptions about the binary prov:wasEndedBy relation from some ended prov:Activity to an prov:Entity that ended it. For example, :ball_game prov:wasEndedBy :buzzer; prov:qualifiedEnd [ a prov:End; prov:entity :buzzer; :foo :bar; prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime ].
    */
    End: prefixer('End'),

    /**
    * **[hadRole](http://www.w3.org/ns/prov#hadRole)** (property)
    * 
    * This property has multiple RDFS domains to suit multiple OWL Profiles. See <a href="#owl-profile">PROV-O OWL Profile</a>.
    */
    hadRole: prefixer('hadRole'),

    /**
    * **[Generation](http://www.w3.org/ns/prov#Generation)** (class)
    * 
    * An instance of prov:Generation provides additional descriptions about the binary prov:wasGeneratedBy relation from a generated prov:Entity to the prov:Activity that generated it. For example, :cake prov:wasGeneratedBy :baking; prov:qualifiedGeneration [ a prov:Generation; prov:activity :baking; :foo :bar ].
    */
    Generation: prefixer('Generation'),

    /**
    * **[wasStartedBy](http://www.w3.org/ns/prov#wasStartedBy)** (property)
    * 
    * Start is when an activity is deemed to have started. A start may refer to an entity, known as trigger, that initiated the activity.
    */
    wasStartedBy: prefixer('wasStartedBy'),

    /**
    * **[used](http://www.w3.org/ns/prov#used)** (property)
    * 
    * A prov:Entity that was used by this prov:Activity. For example, :baking prov:used :spoon, :egg, :oven .
    */
    used: prefixer('used'),

    /**
    * **[Invalidation](http://www.w3.org/ns/prov#Invalidation)** (class)
    * 
    * An instance of prov:Invalidation provides additional descriptions about the binary prov:wasInvalidatedBy relation from an invalidated prov:Entity to the prov:Activity that invalidated it. For example, :uncracked_egg prov:wasInvalidatedBy :baking; prov:qualifiedInvalidation [ a prov:Invalidation; prov:activity :baking; :foo :bar ].
    */
    Invalidation: prefixer('Invalidation'),

    /**
    * **[qualifiedDelegation](http://www.w3.org/ns/prov#qualifiedDelegation)** (property)
    * 
    * If this Agent prov:actedOnBehalfOf Agent :ag, then it can qualify how with prov:qualifiedResponsibility [ a prov:Responsibility;  prov:agent :ag; :foo :bar ].
    */
    qualifiedDelegation: prefixer('qualifiedDelegation'),

    /**
    * **[influencer](http://www.w3.org/ns/prov#influencer)** (property)
    * 
    * Subproperties of prov:influencer are used to cite the object of an unqualified PROV-O triple whose predicate is a subproperty of prov:wasInfluencedBy (e.g. prov:used, prov:wasGeneratedBy). prov:influencer is used much like rdf:object is used.
    */
    influencer: prefixer('influencer'),

    /**
    * **[asInBundle](http://www.w3.org/ns/prov#asInBundle)** (property)
    * 
    * prov:asInBundle is used to specify which bundle the general entity of a prov:mentionOf property is described.
    * 
    * When :x prov:mentionOf :y and :y is described in Bundle :b, the triple :x prov:asInBundle :b is also asserted to cite the Bundle in which :y was described.
    */
    asInBundle: prefixer('asInBundle'),

    /**
    * **[mentionOf](http://www.w3.org/ns/prov#mentionOf)** (property)
    * 
    * prov:mentionOf is used to specialize an entity as described in another bundle. It is to be used in conjuction with prov:asInBundle.
    * 
    * prov:asInBundle is used to cite the Bundle in which the generalization was mentioned.
    */
    mentionOf: prefixer('mentionOf'),

    /**
    * **[Plan](http://www.w3.org/ns/prov#Plan)** (class)
    * 
    * There exist no prescriptive requirement on the nature of plans, their representation, the actions or steps they consist of, or their intended goals. Since plans may evolve over time, it may become necessary to track their provenance, so plans themselves are entities. Representing the plan explicitly in the provenance can be useful for various tasks: for example, to validate the execution as represented in the provenance record, to manage expectation failures, or to provide explanations.
    */
    Plan: prefixer('Plan'),

    /**
    * **[describesService](http://www.w3.org/ns/prov#describesService)** (property)
    * 
    * relates a generic provenance query service resource (type prov:ServiceDescription) to a specific query service description (e.g. a prov:DirectQueryService or a sd:Service).
    */
    describesService: prefixer('describesService'),

    /**
    * **[PrimarySource](http://www.w3.org/ns/prov#PrimarySource)** (class)
    * 
    * An instance of prov:PrimarySource provides additional descriptions about the binary prov:hadPrimarySource relation from some secondary prov:Entity to an earlier, primary prov:Entity. For example, :blog prov:hadPrimarySource :newsArticle; prov:qualifiedPrimarySource [ a prov:PrimarySource; prov:entity :newsArticle; :foo :bar ] .
    */
    PrimarySource: prefixer('PrimarySource'),

    /**
    * **[Quotation](http://www.w3.org/ns/prov#Quotation)** (class)
    * 
    * An instance of prov:Quotation provides additional descriptions about the binary prov:wasQuotedFrom relation from some taken prov:Entity from an earlier, larger prov:Entity. For example, :here_is_looking_at_you_kid prov:wasQuotedFrom :casablanca_script; prov:qualifiedQuotation [ a prov:Quotation; prov:entity :casablanca_script; :foo :bar ].
    */
    Quotation: prefixer('Quotation'),

    /**
    * **[hadGeneration](http://www.w3.org/ns/prov#hadGeneration)** (property)
    * 
    * The _optional_ Generation involved in an Entity's Derivation.
    */
    hadGeneration: prefixer('hadGeneration'),

    /**
    * **[hadActivity](http://www.w3.org/ns/prov#hadActivity)** (property)
    * 
    * This property has multiple RDFS domains to suit multiple OWL Profiles. See <a href="#owl-profile">PROV-O OWL Profile</a>.
    */
    hadActivity: prefixer('hadActivity'),

    /**
    * **[Revision](http://www.w3.org/ns/prov#Revision)** (class)
    * 
    * An instance of prov:Revision provides additional descriptions about the binary prov:wasRevisionOf relation from some newer prov:Entity to an earlier prov:Entity. For example, :draft_2 prov:wasRevisionOf :draft_1; prov:qualifiedRevision [ a prov:Revision; prov:entity :draft_1; :foo :bar ].
    */
    Revision: prefixer('Revision'),

    /**
    * **[hadPlan](http://www.w3.org/ns/prov#hadPlan)** (property)
    * 
    * The _optional_ Plan adopted by an Agent in Association with some Activity. Plan specifications are out of the scope of this specification.
    */
    hadPlan: prefixer('hadPlan'),

    /**
    * **[qualifiedPrimarySource](http://www.w3.org/ns/prov#qualifiedPrimarySource)** (property)
    * 
    * If this Entity prov:hadPrimarySource Entity :e, then it can qualify how using prov:qualifiedPrimarySource [ a prov:PrimarySource; prov:entity :e; :foo :bar ].
    */
    qualifiedPrimarySource: prefixer('qualifiedPrimarySource'),

    /**
    * **[ServiceDescription](http://www.w3.org/ns/prov#ServiceDescription)** (class)
    * 
    * Type for a generic provenance query service. Mainly for use in RDF provenance query service descriptions, to facilitate discovery in linked data environments.
    */
    ServiceDescription: prefixer('ServiceDescription'),

    /**
    * **[hadUsage](http://www.w3.org/ns/prov#hadUsage)** (property)
    * 
    * The _optional_ Usage involved in an Entity's Derivation.
    */
    hadUsage: prefixer('hadUsage'),

    /**
    * **[Start](http://www.w3.org/ns/prov#Start)** (class)
    * 
    * An instance of prov:Start provides additional descriptions about the binary prov:wasStartedBy relation from some started prov:Activity to an prov:Entity that started it. For example, :foot_race prov:wasStartedBy :bang; prov:qualifiedStart [ a prov:Start; prov:entity :bang; :foo :bar; prov:atTime '2012-03-09T08:05:08-05:00'^^xsd:dateTime ] .
    */
    Start: prefixer('Start'),

    /**
    * **[has_anchor](http://www.w3.org/ns/prov#has_anchor)** (property)
    * 
    * Indicates anchor URI for a potentially dynamic resource instance.
    */
    has_anchor: prefixer('has_anchor'),

    /**
    * **[has_provenance](http://www.w3.org/ns/prov#has_provenance)** (property)
    * 
    * Indicates a provenance-URI for a resource; the resource identified by this property presents a provenance record about its subject or anchor resource.
    */
    has_provenance: prefixer('has_provenance'),

    /**
    * **[Usage](http://www.w3.org/ns/prov#Usage)** (class)
    * 
    * An instance of prov:Usage provides additional descriptions about the binary prov:used relation from some prov:Activity to an prov:Entity that it used. For example, :keynote prov:used :podium; prov:qualifiedUsage [ a prov:Usage; prov:entity :podium; :foo :bar ].
    */
    Usage: prefixer('Usage'),

    /**
    * **[hasProvenanceService](http://www.w3.org/ns/prov#has_query_service)** (property)
    * 
    * Indicates a provenance query service that can access provenance related to its subject or anchor resource.
    */
    has_query_service: prefixer('has_query_service'),

    /**
    * **[provenance pingback](http://www.w3.org/ns/prov#pingback)** (property)
    * 
    * Relates a resource to a provenance pingback service that may receive additional provenance links about the resource.
    */
    pingback: prefixer('pingback'),

    /**
    * **[qualifiedAssociation](http://www.w3.org/ns/prov#qualifiedAssociation)** (property)
    * 
    * If this Activity prov:wasAssociatedWith Agent :ag, then it can qualify the Association using prov:qualifiedAssociation [ a prov:Association;  prov:agent :ag; :foo :bar ].
    */
    qualifiedAssociation: prefixer('qualifiedAssociation'),

    /**
    * **[qualifiedInfluence](http://www.w3.org/ns/prov#qualifiedInfluence)** (property)
    * 
    * Because prov:qualifiedInfluence is a broad relation, the more specific relations (qualifiedCommunication, qualifiedDelegation, qualifiedEnd, etc.) should be used when applicable.
    */
    qualifiedInfluence: prefixer('qualifiedInfluence'),

    /**
    * **[qualifiedAttribution](http://www.w3.org/ns/prov#qualifiedAttribution)** (property)
    * 
    * If this Entity prov:wasAttributedTo Agent :ag, then it can qualify how it was influenced using prov:qualifiedAttribution [ a prov:Attribution;  prov:agent :ag; :foo :bar ].
    */
    qualifiedAttribution: prefixer('qualifiedAttribution'),

    /**
    * **[qualifiedCommunication](http://www.w3.org/ns/prov#qualifiedCommunication)** (property)
    * 
    * If this Activity prov:wasInformedBy Activity :a, then it can qualify how it was influenced using prov:qualifiedCommunication [ a prov:Communication;  prov:activity :a; :foo :bar ].
    */
    qualifiedCommunication: prefixer('qualifiedCommunication'),

    /**
    * **[qualifiedDerivation](http://www.w3.org/ns/prov#qualifiedDerivation)** (property)
    * 
    * If this Entity prov:wasDerivedFrom Entity :e, then it can qualify how it was derived using prov:qualifiedDerivation [ a prov:Derivation;  prov:entity :e; :foo :bar ].
    */
    qualifiedDerivation: prefixer('qualifiedDerivation'),

    /**
    * **[qualifiedEnd](http://www.w3.org/ns/prov#qualifiedEnd)** (property)
    * 
    * If this Activity prov:wasEndedBy Entity :e1, then it can qualify how it was ended using prov:qualifiedEnd [ a prov:End;  prov:entity :e1; :foo :bar ].
    */
    qualifiedEnd: prefixer('qualifiedEnd'),

    /**
    * **[qualifiedGeneration](http://www.w3.org/ns/prov#qualifiedGeneration)** (property)
    * 
    * If this Activity prov:generated Entity :e, then it can qualify how it performed the Generation using prov:qualifiedGeneration [ a prov:Generation;  prov:entity :e; :foo :bar ].
    */
    qualifiedGeneration: prefixer('qualifiedGeneration'),

    /**
    * **[qualifiedInvalidation](http://www.w3.org/ns/prov#qualifiedInvalidation)** (property)
    * 
    * If this Entity prov:wasInvalidatedBy Activity :a, then it can qualify how it was invalidated using prov:qualifiedInvalidation [ a prov:Invalidation;  prov:activity :a; :foo :bar ].
    */
    qualifiedInvalidation: prefixer('qualifiedInvalidation'),

    /**
    * **[qualifiedQuotation](http://www.w3.org/ns/prov#qualifiedQuotation)** (property)
    * 
    * If this Entity prov:wasQuotedFrom Entity :e, then it can qualify how using prov:qualifiedQuotation [ a prov:Quotation;  prov:entity :e; :foo :bar ].
    */
    qualifiedQuotation: prefixer('qualifiedQuotation'),

    /**
    * **[qualifiedRevision](http://www.w3.org/ns/prov#qualifiedRevision)** (property)
    * 
    * If this Entity prov:wasRevisionOf Entity :e, then it can qualify how it was revised using prov:qualifiedRevision [ a prov:Revision;  prov:entity :e; :foo :bar ].
    */
    qualifiedRevision: prefixer('qualifiedRevision'),

    /**
    * **[qualifiedStart](http://www.w3.org/ns/prov#qualifiedStart)** (property)
    * 
    * If this Activity prov:wasStartedBy Entity :e1, then it can qualify how it was started using prov:qualifiedStart [ a prov:Start;  prov:entity :e1; :foo :bar ].
    */
    qualifiedStart: prefixer('qualifiedStart'),

    /**
    * **[qualifiedUsage](http://www.w3.org/ns/prov#qualifiedUsage)** (property)
    * 
    * If this Activity prov:used Entity :e, then it can qualify how it used it using prov:qualifiedUsage [ a prov:Usage; prov:entity :e; :foo :bar ].
    */
    qualifiedUsage: prefixer('qualifiedUsage'),

    /**
    * **[atTime](http://www.w3.org/ns/prov#atTime)** (property)
    * 
    * The time at which an InstantaneousEvent occurred, in the form of xsd:dateTime.
    */
    atTime: prefixer('atTime'),

    /**
    * **[endedAtTime](http://www.w3.org/ns/prov#endedAtTime)** (property)
    * 
    * The time at which an activity ended. See also prov:startedAtTime.
    */
    endedAtTime: prefixer('endedAtTime'),

    /**
    * **[generatedAtTime](http://www.w3.org/ns/prov#generatedAtTime)** (property)
    * 
    * The time at which an entity was completely created and is available for use.
    */
    generatedAtTime: prefixer('generatedAtTime'),

    /**
    * **[invalidatedAtTime](http://www.w3.org/ns/prov#invalidatedAtTime)** (property)
    * 
    * The time at which an entity was invalidated (i.e., no longer usable).
    */
    invalidatedAtTime: prefixer('invalidatedAtTime'),

    /**
    * **[startedAtTime](http://www.w3.org/ns/prov#startedAtTime)** (property)
    * 
    * The time at which an activity started. See also prov:endedAtTime.
    */
    startedAtTime: prefixer('startedAtTime'),

    /**
    * **[provenanceUriTemplate](http://www.w3.org/ns/prov#provenanceUriTemplate)** (property)
    * 
    * Relates a provenance service to a URI template string for constructing provenance-URIs.
    */
    provenanceUriTemplate: prefixer('provenanceUriTemplate'),

  
  };

export default prov

