// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://purl.org/linked-data/cube#');

/**
 * [qb](http://purl.org/linked-data/cube#})
 */
const qb = {
  /**
    * **[Attachable (abstract)](http://purl.org/linked-data/cube#Attachable)** (class)
    * 
    * Abstract superclass for everything that can have attributes and dimensions
    */
    Attachable: prefixer('Attachable'),

    /**
    * **[Attribute property](http://purl.org/linked-data/cube#AttributeProperty)** (class)
    * 
    * The class of components which represent attributes of observations in the cube, e.g. unit of measurement
    */
    AttributeProperty: prefixer('AttributeProperty'),

    /**
    * **[Component property (abstract)](http://purl.org/linked-data/cube#ComponentProperty)** (class)
    * 
    * Abstract super-property of all properties representing dimensions, attributes or measures
    */
    ComponentProperty: prefixer('ComponentProperty'),

    /**
    * **[Measure property](http://purl.org/linked-data/cube#MeasureProperty)** (class)
    * 
    * The class of components which represent the measured value of the phenomenon being observed
    */
    MeasureProperty: prefixer('MeasureProperty'),

    /**
    * **[Coded property](http://purl.org/linked-data/cube#CodedProperty)** (class)
    * 
    * Superclass of all coded ComponentProperties
    */
    CodedProperty: prefixer('CodedProperty'),

    /**
    * **[Component set](http://purl.org/linked-data/cube#ComponentSet)** (class)
    * 
    * Abstract class of things which reference one or more ComponentProperties
    */
    ComponentSet: prefixer('ComponentSet'),

    /**
    * **[Component specification](http://purl.org/linked-data/cube#ComponentSpecification)** (class)
    * 
    * Used to define properties of a component (attribute, dimension etc) which are specific to its usage in a DSD.
    */
    ComponentSpecification: prefixer('ComponentSpecification'),

    /**
    * **[Data set](http://purl.org/linked-data/cube#DataSet)** (class)
    * 
    * Represents a collection of observations, possibly organized into various slices, conforming to some common dimensional structure.
    */
    DataSet: prefixer('DataSet'),

    /**
    * **[Data structure definition](http://purl.org/linked-data/cube#DataStructureDefinition)** (class)
    * 
    * Defines the structure of a DataSet or slice
    */
    DataStructureDefinition: prefixer('DataStructureDefinition'),

    /**
    * **[Dimension property](http://purl.org/linked-data/cube#DimensionProperty)** (class)
    * 
    * The class of components which represent the dimensions of the cube
    */
    DimensionProperty: prefixer('DimensionProperty'),

    /**
    * **[Hierarchical Code List](http://purl.org/linked-data/cube#HierarchicalCodeList)** (class)
    * 
    * Represents a generalized hierarchy of concepts which can be used for coding. The hierarchy is defined by one or more roots together with a property which relates concepts in the hierarchy to thier child concept .  The same concepts may be members of multiple hierarchies provided that different qb:parentChildProperty values are used for each hierarchy.
    */
    HierarchicalCodeList: prefixer('HierarchicalCodeList'),

    /**
    * **[Observation](http://purl.org/linked-data/cube#Observation)** (class)
    * 
    * A single observation in the cube, may have one or more associated measured values
    */
    Observation: prefixer('Observation'),

    /**
    * **[Observation Group](http://purl.org/linked-data/cube#ObservationGroup)** (class)
    * 
    * A, possibly arbitrary, group of observations.
    */
    ObservationGroup: prefixer('ObservationGroup'),

    /**
    * **[Slice](http://purl.org/linked-data/cube#Slice)** (class)
    * 
    * Denotes a subset of a DataSet defined by fixing a subset of the dimensional values, component properties on the Slice
    */
    Slice: prefixer('Slice'),

    /**
    * **[attribute](http://purl.org/linked-data/cube#attribute)** (property)
    * 
    * An alternative to qb:componentProperty which makes explicit that the component is a attribute
    */
    attribute: prefixer('attribute'),

    /**
    * **[Slice key](http://purl.org/linked-data/cube#SliceKey)** (class)
    * 
    * Denotes a subset of the component properties of a DataSet which are fixed in the corresponding slices
    */
    SliceKey: prefixer('SliceKey'),

    /**
    * **[component](http://purl.org/linked-data/cube#componentProperty)** (property)
    * 
    * indicates a ComponentProperty (i.e. attribute/dimension) expected on a DataSet, or a dimension fixed in a SliceKey
    */
    componentProperty: prefixer('componentProperty'),

    /**
    * **[code list](http://purl.org/linked-data/cube#codeList)** (property)
    * 
    * gives the code list associated with a CodedProperty
    */
    codeList: prefixer('codeList'),

    /**
    * **[component specification](http://purl.org/linked-data/cube#component)** (property)
    * 
    * indicates a component specification which is included in the structure of the dataset
    */
    component: prefixer('component'),

    /**
    * **[component attachment](http://purl.org/linked-data/cube#componentAttachment)** (property)
    * 
    * Indicates the level at which the component property should be attached, this might an qb:DataSet, qb:Slice or qb:Observation, or a qb:MeasureProperty.
    */
    componentAttachment: prefixer('componentAttachment'),

    /**
    * **[component required](http://purl.org/linked-data/cube#componentRequired)** (property)
    * 
    * Indicates whether a component property is required (true) or optional (false) in the context of a DSD. Only applicable
    * to components correspond to an attribute. Defaults to false (optional).
    */
    componentRequired: prefixer('componentRequired'),

    /**
    * **[concept](http://purl.org/linked-data/cube#concept)** (property)
    * 
    * gives the concept which is being measured or indicated by a ComponentProperty
    */
    concept: prefixer('concept'),

    /**
    * **[data set](http://purl.org/linked-data/cube#dataSet)** (property)
    * 
    * indicates the data set of which this observation is a part
    */
    dataSet: prefixer('dataSet'),

    /**
    * **[dimension](http://purl.org/linked-data/cube#dimension)** (property)
    * 
    * An alternative to qb:componentProperty which makes explicit that the component is a dimension
    */
    dimension: prefixer('dimension'),

    /**
    * **[measure](http://purl.org/linked-data/cube#measure)** (property)
    * 
    * An alternative to qb:componentProperty which makes explicit that the component is a measure
    */
    measure: prefixer('measure'),

    /**
    * **[measure dimension](http://purl.org/linked-data/cube#measureDimension)** (property)
    * 
    * An alternative to qb:componentProperty which makes explicit that the component is a measure dimension
    */
    measureDimension: prefixer('measureDimension'),

    /**
    * **[measure type](http://purl.org/linked-data/cube#measureType)** (property)
    * 
    * Generic measure dimension, the value of this dimension indicates which measure (from the set of measures in the DSD) is being given by the obsValue (or other primary measure)
    */
    measureType: prefixer('measureType'),

    /**
    * **[observation](http://purl.org/linked-data/cube#observation)** (property)
    * 
    * indicates a observation contained within this slice of the data set
    */
    observation: prefixer('observation'),

    /**
    * **[observation group](http://purl.org/linked-data/cube#observationGroup)** (property)
    * 
    * Indicates a group of observations. The domain of this property is left open so that a group may be attached to different resources and need not be restricted to a single DataSet
    */
    observationGroup: prefixer('observationGroup'),

    /**
    * **[order](http://purl.org/linked-data/cube#order)** (property)
    * 
    * indicates a priority order for the components of sets with this structure, used to guide presentations - lower order numbers come before higher numbers, un-numbered components come last
    */
    order: prefixer('order'),

    /**
    * **[parent-child property](http://purl.org/linked-data/cube#parentChildProperty)** (property)
    * 
    * Specifies a property which relates a parent concept in the hierarchy to a child concept.
    */
    parentChildProperty: prefixer('parentChildProperty'),

    /**
    * **[slice](http://purl.org/linked-data/cube#slice)** (property)
    * 
    * Indicates a subset of a DataSet defined by fixing a subset of the dimensional values
    */
    slice: prefixer('slice'),

    /**
    * **[slice key](http://purl.org/linked-data/cube#sliceKey)** (property)
    * 
    * indicates a slice key which is used for slices in this dataset
    */
    sliceKey: prefixer('sliceKey'),

    /**
    * **[slice structure](http://purl.org/linked-data/cube#sliceStructure)** (property)
    * 
    * indicates the sub-key corresponding to this slice
    */
    sliceStructure: prefixer('sliceStructure'),

    /**
    * **[structure](http://purl.org/linked-data/cube#structure)** (property)
    * 
    * indicates the structure to which this data set conforms
    */
    structure: prefixer('structure'),

  
  };

export default qb

