// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.w3.org/1999/02/22-rdf-syntax-ns#');

/**
 * [rdf](http://www.w3.org/1999/02/22-rdf-syntax-ns#})
 */
const rdf = {
  /**
    * **[type](http://www.w3.org/1999/02/22-rdf-syntax-ns#type)** (property)
    * 
    * The subject is an instance of a class.
    */
    type: prefixer('type'),

    /**
    * **[direction](http://www.w3.org/1999/02/22-rdf-syntax-ns#direction)** (property)
    * 
    * The base direction component of a CompoundLiteral.
    */
    direction: prefixer('direction'),

    /**
    * **[first](http://www.w3.org/1999/02/22-rdf-syntax-ns#first)** (property)
    * 
    * The first item in the subject RDF list.
    */
    first: prefixer('first'),

    /**
    * **[language](http://www.w3.org/1999/02/22-rdf-syntax-ns#language)** (property)
    * 
    * The language component of a CompoundLiteral.
    */
    language: prefixer('language'),

    /**
    * **[object](http://www.w3.org/1999/02/22-rdf-syntax-ns#object)** (property)
    * 
    * The object of the subject RDF statement.
    */
    object: prefixer('object'),

    /**
    * **[predicate](http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate)** (property)
    * 
    * The predicate of the subject RDF statement.
    */
    predicate: prefixer('predicate'),

    /**
    * **[rest](http://www.w3.org/1999/02/22-rdf-syntax-ns#rest)** (property)
    * 
    * The rest of the subject RDF list after the first item.
    */
    rest: prefixer('rest'),

    /**
    * **[subject](http://www.w3.org/1999/02/22-rdf-syntax-ns#subject)** (property)
    * 
    * The subject of the subject RDF statement.
    */
    subject: prefixer('subject'),

    /**
    * **[value](http://www.w3.org/1999/02/22-rdf-syntax-ns#value)** (property)
    * 
    * Idiomatic property used for structured values.
    */
    value: prefixer('value'),

    /**
    * **[Alt](http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt)** (class)
    * 
    * The class of containers of alternatives.
    */
    Alt: prefixer('Alt'),

    /**
    * **[Bag](http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag)** (class)
    * 
    * The class of unordered containers.
    */
    Bag: prefixer('Bag'),

    /**
    * **[CompoundLiteral](http://www.w3.org/1999/02/22-rdf-syntax-ns#CompoundLiteral)** (class)
    * 
    * A class representing a compound literal.
    */
    CompoundLiteral: prefixer('CompoundLiteral'),

    /**
    * **[List](http://www.w3.org/1999/02/22-rdf-syntax-ns#List)** (class)
    * 
    * The class of RDF Lists.
    */
    List: prefixer('List'),

    /**
    * **[Property](http://www.w3.org/1999/02/22-rdf-syntax-ns#Property)** (class)
    * 
    * The class of RDF properties.
    */
    Property: prefixer('Property'),

    /**
    * **[Seq](http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq)** (class)
    * 
    * The class of ordered containers.
    */
    Seq: prefixer('Seq'),

    /**
    * **[Statement](http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement)** (class)
    * 
    * The class of RDF statements.
    */
    Statement: prefixer('Statement'),

  
  };

export default rdf

