// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://purl.org/stuff/rev#');

/**
 * [rev](http://purl.org/stuff/rev#})
 */
const rev = {
  /**
    * **[positiveVotes](http://purl.org/stuff/rev#positiveVotes)** (property)
    * 
    * Number of positive usefulness votes (integer)
    */
    positiveVotes: prefixer('positiveVotes'),

    /**
    * **[rating](http://purl.org/stuff/rev#rating)** (property)
    * 
    * A numeric value
    */
    rating: prefixer('rating'),

    /**
    * **[text](http://purl.org/stuff/rev#text)** (property)
    * 
    * The text of the review
    */
    text: prefixer('text'),

    /**
    * **[title](http://purl.org/stuff/rev#title)** (property)
    * 
    * The title of the review
    */
    title: prefixer('title'),

    /**
    * **[totalVotes](http://purl.org/stuff/rev#totalVotes)** (property)
    * 
    * Number of usefulness votes (integer)
    */
    totalVotes: prefixer('totalVotes'),

    /**
    * **[Comment](http://purl.org/stuff/rev#Comment)** (class)
    * 
    * A comment on a review
    */
    Comment: prefixer('Comment'),

    /**
    * **[type](http://purl.org/stuff/rev#type)** (property)
    * 
    * The type of media of a work under review
    */
    type: prefixer('type'),

    /**
    * **[Feedback](http://purl.org/stuff/rev#Feedback)** (class)
    * 
    * Feedback on the review. Expresses whether the review was useful or not
    */
    Feedback: prefixer('Feedback'),

    /**
    * **[Review](http://purl.org/stuff/rev#Review)** (class)
    * 
    * A review of an work
    */
    Review: prefixer('Review'),

    /**
    * **[commenter](http://purl.org/stuff/rev#commenter)** (property)
    * 
    * The commenter on the review
    */
    commenter: prefixer('commenter'),

    /**
    * **[hasComment](http://purl.org/stuff/rev#hasComment)** (property)
    * 
    * Used to associate a review with a comment on the review
    */
    hasComment: prefixer('hasComment'),

    /**
    * **[hasFeedback](http://purl.org/stuff/rev#hasFeedback)** (property)
    * 
    * Associates a review with a feedback on the review
    */
    hasFeedback: prefixer('hasFeedback'),

    /**
    * **[has Review](http://purl.org/stuff/rev#hasReview)** (property)
    * 
    * Associates a work with a a review
    */
    hasReview: prefixer('hasReview'),

    /**
    * **[max Rating](http://purl.org/stuff/rev#maxRating)** (property)
    * 
    * A numeric value
    */
    maxRating: prefixer('maxRating'),

    /**
    * **[min Rating](http://purl.org/stuff/rev#minRating)** (property)
    * 
    * A numeric value
    */
    minRating: prefixer('minRating'),

    /**
    * **[reviewer](http://purl.org/stuff/rev#reviewer)** (property)
    * 
    * The person that has written the review
    */
    reviewer: prefixer('reviewer'),

  
  };

export default rev

