// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://purl.org/rss/1.0/');

/**
 * [rss](http://purl.org/rss/1.0/})
 */
const rss = {
  /**
    * **[Channel](http://purl.org/rss/1.0/channel)** (class)
    * 
    * An RSS information channel.
    */
    channel: prefixer('channel'),

    /**
    * **[Image](http://purl.org/rss/1.0/image)** (class)
    * 
    * An RSS image.
    */
    image: prefixer('image'),

    /**
    * **[Item](http://purl.org/rss/1.0/item)** (class)
    * 
    * An RSS item.
    */
    item: prefixer('item'),

    /**
    * **[Text Input](http://purl.org/rss/1.0/textinput)** (class)
    * 
    * An RSS text input.
    */
    textinput: prefixer('textinput'),

    /**
    * **[Description](http://purl.org/rss/1.0/description)** (property)
    * 
    * A short text description of the subject.
    */
    description: prefixer('description'),

    /**
    * **[Items](http://purl.org/rss/1.0/items)** (property)
    * 
    * Points to a list of rss:item elements that are members of the subject channel.
    */
    items: prefixer('items'),

    /**
    * **[Link](http://purl.org/rss/1.0/link)** (property)
    * 
    * The URL to which an HTML rendering of the subject will link.
    */
    link: prefixer('link'),

    /**
    * **[Name](http://purl.org/rss/1.0/name)** (property)
    * 
    * The text input field's (variable) name.
    */
    name: prefixer('name'),

    /**
    * **[Title](http://purl.org/rss/1.0/title)** (property)
    * 
    * A descriptive title for the channel.
    */
    title: prefixer('title'),

    /**
    * **[URL](http://purl.org/rss/1.0/url)** (property)
    * 
    * The URL of the image to used in the 'src' attribute of the channel's image tag when rendered as HTML.
    */
    url: prefixer('url'),

  
  };

export default rss

