// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://rdfs.org/sioc/ns#');

/**
 * [sioc](http://rdfs.org/sioc/ns#})
 */
const sioc = {
  /**
    * **[content](http://rdfs.org/sioc/ns#content)** (property)
    * 
    * The content of the Item in plain text format.
    */
    content: prefixer('content'),

    /**
    * **[content encoded](http://rdfs.org/sioc/ns#content_encoded)** (property)
    * 
    * The encoded content of the Post, contained in CDATA areas.
    */
    content_encoded: prefixer('content_encoded'),

    /**
    * **[created at](http://rdfs.org/sioc/ns#created_at)** (property)
    * 
    * When this was created, in ISO 8601 format.
    */
    created_at: prefixer('created_at'),

    /**
    * **[delivered at](http://rdfs.org/sioc/ns#delivered_at)** (property)
    * 
    * When this was delivered, in ISO 8601 format.
    */
    delivered_at: prefixer('delivered_at'),

    /**
    * **[description](http://rdfs.org/sioc/ns#description)** (property)
    * 
    * The content of the Post.
    */
    description: prefixer('description'),

    /**
    * **[email sha1](http://rdfs.org/sioc/ns#email_sha1)** (property)
    * 
    * An electronic mail address of the UserAccount, encoded using SHA1.
    */
    email_sha1: prefixer('email_sha1'),

    /**
    * **[first name](http://rdfs.org/sioc/ns#first_name)** (property)
    * 
    * First (real) name of this User. Synonyms include given name or christian name.
    */
    first_name: prefixer('first_name'),

    /**
    * **[id](http://rdfs.org/sioc/ns#id)** (property)
    * 
    * An identifier of a SIOC concept instance. For example, a user ID. Must be unique for instances of each type of SIOC concept within the same site.
    */
    id: prefixer('id'),

    /**
    * **[ip address](http://rdfs.org/sioc/ns#ip_address)** (property)
    * 
    * The IP address used when creating this Item, UserAccount, etc. This can be associated with a creator. Some wiki articles list the IP addresses for the creator or modifiers when the usernames are absent.
    */
    ip_address: prefixer('ip_address'),

    /**
    * **[last activity date](http://rdfs.org/sioc/ns#last_activity_date)** (property)
    * 
    * The date and time of the last activity associated with a SIOC concept instance, and expressed in ISO 8601 format. This could be due to a reply Post or Comment, a modification to an Item, etc.
    */
    last_activity_date: prefixer('last_activity_date'),

    /**
    * **[last item date](http://rdfs.org/sioc/ns#last_item_date)** (property)
    * 
    * The date and time of the last Post (or Item) in a Forum (or a Container), in ISO 8601 format.
    */
    last_item_date: prefixer('last_item_date'),

    /**
    * **[last name](http://rdfs.org/sioc/ns#last_name)** (property)
    * 
    * Last (real) name of this user. Synonyms include surname or family name.
    */
    last_name: prefixer('last_name'),

    /**
    * **[last reply date](http://rdfs.org/sioc/ns#last_reply_date)** (property)
    * 
    * The date and time of the last reply Post or Comment, which could be associated with a starter Item or Post or with a Thread, and expressed in ISO 8601 format.
    */
    last_reply_date: prefixer('last_reply_date'),

    /**
    * **[modified at](http://rdfs.org/sioc/ns#modified_at)** (property)
    * 
    * When this was modified, in ISO 8601 format.
    */
    modified_at: prefixer('modified_at'),

    /**
    * **[Community](http://rdfs.org/sioc/ns#Community)** (class)
    * 
    * Community is a high-level concept that defines an online community and what it consists of.
    */
    Community: prefixer('Community'),

    /**
    * **[name](http://rdfs.org/sioc/ns#name)** (property)
    * 
    * The name of a SIOC concept instance, e.g. a username for a UserAccount, group name for a Usergroup, etc.
    */
    name: prefixer('name'),

    /**
    * **[Item](http://rdfs.org/sioc/ns#Item)** (class)
    * 
    * An Item is something which can be in a Container.
    */
    Item: prefixer('Item'),

    /**
    * **[note](http://rdfs.org/sioc/ns#note)** (property)
    * 
    * A note associated with this resource, for example, if it has been edited by a UserAccount.
    */
    note: prefixer('note'),

    /**
    * **[Role](http://rdfs.org/sioc/ns#Role)** (class)
    * 
    * A Role is a function of a UserAccount within a scope of a particular Forum, Site, etc.
    */
    Role: prefixer('Role'),

    /**
    * **[num authors](http://rdfs.org/sioc/ns#num_authors)** (property)
    * 
    * The number of unique authors (UserAccounts and unregistered posters) who have contributed to this Item, Thread, Post, etc.
    */
    num_authors: prefixer('num_authors'),

    /**
    * **[User Account](http://rdfs.org/sioc/ns#UserAccount)** (class)
    * 
    * A user account in an online community site.
    */
    UserAccount: prefixer('UserAccount'),

    /**
    * **[num items](http://rdfs.org/sioc/ns#num_items)** (property)
    * 
    * The number of Posts (or Items) in a Forum (or a Container).
    */
    num_items: prefixer('num_items'),

    /**
    * **[Container](http://rdfs.org/sioc/ns#Container)** (class)
    * 
    * An area in which content Items are contained.
    */
    Container: prefixer('Container'),

    /**
    * **[num replies](http://rdfs.org/sioc/ns#num_replies)** (property)
    * 
    * The number of replies that this Item, Thread, Post, etc. has. Useful for when the reply structure is absent.
    */
    num_replies: prefixer('num_replies'),

    /**
    * **[Usergroup](http://rdfs.org/sioc/ns#Usergroup)** (class)
    * 
    * A set of UserAccounts whose owners have a common purpose or interest. Can be used for access control purposes.
    */
    Usergroup: prefixer('Usergroup'),

    /**
    * **[num threads](http://rdfs.org/sioc/ns#num_threads)** (property)
    * 
    * The number of Threads (AKA discussion topics) in a Forum.
    */
    num_threads: prefixer('num_threads'),

    /**
    * **[Forum](http://rdfs.org/sioc/ns#Forum)** (class)
    * 
    * A discussion area on which Posts or entries are made.
    */
    Forum: prefixer('Forum'),

    /**
    * **[num views](http://rdfs.org/sioc/ns#num_views)** (property)
    * 
    * The number of times this Item, Thread, UserAccount profile, etc. has been viewed.
    */
    num_views: prefixer('num_views'),

    /**
    * **[Space](http://rdfs.org/sioc/ns#Space)** (class)
    * 
    * A Space is a place where data resides, e.g. on a website, desktop, fileshare, etc.
    */
    Space: prefixer('Space'),

    /**
    * **[read at](http://rdfs.org/sioc/ns#read_at)** (property)
    * 
    * When this was read, in ISO 8601 format.
    */
    read_at: prefixer('read_at'),

    /**
    * **[Post](http://rdfs.org/sioc/ns#Post)** (class)
    * 
    * An article or message that can be posted to a Forum.
    */
    Post: prefixer('Post'),

    /**
    * **[subject](http://rdfs.org/sioc/ns#subject)** (property)
    * 
    * Keyword(s) describing subject of the Post.
    */
    subject: prefixer('subject'),

    /**
    * **[title](http://rdfs.org/sioc/ns#title)** (property)
    * 
    * This is the title (subject line) of the Post. Note that for a Post within a threaded discussion that has no parents, it would detail the topic thread.
    */
    title: prefixer('title'),

    /**
    * **[Site](http://rdfs.org/sioc/ns#Site)** (class)
    * 
    * A Site can be the location of an online community or set of communities, with UserAccounts and Usergroups creating Items in a set of Containers. It can be thought of as a web-accessible data Space.
    */
    Site: prefixer('Site'),

    /**
    * **[Thread](http://rdfs.org/sioc/ns#Thread)** (class)
    * 
    * A container for a series of threaded discussion Posts or Items.
    */
    Thread: prefixer('Thread'),

    /**
    * **[about](http://rdfs.org/sioc/ns#about)** (property)
    * 
    * Specifies that this Item is about a particular resource, e.g. a Post describing a book, hotel, etc.
    */
    about: prefixer('about'),

    /**
    * **[account of](http://rdfs.org/sioc/ns#account_of)** (property)
    * 
    * Refers to the foaf:Agent or foaf:Person who owns this sioc:UserAccount.
    */
    account_of: prefixer('account_of'),

    /**
    * **[addressed to](http://rdfs.org/sioc/ns#addressed_to)** (property)
    * 
    * Refers to who (e.g. a UserAccount, e-mail address, etc.) a particular Item is addressed to.
    */
    addressed_to: prefixer('addressed_to'),

    /**
    * **[administrator of](http://rdfs.org/sioc/ns#administrator_of)** (property)
    * 
    * A Site that the UserAccount is an administrator of.
    */
    administrator_of: prefixer('administrator_of'),

    /**
    * **[has administrator](http://rdfs.org/sioc/ns#has_administrator)** (property)
    * 
    * A UserAccount that is an administrator of this Site.
    */
    has_administrator: prefixer('has_administrator'),

    /**
    * **[attachment](http://rdfs.org/sioc/ns#attachment)** (property)
    * 
    * The URI of a file attached to an Item.
    */
    attachment: prefixer('attachment'),

    /**
    * **[avatar](http://rdfs.org/sioc/ns#avatar)** (property)
    * 
    * An image or depiction used to represent this UserAccount.
    */
    avatar: prefixer('avatar'),

    /**
    * **[container of](http://rdfs.org/sioc/ns#container_of)** (property)
    * 
    * An Item that this Container contains.
    */
    container_of: prefixer('container_of'),

    /**
    * **[has container](http://rdfs.org/sioc/ns#has_container)** (property)
    * 
    * The Container to which this Item belongs.
    */
    has_container: prefixer('has_container'),

    /**
    * **[creator of](http://rdfs.org/sioc/ns#creator_of)** (property)
    * 
    * A resource that the UserAccount is a creator of.
    */
    creator_of: prefixer('creator_of'),

    /**
    * **[has creator](http://rdfs.org/sioc/ns#has_creator)** (property)
    * 
    * This is the UserAccount that made this resource.
    */
    has_creator: prefixer('has_creator'),

    /**
    * **[discussion of](http://rdfs.org/sioc/ns#discussion_of)** (property)
    * 
    * The Item that this discussion is about.
    */
    discussion_of: prefixer('discussion_of'),

    /**
    * **[has discussion](http://rdfs.org/sioc/ns#has_discussion)** (property)
    * 
    * A discussion that is related to this Item. The discussion can be anything, for example, a sioc:Forum or sioc:Thread, a sioct:WikiArticle or simply a foaf:Document.
    */
    has_discussion: prefixer('has_discussion'),

    /**
    * **[email](http://rdfs.org/sioc/ns#email)** (property)
    * 
    * An electronic mail address of the UserAccount.
    */
    email: prefixer('email'),

    /**
    * **[embeds knowledge](http://rdfs.org/sioc/ns#embeds_knowledge)** (property)
    * 
    * This links Items to embedded statements, facts and structured content.
    */
    embeds_knowledge: prefixer('embeds_knowledge'),

    /**
    * **[feed](http://rdfs.org/sioc/ns#feed)** (property)
    * 
    * A feed (e.g. RSS, Atom, etc.) pertaining to this resource (e.g. for a Forum, Site, UserAccount, etc.).
    */
    feed: prefixer('feed'),

    /**
    * **[follows](http://rdfs.org/sioc/ns#follows)** (property)
    * 
    * Indicates that one UserAccount follows another UserAccount (e.g. for microblog posts or other content item updates).
    */
    follows: prefixer('follows'),

    /**
    * **[function of](http://rdfs.org/sioc/ns#function_of)** (property)
    * 
    * A UserAccount that has this Role.
    */
    function_of: prefixer('function_of'),

    /**
    * **[has function](http://rdfs.org/sioc/ns#has_function)** (property)
    * 
    * A Role that this UserAccount has.
    */
    has_function: prefixer('has_function'),

    /**
    * **[generator](http://rdfs.org/sioc/ns#generator)** (property)
    * 
    * A URI for the application used to generate this Item.
    */
    generator: prefixer('generator'),

    /**
    * **[has host](http://rdfs.org/sioc/ns#has_host)** (property)
    * 
    * The Site that hosts this Container.
    */
    has_host: prefixer('has_host'),

    /**
    * **[has space](http://rdfs.org/sioc/ns#has_space)** (property)
    * 
    * A data Space which this resource is a part of.
    */
    has_space: prefixer('has_space'),

    /**
    * **[host of](http://rdfs.org/sioc/ns#host_of)** (property)
    * 
    * A Container that is hosted on this Site.
    */
    host_of: prefixer('host_of'),

    /**
    * **[has member](http://rdfs.org/sioc/ns#has_member)** (property)
    * 
    * A UserAccount that is a member of this Usergroup.
    */
    has_member: prefixer('has_member'),

    /**
    * **[member of](http://rdfs.org/sioc/ns#member_of)** (property)
    * 
    * A Usergroup that this UserAccount is a member of.
    */
    member_of: prefixer('member_of'),

    /**
    * **[has moderator](http://rdfs.org/sioc/ns#has_moderator)** (property)
    * 
    * A UserAccount that is a moderator of this Forum.
    */
    has_moderator: prefixer('has_moderator'),

    /**
    * **[moderator of](http://rdfs.org/sioc/ns#moderator_of)** (property)
    * 
    * A Forum that a UserAccount is a moderator of.
    */
    moderator_of: prefixer('moderator_of'),

    /**
    * **[has modifier](http://rdfs.org/sioc/ns#has_modifier)** (property)
    * 
    * A UserAccount that modified this resource (e.g. Item, Container, Space).
    */
    has_modifier: prefixer('has_modifier'),

    /**
    * **[modifier of](http://rdfs.org/sioc/ns#modifier_of)** (property)
    * 
    * A resource that this UserAccount has modified.
    */
    modifier_of: prefixer('modifier_of'),

    /**
    * **[has owner](http://rdfs.org/sioc/ns#has_owner)** (property)
    * 
    * A UserAccount that this resource is owned by.
    */
    has_owner: prefixer('has_owner'),

    /**
    * **[owner of](http://rdfs.org/sioc/ns#owner_of)** (property)
    * 
    * A resource owned by a particular UserAccount, for example, a weblog or image gallery.
    */
    owner_of: prefixer('owner_of'),

    /**
    * **[has parent](http://rdfs.org/sioc/ns#has_parent)** (property)
    * 
    * A Container or Forum that this Container or Forum is a child of.
    */
    has_parent: prefixer('has_parent'),

    /**
    * **[parent of](http://rdfs.org/sioc/ns#parent_of)** (property)
    * 
    * A child Container or Forum that this Container or Forum is a parent of.
    */
    parent_of: prefixer('parent_of'),

    /**
    * **[has part](http://rdfs.org/sioc/ns#has_part)** (property)
    * 
    * An resource that is a part of this subject.
    */
    has_part: prefixer('has_part'),

    /**
    * **[part of](http://rdfs.org/sioc/ns#part_of)** (property)
    * 
    * A resource that the subject is a part of.
    */
    part_of: prefixer('part_of'),

    /**
    * **[has reply](http://rdfs.org/sioc/ns#has_reply)** (property)
    * 
    * Points to an Item or Post that is a reply or response to this Item or Post.
    */
    has_reply: prefixer('has_reply'),

    /**
    * **[related to](http://rdfs.org/sioc/ns#related_to)** (property)
    * 
    * Related resources for this resource, e.g. for Posts, perhaps determined implicitly from topics or references.
    */
    related_to: prefixer('related_to'),

    /**
    * **[reply of](http://rdfs.org/sioc/ns#reply_of)** (property)
    * 
    * Links to an Item or Post which this Item or Post is a reply to.
    */
    reply_of: prefixer('reply_of'),

    /**
    * **[has scope](http://rdfs.org/sioc/ns#has_scope)** (property)
    * 
    * A resource that this Role applies to.
    */
    has_scope: prefixer('has_scope'),

    /**
    * **[scope of](http://rdfs.org/sioc/ns#scope_of)** (property)
    * 
    * A Role that has a scope of this resource.
    */
    scope_of: prefixer('scope_of'),

    /**
    * **[space of](http://rdfs.org/sioc/ns#space_of)** (property)
    * 
    * A resource which belongs to this data Space.
    */
    space_of: prefixer('space_of'),

    /**
    * **[has subscriber](http://rdfs.org/sioc/ns#has_subscriber)** (property)
    * 
    * A UserAccount that is subscribed to this Container.
    */
    has_subscriber: prefixer('has_subscriber'),

    /**
    * **[subscriber of](http://rdfs.org/sioc/ns#subscriber_of)** (property)
    * 
    * A Container that a UserAccount is subscribed to.
    */
    subscriber_of: prefixer('subscriber_of'),

    /**
    * **[has usergroup](http://rdfs.org/sioc/ns#has_usergroup)** (property)
    * 
    * Points to a Usergroup that has certain access to this Space.
    */
    has_usergroup: prefixer('has_usergroup'),

    /**
    * **[usergroup of](http://rdfs.org/sioc/ns#usergroup_of)** (property)
    * 
    * A Space that the Usergroup has access to.
    */
    usergroup_of: prefixer('usergroup_of'),

    /**
    * **[latest version](http://rdfs.org/sioc/ns#latest_version)** (property)
    * 
    * Links to the latest revision of this Item or Post.
    */
    latest_version: prefixer('latest_version'),

    /**
    * **[likes](http://rdfs.org/sioc/ns#likes)** (property)
    * 
    * Used to indicate some form of endorsement by a UserAccount or Agent of an Item, Container, Space, UserAccount, etc.
    */
    likes: prefixer('likes'),

    /**
    * **[link](http://rdfs.org/sioc/ns#link)** (property)
    * 
    * A URI of a document which contains this SIOC object.
    */
    link: prefixer('link'),

    /**
    * **[links to](http://rdfs.org/sioc/ns#links_to)** (property)
    * 
    * Links extracted from hyperlinks within a SIOC concept, e.g. Post or Site.
    */
    links_to: prefixer('links_to'),

    /**
    * **[mentions](http://rdfs.org/sioc/ns#mentions)** (property)
    * 
    * Refers to a UserAccount that a particular Item mentions.
    */
    mentions: prefixer('mentions'),

    /**
    * **[next by date](http://rdfs.org/sioc/ns#next_by_date)** (property)
    * 
    * Next Item or Post in a given Container sorted by date.
    */
    next_by_date: prefixer('next_by_date'),

    /**
    * **[previous by date](http://rdfs.org/sioc/ns#previous_by_date)** (property)
    * 
    * Previous Item or Post in a given Container sorted by date.
    */
    previous_by_date: prefixer('previous_by_date'),

    /**
    * **[next version](http://rdfs.org/sioc/ns#next_version)** (property)
    * 
    * Links to the next revision of this Item or Post.
    */
    next_version: prefixer('next_version'),

    /**
    * **[previous version](http://rdfs.org/sioc/ns#previous_version)** (property)
    * 
    * Links to the previous revision of this Item or Post.
    */
    previous_version: prefixer('previous_version'),

    /**
    * **[reference](http://rdfs.org/sioc/ns#reference)** (property)
    * 
    * Links either created explicitly or extracted implicitly on the HTML level from the Post.
    */
    reference: prefixer('reference'),

    /**
    * **[respond to](http://rdfs.org/sioc/ns#respond_to)** (property)
    * 
    * For the reply-to address set in email messages, IMs, etc. The property name was chosen to avoid confusion with has_reply/reply_of (the reply graph).
    */
    respond_to: prefixer('respond_to'),

    /**
    * **[shared by](http://rdfs.org/sioc/ns#shared_by)** (property)
    * 
    * For shared Items where there is a certain creator_of and an intermediary who shares or forwards it (e.g. as a sibling Item).
    */
    shared_by: prefixer('shared_by'),

    /**
    * **[topic](http://rdfs.org/sioc/ns#topic)** (property)
    * 
    * A topic of interest, linking to the appropriate URI, e.g. in the Open Directory Project or of a SKOS category.
    */
    topic: prefixer('topic'),

  
  };

export default sioc

