// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://purl.org/vocab/vann/');

/**
 * [vann](http://purl.org/vocab/vann/})
 */
const vann = {
  /**
    * **[Preferred Namespace Prefix](http://purl.org/vocab/vann/preferredNamespacePrefix)** (property)
    * 
    * The preferred namespace prefix to use when using terms from this vocabulary in an XML document.
    */
    preferredNamespacePrefix: prefixer('preferredNamespacePrefix'),

    /**
    * **[Preferred Namespace Uri](http://purl.org/vocab/vann/preferredNamespaceUri)** (property)
    * 
    * The preferred namespace URI to use when using terms from this vocabulary in an XML document.
    */
    preferredNamespaceUri: prefixer('preferredNamespaceUri'),

    /**
    * **[Changes](http://purl.org/vocab/vann/changes)** (property)
    * 
    * A reference to a resource that describes changes between this version of a vocabulary and the previous.
    */
    changes: prefixer('changes'),

    /**
    * **[Example](http://purl.org/vocab/vann/example)** (property)
    * 
    * A reference to a resource that provides an example of how this resource can be used.
    */
    example: prefixer('example'),

    /**
    * **[Term Group](http://purl.org/vocab/vann/termGroup)** (property)
    * 
    * A group of related terms in a vocabulary.
    */
    termGroup: prefixer('termGroup'),

    /**
    * **[Usage Note](http://purl.org/vocab/vann/usageNote)** (property)
    * 
    * A reference to a resource that provides information on how this resource is to be used.
    */
    usageNote: prefixer('usageNote'),

  
  };

export default vann

