// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://rdfs.org/ns/void#');

/**
 * [void](http://rdfs.org/ns/void#})
 */
const $void = {
  /**
    * **[dataset](http://rdfs.org/ns/void#Dataset)** (class)
    * 
    * A set of RDF triples that are published, maintained or aggregated by a single provider.
    */
    Dataset: prefixer('Dataset'),

    /**
    * **[dataset description](http://rdfs.org/ns/void#DatasetDescription)** (class)
    * 
    * A web resource whose foaf:primaryTopic or foaf:topics include void:Datasets.
    */
    DatasetDescription: prefixer('DatasetDescription'),

    /**
    * **[linkset](http://rdfs.org/ns/void#Linkset)** (class)
    * 
    * A collection of RDF links between two void:Datasets.
    */
    Linkset: prefixer('Linkset'),

    /**
    * **[technical feature](http://rdfs.org/ns/void#TechnicalFeature)** (class)
    * 
    * A technical feature of a void:Dataset, such as a supported RDF serialization format.
    */
    TechnicalFeature: prefixer('TechnicalFeature'),

    /**
    * **[class partition](http://rdfs.org/ns/void#classPartition)** (property)
    * 
    * A subset of a void:Dataset that contains only the entities of a certain rdfs:Class.
    */
    classPartition: prefixer('classPartition'),

    /**
    * **[Data Dump](http://rdfs.org/ns/void#dataDump)** (property)
    * 
    * An RDF dump, partial or complete, of a void:Dataset.
    */
    dataDump: prefixer('dataDump'),

    /**
    * **[in dataset](http://rdfs.org/ns/void#inDataset)** (property)
    * 
    * Points to the void:Dataset that a document is a part of.
    */
    inDataset: prefixer('inDataset'),

    /**
    * **[Target](http://rdfs.org/ns/void#target)** (property)
    * 
    * One of the two datasets linked by the Linkset.
    */
    target: prefixer('target'),

    /**
    * **[open search description](http://rdfs.org/ns/void#openSearchDescription)** (property)
    * 
    * An OpenSearch description document for a free-text search service over a void:Dataset.
    */
    openSearchDescription: prefixer('openSearchDescription'),

    /**
    * **[property partition](http://rdfs.org/ns/void#propertyPartition)** (property)
    * 
    * A subset of a void:Dataset that contains only the triples of a certain rdf:Property.
    */
    propertyPartition: prefixer('propertyPartition'),

    /**
    * **[root resource](http://rdfs.org/ns/void#rootResource)** (property)
    * 
    * A top concept or entry point for a void:Dataset that is structured in a tree-like fashion. All resources in a dataset can be reached by following links from its root resources in a small number of steps.
    */
    rootResource: prefixer('rootResource'),

    /**
    * **[has an URI look-up endpoint at](http://rdfs.org/ns/void#uriLookupEndpoint)** (property)
    * 
    * Defines a simple URI look-up protocol for accessing a dataset.
    */
    uriLookupEndpoint: prefixer('uriLookupEndpoint'),

    /**
    * **[vocabulary](http://rdfs.org/ns/void#vocabulary)** (property)
    * 
    * A vocabulary that is used in the dataset.
    */
    vocabulary: prefixer('vocabulary'),

    /**
    * **[classes](http://rdfs.org/ns/void#classes)** (property)
    * 
    * The total number of distinct classes in a void:Dataset. In other words, the number of distinct resources occuring as objects of rdf:type triples in the dataset.
    */
    classes: prefixer('classes'),

    /**
    * **[distinct objects](http://rdfs.org/ns/void#distinctObjects)** (property)
    * 
    * The total number of distinct objects in a void:Dataset. In other words, the number of distinct resources that occur in the object position of triples in the dataset. Literals are included in this count.
    */
    distinctObjects: prefixer('distinctObjects'),

    /**
    * **[distinct subjects](http://rdfs.org/ns/void#distinctSubjects)** (property)
    * 
    * The total number of distinct subjects in a void:Dataset. In other words, the number of distinct resources that occur in the subject position of triples in the dataset.
    */
    distinctSubjects: prefixer('distinctSubjects'),

    /**
    * **[number of documents](http://rdfs.org/ns/void#documents)** (property)
    * 
    * The total number of documents, for datasets that are published as a set of individual documents, such as RDF/XML documents or RDFa-annotated web pages. Non-RDF documents, such as web pages in HTML or images, are usually not included in this count. This property is intended for datasets where the total number of triples or entities is hard to determine. void:triples or void:entities should be preferred where practical.
    */
    documents: prefixer('documents'),

    /**
    * **[number of entities](http://rdfs.org/ns/void#entities)** (property)
    * 
    * The total number of entities that are described in a void:Dataset.
    */
    entities: prefixer('entities'),

    /**
    * **[number of properties](http://rdfs.org/ns/void#properties)** (property)
    * 
    * The total number of distinct properties in a void:Dataset. In other words, the number of distinct resources that occur in the predicate position of triples in the dataset.
    */
    properties: prefixer('properties'),

    /**
    * **[number of triples](http://rdfs.org/ns/void#triples)** (property)
    * 
    * The total number of triples contained in a void:Dataset.
    */
    triples: prefixer('triples'),

    /**
    * **[URI space](http://rdfs.org/ns/void#uriSpace)** (property)
    * 
    * A URI that is a common string prefix of all the entity URIs in a void:Dataset.
    */
    uriSpace: prefixer('uriSpace'),

  
  };

export default $void

