// This file is generated by the build script. Do not edit it manually.
import { prefixer as $prefixer } from '../utilities.js';
const prefixer = $prefixer('http://www.w3.org/2003/06/sw-vocab-status/ns#');

/**
 * [vs](http://www.w3.org/2003/06/sw-vocab-status/ns#})
 */
const vs = {
  /**
    * **[more info](http://www.w3.org/2003/06/sw-vocab-status/ns#moreinfo)** (property)
    * 
    * more information about the status etc of a term, typically human oriented
    */
    moreinfo: prefixer('moreinfo'),

    /**
    * **[term status](http://www.w3.org/2003/06/sw-vocab-status/ns#term_status)** (property)
    * 
    * the status of a vocabulary term, expressed as a short symbolic string; known values include 'unstable','testing', 'stable' and 'archaic'
    */
    term_status: prefixer('term_status'),

    /**
    * **[user docs](http://www.w3.org/2003/06/sw-vocab-status/ns#userdocs)** (property)
    * 
    * human-oriented documentation, examples etc for use of this term
    */
    userdocs: prefixer('userdocs'),

  
  };

export default vs

